import type { CodeChallenge, Difficulty, FreelanceCategory, FreelanceJob, GigLaneId } from "./types.ts";

export type GigLane = {
  id: GigLaneId;
  title: string;
  blurb: string;
  unlockAfter: number;
};

export const GIG_LANES: GigLane[] = [
  { id: "starter", title: "Starter desk", blurb: "Print, fix a typo, ship a one-liner.", unlockAfter: 1 },
  { id: "numbers", title: "Numbers desk", blurb: "Bills, wages, leftover seats.", unlockAfter: 3 },
  { id: "logic", title: "Logic desk", blurb: "Pass, fail, warn, convert.", unlockAfter: 5 },
  { id: "text", title: "Text desk", blurb: "Names, tags, and clean strings.", unlockAfter: 8 },
  { id: "loops", title: "Loops desk", blurb: "Count, filter, repeat.", unlockAfter: 11 },
  { id: "lists", title: "Lists desk", blurb: "Menus, tickets, top scores.", unlockAfter: 15 },
  { id: "records", title: "Records desk", blurb: "Lookups, reports, tiny APIs.", unlockAfter: 20 },
  { id: "methods", title: "Methods desk", blurb: "Split, replace, classify.", unlockAfter: 30 },
  { id: "studio", title: "Studio desk", blurb: "Zip, Fizz, clamp, unique.", unlockAfter: 50 },
  { id: "craft", title: "Craft desk", blurb: "Pipelines, ciphers, nested data.", unlockAfter: 75 },
];

function ch(partial: CodeChallenge): CodeChallenge {
  return partial;
}

function gig(def: Omit<FreelanceJob, "challenge"> & { challenge: CodeChallenge }): FreelanceJob {
  return def;
}

export const GIGS: FreelanceJob[] = [
  gig({
    id: "gig-cafe-open",
    title: "Cafe chalkboard",
    client: "Mina Cho",
    company: "Northshore Cafe",
    category: "utility",
    lane: "starter",
    unlockAfter: 1,
    difficulty: "Easy",
    pay: 220,
    xp: 40,
    skills: ["print()", "strings"],
    summary: "Print the morning sign exactly.",
    brief: "Mina needs the board to show OPEN 8AM — capitals, space, no extra words. Simulated cafe, simulated pay.",
    challenge: ch({
      id: "gig-cafe-open",
      title: "Print the sign",
      concept: "print() and strings",
      prompt: "Print exactly: OPEN 8AM",
      briefing: "Quotes wrap the message. print() shows it without the quotes.",
      example: "print(\"OPEN 8AM\")",
      starter: "# Print the chalkboard line.\n",
      expected: "OPEN 8AM\n",
      solution: "print(\"OPEN 8AM\")",
      hints: ["Use print() with parentheses.", "Put OPEN 8AM inside quotes.", "Match capitals and the space."],
    }),
  }),
  gig({
    id: "gig-hello-bug",
    title: "Fix the greeting bug",
    client: "Jules Adeyemi",
    company: "Harbor Helpdesk",
    category: "bugfix",
    lane: "starter",
    unlockAfter: 1,
    difficulty: "Easy",
    pay: 240,
    xp: 45,
    skills: ["debugging", "strings"],
    summary: "Hello prints a NameError. Add quotes.",
    brief: "A trainee shipped print(Hello) without quotes. Python looks for a variable named Hello. Fix it so the screen shows Hello.",
    challenge: ch({
      id: "gig-hello-bug",
      title: "Quotes around the word",
      concept: "NameError vs string",
      prompt: "The starter crashes. Make it print Hello.",
      briefing: "A bare name is a variable. A quoted name is text.",
      example: "print(\"Hello\")",
      starter: "print(Hello)\n",
      expected: "Hello\n",
      solution: "print(\"Hello\")",
      hints: ["Hello without quotes is a missing variable.", "Wrap Hello in quotes.", "print(\"Hello\")"],
    }),
  }),
  gig({
    id: "gig-sms-hi",
    title: "Welcome SMS",
    client: "Priya Shah",
    company: "Brightlane School",
    category: "utility",
    lane: "starter",
    unlockAfter: 1,
    difficulty: "Easy",
    pay: 200,
    xp: 40,
    skills: ["print()", "punctuation"],
    summary: "Send a one-line welcome text.",
    brief: "Print Hi, Maya — comma and capital M. This is a practice SMS, not a real message to a person.",
    challenge: ch({
      id: "gig-sms-hi",
      title: "One-line text",
      concept: "Exact strings",
      prompt: "Print exactly: Hi, Maya",
      briefing: "Match the comma and the space after it.",
      example: "print(\"Hi, Maya\")",
      starter: "# Type the print line.\n",
      expected: "Hi, Maya\n",
      solution: "print(\"Hi, Maya\")",
      hints: ["Include the comma.", "Capital M in Maya.", "print(\"Hi, Maya\")"],
    }),
  }),
  gig({
    id: "gig-receipt-head",
    title: "Receipt header",
    client: "Owen Park",
    company: "Drift Market",
    category: "utility",
    lane: "starter",
    unlockAfter: 1,
    difficulty: "Easy",
    pay: 210,
    xp: 40,
    skills: ["print()"],
    summary: "Print the store name on a dummy receipt.",
    brief: "Owen wants the receipt simulator to start with NORTHSHORE in capitals. Not a real register.",
    challenge: ch({
      id: "gig-receipt-head",
      title: "Store name",
      concept: "print()",
      prompt: "Print NORTHSHORE",
      briefing: "One print, all caps, no extra spaces.",
      example: "print(\"NORTHSHORE\")",
      starter: "# Header line.\n",
      expected: "NORTHSHORE\n",
      solution: "print(\"NORTHSHORE\")",
      hints: ["All capitals.", "No spaces.", "print(\"NORTHSHORE\")"],
    }),
  }),
  gig({
    id: "gig-status-ok",
    title: "Health-check ping",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "automation",
    lane: "starter",
    unlockAfter: 1,
    difficulty: "Easy",
    pay: 230,
    xp: 45,
    skills: ["print()", "status strings"],
    summary: "A tiny uptime script should print STATUS OK.",
    brief: "Simulated monitor. Print STATUS OK so the dashboard test turns green.",
    challenge: ch({
      id: "gig-status-ok",
      title: "Ping the board",
      concept: "print()",
      prompt: "Print STATUS OK",
      briefing: "Space between the two words. Both caps.",
      example: "print(\"STATUS OK\")",
      starter: "# Status line.\n",
      expected: "STATUS OK\n",
      solution: "print(\"STATUS OK\")",
      hints: ["Two words.", "STATUS then a space then OK.", "print(\"STATUS OK\")"],
    }),
  }),

  gig({
    id: "gig-tip-math",
    title: "Tip calculator",
    client: "Mina Cho",
    company: "Northshore Cafe",
    category: "utility",
    lane: "numbers",
    unlockAfter: 3,
    difficulty: "Easy",
    pay: 320,
    xp: 55,
    skills: ["variables", "addition"],
    summary: "Bill 50 plus a 5 tip.",
    brief: "Print the total after a $5 tip on a $50 bill. Virtual cafe math — not real money.",
    challenge: ch({
      id: "gig-tip-math",
      title: "Add the tip",
      concept: "variables and +",
      prompt: "Store bill 50 and tip 5. Print bill + tip.",
      briefing: "Names hold numbers. + adds them. print shows the total.",
      example: "bill = 50\ntip = 5\nprint(bill + tip)",
      starter: "bill = 50\ntip = 5\n",
      expected: "55\n",
      solution: "bill = 50\ntip = 5\nprint(bill + tip)",
      hints: ["You already have bill and tip.", "Add them: bill + tip", "print(bill + tip)"],
    }),
  }),
  gig({
    id: "gig-hours-pay",
    title: "Shift payout",
    client: "Chris Vale",
    company: "Harbor Logistics",
    category: "utility",
    lane: "numbers",
    unlockAfter: 3,
    difficulty: "Easy",
    pay: 340,
    xp: 55,
    skills: ["multiplication"],
    summary: "8 hours times 15 an hour.",
    brief: "Print 8 * 15 for a simulated warehouse shift. Not a real payroll.",
    challenge: ch({
      id: "gig-hours-pay",
      title: "Hours times rate",
      concept: "multiplication",
      prompt: "Print 8 * 15",
      briefing: "* multiplies. No quotes around numbers.",
      example: "print(8 * 15)",
      starter: "hours = 8\nrate = 15\n",
      expected: "120\n",
      solution: "hours = 8\nrate = 15\nprint(hours * rate)",
      hints: ["Use hours * rate", "print the product", "120 is the target"],
    }),
  }),
  gig({
    id: "gig-seats-left",
    title: "Seats remaining",
    client: "Priya Shah",
    company: "Brightlane School",
    category: "utility",
    lane: "numbers",
    unlockAfter: 3,
    difficulty: "Easy",
    pay: 300,
    xp: 50,
    skills: ["subtraction"],
    summary: "40 seats minus 12 taken.",
    brief: "Print how many seats are left. Classroom simulator.",
    challenge: ch({
      id: "gig-seats-left",
      title: "Subtract taken seats",
      concept: "subtraction",
      prompt: "Print 40 - 12",
      briefing: "- subtracts. print shows the leftover.",
      example: "print(40 - 12)",
      starter: "seats = 40\ntaken = 12\n",
      expected: "28\n",
      solution: "seats = 40\ntaken = 12\nprint(seats - taken)",
      hints: ["seats - taken", "print that value", "28"],
    }),
  }),
  gig({
    id: "gig-double-score",
    title: "Bonus round",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "game",
    lane: "numbers",
    unlockAfter: 3,
    difficulty: "Easy",
    pay: 310,
    xp: 50,
    skills: ["variables", "multiplication"],
    summary: "Double a score of 21.",
    brief: "A mini-game prototype needs the score doubled. Print 42.",
    challenge: ch({
      id: "gig-double-score",
      title: "Times two",
      concept: "multiply a variable",
      prompt: "score is 21. Print score * 2.",
      briefing: "You can multiply a stored number.",
      example: "score = 21\nprint(score * 2)",
      starter: "score = 21\n",
      expected: "42\n",
      solution: "score = 21\nprint(score * 2)",
      hints: ["score * 2", "print it", "42"],
    }),
  }),
  gig({
    id: "gig-min-hours",
    title: "Minutes to hours",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "utility",
    lane: "numbers",
    unlockAfter: 3,
    difficulty: "Easy / Medium",
    pay: 360,
    xp: 60,
    skills: ["// integer division"],
    summary: "150 minutes in whole hours.",
    brief: "Use // so 150 minutes becomes 2 hours. Drop the leftover minutes.",
    challenge: ch({
      id: "gig-min-hours",
      title: "Integer divide",
      concept: "//",
      prompt: "Print 150 // 60",
      briefing: "// divides and keeps the whole number. 150 // 60 is 2.",
      example: "print(150 // 60)",
      starter: "minutes = 150\n",
      expected: "2\n",
      solution: "minutes = 150\nprint(minutes // 60)",
      hints: ["Use // not /", "minutes // 60", "print 2"],
    }),
  }),

  gig({
    id: "gig-pass-gate",
    title: "Exam gate",
    client: "Priya Shah",
    company: "Brightlane School",
    category: "utility",
    lane: "logic",
    unlockAfter: 5,
    difficulty: "Easy / Medium",
    pay: 420,
    xp: 70,
    skills: ["if", "comparison"],
    summary: "Score 82 — print PASS or FAIL at 70.",
    brief: "If score >= 70 print PASS else FAIL. Simulated grade, not a real transcript.",
    challenge: ch({
      id: "gig-pass-gate",
      title: "Pass at 70",
      concept: "if / else",
      prompt: "score is 82. Print PASS if score >= 70, else FAIL.",
      briefing: "if asks a yes/no. Colon, then indent the print.",
      example: "if score >= 70:\n    print(\"PASS\")\nelse:\n    print(\"FAIL\")",
      starter: "score = 82\n",
      expected: "PASS\n",
      solution: "score = 82\nif score >= 70:\n    print(\"PASS\")\nelse:\n    print(\"FAIL\")",
      hints: ["if score >= 70:", "print PASS on that branch", "82 passes"],
    }),
  }),
  gig({
    id: "gig-age-check",
    title: "Door check",
    client: "Owen Park",
    company: "Drift Market",
    category: "utility",
    lane: "logic",
    unlockAfter: 5,
    difficulty: "Easy",
    pay: 400,
    xp: 65,
    skills: ["if", ">= "],
    summary: "Age 19 — print YES if 18+.",
    brief: "A simulated event door. Print YES or NO.",
    challenge: ch({
      id: "gig-age-check",
      title: "Eighteen and up",
      concept: "if / else",
      prompt: "age is 19. Print YES if age >= 18, else NO.",
      briefing: ">= means at least.",
      example: "if age >= 18:\n    print(\"YES\")",
      starter: "age = 19\n",
      expected: "YES\n",
      solution: "age = 19\nif age >= 18:\n    print(\"YES\")\nelse:\n    print(\"NO\")",
      hints: ["if age >= 18:", "print YES", "else print NO"],
    }),
  }),
  gig({
    id: "gig-discount",
    title: "Basket discount",
    client: "Mina Cho",
    company: "Northshore Cafe",
    category: "utility",
    lane: "logic",
    unlockAfter: 5,
    difficulty: "Easy / Medium",
    pay: 440,
    xp: 75,
    skills: ["if", "reassignment"],
    summary: "Over 50? Take 10 off 80.",
    brief: "If price > 50, subtract 10, then print the price.",
    challenge: ch({
      id: "gig-discount",
      title: "Conditional markdown",
      concept: "if then assign",
      prompt: "price is 80. If price > 50, set price = price - 10. Then print price.",
      briefing: "You can change a variable inside an if.",
      example: "if price > 50:\n    price = price - 10\nprint(price)",
      starter: "price = 80\n",
      expected: "70\n",
      solution: "price = 80\nif price > 50:\n    price = price - 10\nprint(price)",
      hints: ["if price > 50:", "price = price - 10", "print(price) after the if"],
    }),
  }),
  gig({
    id: "gig-temp-c",
    title: "Weather convert",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "utility",
    lane: "logic",
    unlockAfter: 5,
    difficulty: "Medium",
    pay: 460,
    xp: 80,
    skills: ["integer math", "//"],
    summary: "77 F to C with integer math.",
    brief: "Print (77 - 32) * 5 // 9 which is 25. Sensor prototype, not a live weather feed.",
    challenge: ch({
      id: "gig-temp-c",
      title: "F to C",
      concept: "order of operations",
      prompt: "Print (77 - 32) * 5 // 9",
      briefing: "Parentheses first. // keeps a whole number.",
      example: "print((77 - 32) * 5 // 9)",
      starter: "f = 77\n",
      expected: "25\n",
      solution: "f = 77\nprint((f - 32) * 5 // 9)",
      hints: ["Subtract 32 first", "Then * 5 // 9", "Target is 25"],
    }),
  }),
  gig({
    id: "gig-stock-warn",
    title: "Low-stock ping",
    client: "Chris Vale",
    company: "Harbor Logistics",
    category: "automation",
    lane: "logic",
    unlockAfter: 5,
    difficulty: "Easy / Medium",
    pay: 430,
    xp: 70,
    skills: ["if", "inventory"],
    summary: "Qty 2 — print LOW if under 5.",
    brief: "Warehouse simulator. Print LOW or OK.",
    challenge: ch({
      id: "gig-stock-warn",
      title: "Warn under five",
      concept: "if / else",
      prompt: "qty is 2. Print LOW if qty < 5, else OK.",
      briefing: "< means strictly less than.",
      example: "if qty < 5:\n    print(\"LOW\")",
      starter: "qty = 2\n",
      expected: "LOW\n",
      solution: "qty = 2\nif qty < 5:\n    print(\"LOW\")\nelse:\n    print(\"OK\")",
      hints: ["if qty < 5:", "print LOW", "2 is low"],
    }),
  }),

  gig({
    id: "gig-upper-name",
    title: "Badge press",
    client: "Jules Adeyemi",
    company: "Harbor Helpdesk",
    category: "utility",
    lane: "text",
    unlockAfter: 8,
    difficulty: "Easy",
    pay: 480,
    xp: 80,
    skills: [".upper()"],
    summary: "Turn ada into ADA.",
    brief: "Name badges want capitals. Print ADA.",
    challenge: ch({
      id: "gig-upper-name",
      title: "Uppercase a name",
      concept: "str.upper",
      prompt: "Print \"ada\".upper()",
      briefing: ".upper() returns a new string in capitals.",
      example: "print(\"ada\".upper())",
      starter: "name = \"ada\"\n",
      expected: "ADA\n",
      solution: "name = \"ada\"\nprint(name.upper())",
      hints: ["name.upper()", "print that", "ADA"],
    }),
  }),
  gig({
    id: "gig-join-hello",
    title: "Lobby greeting",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "utility",
    lane: "text",
    unlockAfter: 8,
    difficulty: "Easy",
    pay: 470,
    xp: 75,
    skills: ["concatenation"],
    summary: "Hi + name.",
    brief: "Print Hi Leo using the stored name.",
    challenge: ch({
      id: "gig-join-hello",
      title: "Join two strings",
      concept: "string +",
      prompt: "name is Leo. Print \"Hi \" + name",
      briefing: "+ sticks strings together. Include the space after Hi.",
      example: "print(\"Hi \" + name)",
      starter: "name = \"Leo\"\n",
      expected: "Hi Leo\n",
      solution: "name = \"Leo\"\nprint(\"Hi \" + name)",
      hints: ["\"Hi \" has a trailing space", "Add name", "print the join"],
    }),
  }),
  gig({
    id: "gig-len-handle",
    title: "Handle length",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "data",
    lane: "text",
    unlockAfter: 8,
    difficulty: "Easy",
    pay: 460,
    xp: 75,
    skills: ["len()"],
    summary: "How many letters in pixel?",
    brief: "Print len(\"pixel\") which is 5. Signup form simulator.",
    challenge: ch({
      id: "gig-len-handle",
      title: "Count characters",
      concept: "len",
      prompt: "Print the length of \"pixel\".",
      briefing: "len counts characters in a string.",
      example: "print(len(\"pixel\"))",
      starter: "handle = \"pixel\"\n",
      expected: "5\n",
      solution: "handle = \"pixel\"\nprint(len(handle))",
      hints: ["len(handle)", "print it", "5 letters"],
    }),
  }),
  gig({
    id: "gig-strip-tag",
    title: "Clean a tag",
    client: "Owen Park",
    company: "Drift Market",
    category: "data",
    lane: "text",
    unlockAfter: 8,
    difficulty: "Easy / Medium",
    pay: 500,
    xp: 85,
    skills: [".strip()"],
    summary: "Trim spaces around done.",
    brief: "Scanner padding left extra spaces. Print done with no padding.",
    challenge: ch({
      id: "gig-strip-tag",
      title: "strip() the edges",
      concept: "str.strip",
      prompt: "Print \"  done  \".strip()",
      briefing: "strip() removes spaces from both ends, not the middle.",
      example: "print(\"  done  \".strip())",
      starter: "tag = \"  done  \"\n",
      expected: "done\n",
      solution: "tag = \"  done  \"\nprint(tag.strip())",
      hints: ["tag.strip()", "print the result", "No extra spaces"],
    }),
  }),
  gig({
    id: "gig-initials",
    title: "Monogram",
    client: "Priya Shah",
    company: "Brightlane School",
    category: "utility",
    lane: "text",
    unlockAfter: 8,
    difficulty: "Easy / Medium",
    pay: 520,
    xp: 90,
    skills: ["indexes"],
    summary: "First letters of Ada Lovelace.",
    brief: "Print AL using index 0 of each name.",
    challenge: ch({
      id: "gig-initials",
      title: "Index 0 + index 0",
      concept: "string indexes",
      prompt: "Print first[0] + last[0] for Ada Lovelace.",
      briefing: "Indexes start at 0. first[0] is A.",
      example: "print(first[0] + last[0])",
      starter: "first = \"Ada\"\nlast = \"Lovelace\"\n",
      expected: "AL\n",
      solution: "first = \"Ada\"\nlast = \"Lovelace\"\nprint(first[0] + last[0])",
      hints: ["first[0] is A", "last[0] is L", "Add the two characters"],
    }),
  }),

  gig({
    id: "gig-sum-hours",
    title: "Timesheet total",
    client: "Chris Vale",
    company: "Harbor Logistics",
    category: "data",
    lane: "loops",
    unlockAfter: 11,
    difficulty: "Easy / Medium",
    pay: 560,
    xp: 95,
    skills: ["sum()", "lists"],
    summary: "Add 3, 4, and 5 hours.",
    brief: "Print sum([3, 4, 5]). Simulated timesheet.",
    challenge: ch({
      id: "gig-sum-hours",
      title: "Sum a list",
      concept: "sum",
      prompt: "Print the sum of [3, 4, 5].",
      briefing: "sum adds every number in a list.",
      example: "print(sum([3, 4, 5]))",
      starter: "hours = [3, 4, 5]\n",
      expected: "12\n",
      solution: "hours = [3, 4, 5]\nprint(sum(hours))",
      hints: ["sum(hours)", "print it", "12"],
    }),
  }),
  gig({
    id: "gig-count-even",
    title: "Even-lot counter",
    client: "Owen Park",
    company: "Drift Market",
    category: "data",
    lane: "loops",
    unlockAfter: 11,
    difficulty: "Medium",
    pay: 620,
    xp: 110,
    skills: ["for", "%", "counters"],
    summary: "How many evens in 1..6?",
    brief: "Loop the list. If x % 2 == 0, add one. Print the count.",
    challenge: ch({
      id: "gig-count-even",
      title: "Count even numbers",
      concept: "for + remainder",
      prompt: "Count how many values in [1, 2, 3, 4, 5, 6] are even. Print that count.",
      briefing: "% 2 == 0 means even. Keep a counter.",
      example: "n = 0\nfor x in nums:\n    if x % 2 == 0:\n        n = n + 1\nprint(n)",
      starter: "nums = [1, 2, 3, 4, 5, 6]\nn = 0\n",
      expected: "3\n",
      solution: "nums = [1, 2, 3, 4, 5, 6]\nn = 0\nfor x in nums:\n    if x % 2 == 0:\n        n = n + 1\nprint(n)",
      hints: ["for x in nums:", "if x % 2 == 0", "n = n + 1, then print n"],
    }),
  }),
  gig({
    id: "gig-table-row",
    title: "Times-table row",
    client: "Priya Shah",
    company: "Brightlane School",
    category: "game",
    lane: "loops",
    unlockAfter: 11,
    difficulty: "Easy / Medium",
    pay: 580,
    xp: 100,
    skills: ["for", "range"],
    summary: "Print 3, 6, 9, 12 each on its line.",
    brief: "Worksheet generator. One number per line.",
    challenge: ch({
      id: "gig-table-row",
      title: "3 times 1..4",
      concept: "for range",
      prompt: "Print 3*1, 3*2, 3*3, 3*4 each on a new line.",
      briefing: "range(1, 5) is 1, 2, 3, 4.",
      example: "for i in range(1, 5):\n    print(3 * i)",
      starter: "# Print four lines.\n",
      expected: "3\n6\n9\n12\n",
      solution: "for i in range(1, 5):\n    print(3 * i)",
      hints: ["for i in range(1, 5):", "print(3 * i)", "Four lines"],
    }),
  }),
  gig({
    id: "gig-filter-pass",
    title: "Passing scores",
    client: "Jules Adeyemi",
    company: "Harbor Helpdesk",
    category: "data",
    lane: "loops",
    unlockAfter: 11,
    difficulty: "Medium",
    pay: 640,
    xp: 110,
    skills: ["for", "if", "filter"],
    summary: "Print scores that are 70 or more.",
    brief: "From [55, 70, 90] print 70 then 90. Training data, not real students.",
    challenge: ch({
      id: "gig-filter-pass",
      title: "Keep the passes",
      concept: "filter with for",
      prompt: "Loop [55, 70, 90]. Print each score that is >= 70.",
      briefing: "if inside a for keeps some items and skips others.",
      example: "for s in scores:\n    if s >= 70:\n        print(s)",
      starter: "scores = [55, 70, 90]\n",
      expected: "70\n90\n",
      solution: "scores = [55, 70, 90]\nfor s in scores:\n    if s >= 70:\n        print(s)",
      hints: ["for s in scores:", "if s >= 70", "print(s)"],
    }),
  }),
  gig({
    id: "gig-countdown",
    title: "Launch countdown",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "game",
    lane: "loops",
    unlockAfter: 11,
    difficulty: "Easy / Medium",
    pay: 540,
    xp: 90,
    skills: ["for", "print"],
    summary: "3, 2, 1, then GO.",
    brief: "Game boot screen. Four lines.",
    challenge: ch({
      id: "gig-countdown",
      title: "Count then GO",
      concept: "for over a list",
      prompt: "Print 3, then 2, then 1, then GO — four lines.",
      briefing: "Loop [3, 2, 1], then one more print.",
      example: "for n in [3, 2, 1]:\n    print(n)\nprint(\"GO\")",
      starter: "# Countdown.\n",
      expected: "3\n2\n1\nGO\n",
      solution: "for n in [3, 2, 1]:\n    print(n)\nprint(\"GO\")",
      hints: ["Loop 3, 2, 1", "print each n", "Then print GO"],
    }),
  }),

  gig({
    id: "gig-append-ticket",
    title: "New ticket",
    client: "Jules Adeyemi",
    company: "Harbor Helpdesk",
    category: "automation",
    lane: "lists",
    unlockAfter: 15,
    difficulty: "Easy / Medium",
    pay: 680,
    xp: 115,
    skills: [".append()", "indexes"],
    summary: "Append 12 and print the last ticket.",
    brief: "Queue simulator. Start [10, 11], append 12, print index 2.",
    challenge: ch({
      id: "gig-append-ticket",
      title: "append then index",
      concept: "list.append",
      prompt: "tix starts as [10, 11]. Append 12. Print tix[2].",
      briefing: "append adds at the end. Indexes start at 0, so the third item is [2].",
      example: "tix.append(12)\nprint(tix[2])",
      starter: "tix = [10, 11]\n",
      expected: "12\n",
      solution: "tix = [10, 11]\ntix.append(12)\nprint(tix[2])",
      hints: ["tix.append(12)", "print(tix[2])", "append returns None — print the list item"],
    }),
  }),
  gig({
    id: "gig-replace-item",
    title: "Menu swap",
    client: "Mina Cho",
    company: "Northshore Cafe",
    category: "utility",
    lane: "lists",
    unlockAfter: 15,
    difficulty: "Easy / Medium",
    pay: 660,
    xp: 110,
    skills: ["index assign"],
    summary: "Change bread to rice.",
    brief: "menu = [soup, bread, tea]. Replace index 1. Print the new index 1.",
    challenge: ch({
      id: "gig-replace-item",
      title: "Assign at an index",
      concept: "list[i] = value",
      prompt: "Set menu[1] to \"rice\". Print menu[1].",
      briefing: "You can replace an existing slot. You cannot assign past the end — use append for that.",
      example: "menu[1] = \"rice\"\nprint(menu[1])",
      starter: "menu = [\"soup\", \"bread\", \"tea\"]\n",
      expected: "rice\n",
      solution: "menu = [\"soup\", \"bread\", \"tea\"]\nmenu[1] = \"rice\"\nprint(menu[1])",
      hints: ["menu[1] = \"rice\"", "print(menu[1])", "Index 1 is the second item"],
    }),
  }),
  gig({
    id: "gig-slice-log",
    title: "Log window",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "data",
    lane: "lists",
    unlockAfter: 15,
    difficulty: "Medium",
    pay: 720,
    xp: 120,
    skills: ["slices"],
    summary: "Print the first two log lines.",
    brief: "A file-like list of lines. Slice [0:2] and print both.",
    challenge: ch({
      id: "gig-slice-log",
      title: "Slice start:end",
      concept: "list slices",
      prompt: "log = [\"boot\", \"ok\", \"sync\"]. Take log[0:2]. Print both items, one per line.",
      briefing: "start:end goes up to but not including end. [0:2] is indexes 0 and 1.",
      example: "part = log[0:2]\nprint(part[0])\nprint(part[1])",
      starter: "log = [\"boot\", \"ok\", \"sync\"]\n",
      expected: "boot\nok\n",
      solution: "log = [\"boot\", \"ok\", \"sync\"]\npart = log[0:2]\nprint(part[0])\nprint(part[1])",
      hints: ["log[0:2]", "Print part[0] then part[1]", "boot then ok"],
    }),
  }),
  gig({
    id: "gig-top-score",
    title: "High score",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "game",
    lane: "lists",
    unlockAfter: 15,
    difficulty: "Easy",
    pay: 640,
    xp: 100,
    skills: ["max()"],
    summary: "Best of 4, 17, 9.",
    brief: "Print max of the list. Arcade prototype.",
    challenge: ch({
      id: "gig-top-score",
      title: "max of a list",
      concept: "max",
      prompt: "Print max([4, 17, 9])",
      briefing: "max returns the largest number.",
      example: "print(max(scores))",
      starter: "scores = [4, 17, 9]\n",
      expected: "17\n",
      solution: "scores = [4, 17, 9]\nprint(max(scores))",
      hints: ["max(scores)", "print it", "17"],
    }),
  }),
  gig({
    id: "gig-index-swap",
    title: "Rotate the rack",
    client: "Chris Vale",
    company: "Harbor Logistics",
    category: "automation",
    lane: "lists",
    unlockAfter: 15,
    difficulty: "Medium",
    pay: 740,
    xp: 125,
    skills: ["indexes", "swap"],
    summary: "Swap first and last of [1, 2, 3].",
    brief: "Print the new first, then the new last. Should be 3 then 1.",
    challenge: ch({
      id: "gig-index-swap",
      title: "Swap ends",
      concept: "temporary swap",
      prompt: "a = [1, 2, 3]. Swap a[0] and a[2]. Print a[0] then a[2].",
      briefing: "Use a tmp box, or a[0], a[2] = a[2], a[0].",
      example: "tmp = a[0]\na[0] = a[2]\na[2] = tmp",
      starter: "a = [1, 2, 3]\n",
      expected: "3\n1\n",
      solution: "a = [1, 2, 3]\ntmp = a[0]\na[0] = a[2]\na[2] = tmp\nprint(a[0])\nprint(a[2])",
      hints: ["Save a[0] in tmp", "a[0] = a[2], then a[2] = tmp", "Print 3 then 1"],
    }),
  }),

  gig({
    id: "gig-lookup-role",
    title: "Staff lookup",
    client: "Jules Adeyemi",
    company: "Harbor Helpdesk",
    category: "api",
    lane: "records",
    unlockAfter: 20,
    difficulty: "Easy / Medium",
    pay: 780,
    xp: 130,
    skills: ["dictionaries"],
    summary: "Print Ada's role from a dict.",
    brief: "A tiny simulated API payload. Print Engineer.",
    challenge: ch({
      id: "gig-lookup-role",
      title: "Dict key access",
      concept: "dict[key]",
      prompt: "staff maps Ada to Engineer. Print staff[\"Ada\"].",
      briefing: "Keys are strings. Spell the key exactly.",
      example: "print(staff[\"Ada\"])",
      starter: "staff = {\"Ada\": \"Engineer\"}\n",
      expected: "Engineer\n",
      solution: "staff = {\"Ada\": \"Engineer\"}\nprint(staff[\"Ada\"])",
      hints: ["staff[\"Ada\"]", "Quotes around Ada", "print the role"],
    }),
  }),
  gig({
    id: "gig-safe-get",
    title: "Missing field",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "api",
    lane: "records",
    unlockAfter: 20,
    difficulty: "Medium",
    pay: 800,
    xp: 140,
    skills: [".get()"],
    summary: "Look up a key that is not there.",
    brief: "user has name only. Print user.get(\"role\") which is None — no crash.",
    challenge: ch({
      id: "gig-safe-get",
      title: "get never explodes",
      concept: "dict.get",
      prompt: "Print user.get(\"role\") for a user that only has name.",
      briefing: ".get(key) returns None when the key is missing. [] would raise KeyError.",
      example: "print(user.get(\"role\"))",
      starter: "user = {\"name\": \"Nia\"}\n",
      expected: "None\n",
      solution: "user = {\"name\": \"Nia\"}\nprint(user.get(\"role\"))",
      hints: ["user.get(\"role\")", "Missing keys become None", "print it"],
    }),
  }),
  gig({
    id: "gig-report-fn",
    title: "ID labeler",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "report",
    lane: "records",
    unlockAfter: 20,
    difficulty: "Medium",
    pay: 820,
    xp: 145,
    skills: ["functions", "str()"],
    summary: "A function that returns id=7.",
    brief: "Write label(n) that returns \"id=\" + str(n). Print label(7).",
    challenge: ch({
      id: "gig-report-fn",
      title: "def + return",
      concept: "functions",
      prompt: "Define label(n) that returns id= plus the number. Print label(7).",
      briefing: "str(n) turns a number into text so you can add it to a string.",
      example: "def label(n):\n    return \"id=\" + str(n)\nprint(label(7))",
      starter: "def label(n):\n    return \"\"\n",
      expected: "id=7\n",
      solution: "def label(n):\n    return \"id=\" + str(n)\nprint(label(7))",
      hints: ["return \"id=\" + str(n)", "Call print(label(7))", "No extra spaces"],
    }),
  }),
  gig({
    id: "gig-filter-roster",
    title: "Active roster",
    client: "Chris Vale",
    company: "Harbor Logistics",
    category: "data",
    lane: "records",
    unlockAfter: 20,
    difficulty: "Medium",
    pay: 860,
    xp: 150,
    skills: ["list of dicts", "for"],
    summary: "Print names where ok is True.",
    brief: "Simulated crew list. Print Ada only.",
    challenge: ch({
      id: "gig-filter-roster",
      title: "Walk records",
      concept: "nested fields",
      prompt: "Loop people. If p[\"ok\"], print p[\"name\"].",
      briefing: "Each p is a dictionary. p[\"ok\"] is True or False.",
      example: "for p in people:\n    if p[\"ok\"]:\n        print(p[\"name\"])",
      starter: "people = [{\"name\": \"Ada\", \"ok\": True}, {\"name\": \"Ben\", \"ok\": False}]\n",
      expected: "Ada\n",
      solution:
        "people = [{\"name\": \"Ada\", \"ok\": True}, {\"name\": \"Ben\", \"ok\": False}]\nfor p in people:\n    if p[\"ok\"]:\n        print(p[\"name\"])",
      hints: ["for p in people:", "if p[\"ok\"]:", "print(p[\"name\"])"],
    }),
  }),
  gig({
    id: "gig-merge-keys",
    title: "Patch a record",
    client: "Owen Park",
    company: "Drift Market",
    category: "api",
    lane: "records",
    unlockAfter: 20,
    difficulty: "Easy / Medium",
    pay: 760,
    xp: 130,
    skills: ["dict assign"],
    summary: "Change city from Oslo to Bergen.",
    brief: "Simulated profile patch. Print the new city.",
    challenge: ch({
      id: "gig-merge-keys",
      title: "Overwrite a key",
      concept: "dict assignment",
      prompt: "Set rec[\"city\"] = \"Bergen\". Print rec[\"city\"].",
      briefing: "Assigning an existing key replaces the value.",
      example: "rec[\"city\"] = \"Bergen\"\nprint(rec[\"city\"])",
      starter: "rec = {\"city\": \"Oslo\"}\n",
      expected: "Bergen\n",
      solution: "rec = {\"city\": \"Oslo\"}\nrec[\"city\"] = \"Bergen\"\nprint(rec[\"city\"])",
      hints: ["rec[\"city\"] = \"Bergen\"", "print(rec[\"city\"])", "Spelling and capitals matter"],
    }),
  }),

  gig({
    id: "gig-domain-email",
    title: "Email domain",
    client: "Jules Adeyemi",
    company: "Harbor Helpdesk",
    category: "data",
    lane: "methods",
    unlockAfter: 30,
    difficulty: "Medium",
    pay: 900,
    xp: 160,
    skills: [".split()"],
    summary: "Take the part after @.",
    brief: "Print lumen.dev from ada@lumen.dev. Practice parser, not a real inbox.",
    challenge: ch({
      id: "gig-domain-email",
      title: "split on @",
      concept: "str.split",
      prompt: "Split the email on \"@\" and print index 1.",
      briefing: "split returns a list. [0] is the name, [1] is the domain.",
      example: "print(email.split(\"@\")[1])",
      starter: "email = \"ada@lumen.dev\"\n",
      expected: "lumen.dev\n",
      solution: "email = \"ada@lumen.dev\"\nprint(email.split(\"@\")[1])",
      hints: ["email.split(\"@\")", "Take [1]", "print the domain"],
    }),
  }),
  gig({
    id: "gig-replace-word",
    title: "Redact a phrase",
    client: "Priya Shah",
    company: "Brightlane School",
    category: "automation",
    lane: "methods",
    unlockAfter: 30,
    difficulty: "Easy / Medium",
    pay: 860,
    xp: 150,
    skills: [".replace()"],
    summary: "Replace buy with view.",
    brief: "Print view now view. Content filter prototype.",
    challenge: ch({
      id: "gig-replace-word",
      title: "replace all matches",
      concept: "str.replace",
      prompt: "Replace \"buy\" with \"view\" in \"buy now buy\". Print the result.",
      briefing: "replace returns a new string. It does not change the original in place.",
      example: "print(msg.replace(\"buy\", \"view\"))",
      starter: "msg = \"buy now buy\"\n",
      expected: "view now view\n",
      solution: "msg = \"buy now buy\"\nprint(msg.replace(\"buy\", \"view\"))",
      hints: ["msg.replace(\"buy\", \"view\")", "print the new string", "Both buys change"],
    }),
  }),
  gig({
    id: "gig-count-letter",
    title: "Letter tally",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "data",
    lane: "methods",
    unlockAfter: 30,
    difficulty: "Easy",
    pay: 820,
    xp: 140,
    skills: [".count()"],
    summary: "How many a in banana?",
    brief: "Print 3.",
    challenge: ch({
      id: "gig-count-letter",
      title: "count a character",
      concept: "str.count",
      prompt: "Print how many times \"a\" appears in \"banana\".",
      briefing: "count returns a number.",
      example: "print(\"banana\".count(\"a\"))",
      starter: "word = \"banana\"\n",
      expected: "3\n",
      solution: "word = \"banana\"\nprint(word.count(\"a\"))",
      hints: ["word.count(\"a\")", "print it", "3"],
    }),
  }),
  gig({
    id: "gig-startswith-ok",
    title: "Path gate",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "automation",
    lane: "methods",
    unlockAfter: 30,
    difficulty: "Easy / Medium",
    pay: 880,
    xp: 155,
    skills: [".startswith()"],
    summary: "Allow paths under img/.",
    brief: "If the path starts with img/ print OK else NO.",
    challenge: ch({
      id: "gig-startswith-ok",
      title: "startswith check",
      concept: "str.startswith",
      prompt: "path is img/cat.png. Print OK if it startswith img/, else NO.",
      briefing: "startswith asks a yes/no about the beginning of a string.",
      example: "if path.startswith(\"img/\"):\n    print(\"OK\")",
      starter: "path = \"img/cat.png\"\n",
      expected: "OK\n",
      solution:
        "path = \"img/cat.png\"\nif path.startswith(\"img/\"):\n    print(\"OK\")\nelse:\n    print(\"NO\")",
      hints: ["path.startswith(\"img/\")", "print OK", "Include the slash"],
    }),
  }),
  gig({
    id: "gig-guess-hint",
    title: "Guessing-game hint",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "game",
    lane: "methods",
    unlockAfter: 30,
    difficulty: "Medium",
    pay: 940,
    xp: 165,
    skills: ["if / elif", "compare"],
    summary: "Secret 7, guess 4 — Too low.",
    brief: "Print Too low, Too high, or Correct. Mini-game logic.",
    challenge: ch({
      id: "gig-guess-hint",
      title: "Compare guess to secret",
      concept: "elif chain",
      prompt: "secret 7, guess 4. Print Too low / Too high / Correct.",
      briefing: "if guess < secret, elif guess > secret, else Correct.",
      example: "if guess < secret:\n    print(\"Too low\")\nelif guess > secret:\n    print(\"Too high\")\nelse:\n    print(\"Correct\")",
      starter: "secret = 7\nguess = 4\n",
      expected: "Too low\n",
      solution:
        "secret = 7\nguess = 4\nif guess < secret:\n    print(\"Too low\")\nelif guess > secret:\n    print(\"Too high\")\nelse:\n    print(\"Correct\")",
      hints: ["if guess < secret", "Print Too low", "Match the capital T and the space"],
    }),
  }),

  gig({
    id: "gig-zip-labels",
    title: "Score sheet",
    client: "Priya Shah",
    company: "Brightlane School",
    category: "report",
    lane: "studio",
    unlockAfter: 50,
    difficulty: "Medium",
    pay: 1100,
    xp: 190,
    skills: ["zip", "loops"],
    summary: "Pair names with points.",
    brief: "Print Ada 90 then Ben 70. Simulated class sheet.",
    challenge: ch({
      id: "gig-zip-labels",
      title: "zip two lists",
      concept: "zip",
      prompt: "zip names with pts. Print name, space, score on each line.",
      briefing: "zip walks two lists in lockstep. Unpack the pair.",
      example: "for n, p in zip(names, pts):\n    print(n + \" \" + str(p))",
      starter: "names = [\"Ada\", \"Ben\"]\npts = [90, 70]\n",
      expected: "Ada 90\nBen 70\n",
      solution: "names = [\"Ada\", \"Ben\"]\npts = [90, 70]\nfor n, p in zip(names, pts):\n    print(n + \" \" + str(p))",
      hints: ["for n, p in zip(names, pts):", "str(p) to join with the name", "Space between"],
    }),
  }),
  gig({
    id: "gig-fizz-tag",
    title: "Ticket tags",
    client: "Jules Adeyemi",
    company: "Harbor Helpdesk",
    category: "automation",
    lane: "studio",
    unlockAfter: 50,
    difficulty: "Medium",
    pay: 1150,
    xp: 200,
    skills: ["%", "elif"],
    summary: "15 should print FIZZBUZZ.",
    brief: "Priority tags: 15→FIZZBUZZ, 3→FIZZ, 5→BUZZ, else the number.",
    challenge: ch({
      id: "gig-fizz-tag",
      title: "FizzBuzz one shot",
      concept: "remainder chain",
      prompt: "n is 15. Print FIZZBUZZ / FIZZ / BUZZ / n using % 15, % 3, % 5.",
      briefing: "Check % 15 first so 15 is not tagged FIZZ only.",
      example: "if n % 15 == 0:\n    print(\"FIZZBUZZ\")",
      starter: "n = 15\n",
      expected: "FIZZBUZZ\n",
      solution:
        "n = 15\nif n % 15 == 0:\n    print(\"FIZZBUZZ\")\nelif n % 3 == 0:\n    print(\"FIZZ\")\nelif n % 5 == 0:\n    print(\"BUZZ\")\nelse:\n    print(n)",
      hints: ["Test % 15 first", "print FIZZBUZZ", "All caps, no space"],
    }),
  }),
  gig({
    id: "gig-unique-merge",
    title: "Merge unique IDs",
    client: "Chris Vale",
    company: "Harbor Logistics",
    category: "data",
    lane: "studio",
    unlockAfter: 50,
    difficulty: "Medium / Hard",
    pay: 1200,
    xp: 210,
    skills: ["in", "append", "concat"],
    summary: "Merge [1, 2] and [2, 3] without duplicates.",
    brief: "Print 1 then 2 then 3. First-seen order.",
    challenge: ch({
      id: "gig-unique-merge",
      title: "Keep first of each",
      concept: "membership",
      prompt: "Walk a + b. If x not in out, append it. Print each item of out.",
      briefing: "not in asks whether a value is already in the list.",
      example: "for x in a + b:\n    if x not in out:\n        out.append(x)",
      starter: "a = [1, 2]\nb = [2, 3]\nout = []\n",
      expected: "1\n2\n3\n",
      solution:
        "a = [1, 2]\nb = [2, 3]\nout = []\nfor x in a + b:\n    if x not in out:\n        out.append(x)\nfor x in out:\n    print(x)",
      hints: ["for x in a + b", "if x not in out: out.append(x)", "Then print each of out"],
    }),
  }),
  gig({
    id: "gig-clamp",
    title: "Volume clamp",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "utility",
    lane: "studio",
    unlockAfter: 50,
    difficulty: "Medium",
    pay: 1080,
    xp: 185,
    skills: ["if", "bounds"],
    summary: "Keep 140 inside 0..100.",
    brief: "If n > 100 set 100. If n < 0 set 0. Print n. Audio mixer prototype.",
    challenge: ch({
      id: "gig-clamp",
      title: "Clamp a number",
      concept: "min/max bounds",
      prompt: "n is 140. Clamp to 0..100 and print n.",
      briefing: "Two ifs, or min(100, max(0, n)).",
      example: "if n > 100:\n    n = 100\nif n < 0:\n    n = 0\nprint(n)",
      starter: "n = 140\n",
      expected: "100\n",
      solution: "n = 140\nif n > 100:\n    n = 100\nif n < 0:\n    n = 0\nprint(n)",
      hints: ["if n > 100: n = 100", "Then print n", "140 becomes 100"],
    }),
  }),
  gig({
    id: "gig-any-ready",
    title: "Ready check",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "api",
    lane: "studio",
    unlockAfter: 50,
    difficulty: "Medium",
    pay: 1120,
    xp: 190,
    skills: ["any()", "all()"],
    summary: "any flags True, all flags False.",
    brief: "flags = [False, True, False]. Print any(flags) then all(flags).",
    challenge: ch({
      id: "gig-any-ready",
      title: "any and all",
      concept: "bulk truth",
      prompt: "Print any(flags) on the first line and all(flags) on the second.",
      briefing: "any is True if at least one item is true. all needs every item true.",
      example: "print(any(flags))\nprint(all(flags))",
      starter: "flags = [False, True, False]\n",
      expected: "True\nFalse\n",
      solution: "flags = [False, True, False]\nprint(any(flags))\nprint(all(flags))",
      hints: ["print(any(flags))", "print(all(flags))", "True then False"],
    }),
  }),

  gig({
    id: "gig-freq-a",
    title: "Letter frequency",
    client: "Priya Shah",
    company: "Brightlane School",
    category: "data",
    lane: "craft",
    unlockAfter: 75,
    difficulty: "Medium / Hard",
    pay: 1400,
    xp: 240,
    skills: ["dicts", "counters"],
    summary: "Count each letter in ada.",
    brief: "Build a dict. Print the count for a, then d. Cipher lab — simulated.",
    challenge: ch({
      id: "gig-freq-a",
      title: "Frequency table",
      concept: "dict counters",
      prompt: "Count letters in \"ada\". Print freq[\"a\"] then freq[\"d\"].",
      briefing: "If the key is missing, start at 0, then add 1.",
      example: "for ch in word:\n    freq[ch] = freq.get(ch, 0) + 1",
      starter: "word = \"ada\"\nfreq = {}\n",
      expected: "2\n1\n",
      solution:
        "word = \"ada\"\nfreq = {}\nfor ch in word:\n    freq[ch] = freq.get(ch, 0) + 1\nprint(freq[\"a\"])\nprint(freq[\"d\"])",
      hints: ["freq.get(ch, 0) + 1", "Loop every character", "Print a then d"],
    }),
  }),
  gig({
    id: "gig-caesar-one",
    title: "Shift a letter",
    client: "Kenji Mori",
    company: "Pixel & Co",
    category: "game",
    lane: "craft",
    unlockAfter: 75,
    difficulty: "Hard",
    pay: 1500,
    xp: 260,
    skills: ["ord", "chr"],
    summary: "Move A one place to B.",
    brief: "Toy cipher. Print chr(ord(\"A\") + 1).",
    challenge: ch({
      id: "gig-caesar-one",
      title: "ord and chr",
      concept: "character codes",
      prompt: "Print the character after A using ord and chr.",
      briefing: "ord(\"A\") is 65. chr(66) is B.",
      example: "print(chr(ord(\"A\") + 1))",
      starter: "letter = \"A\"\n",
      expected: "B\n",
      solution: "letter = \"A\"\nprint(chr(ord(letter) + 1))",
      hints: ["ord(letter) + 1", "Wrap with chr(...)", "B"],
    }),
  }),
  gig({
    id: "gig-nested-pass",
    title: "Open tickets",
    client: "Jules Adeyemi",
    company: "Harbor Helpdesk",
    category: "report",
    lane: "craft",
    unlockAfter: 75,
    difficulty: "Medium / Hard",
    pay: 1450,
    xp: 250,
    skills: ["nested records"],
    summary: "Print ids of tickets with status open.",
    brief: "Simulated ticket bay. Print 1 then 3.",
    challenge: ch({
      id: "gig-nested-pass",
      title: "Filter nested dicts",
      concept: "nested loops of records",
      prompt: "Loop tickets. If t[\"status\"] == \"open\", print t[\"id\"].",
      briefing: "Each ticket is a dictionary inside a list.",
      example: "for t in tickets:\n    if t[\"status\"] == \"open\":\n        print(t[\"id\"])",
      starter:
        "tickets = [{\"id\": 1, \"status\": \"open\"}, {\"id\": 2, \"status\": \"done\"}, {\"id\": 3, \"status\": \"open\"}]\n",
      expected: "1\n3\n",
      solution:
        "tickets = [{\"id\": 1, \"status\": \"open\"}, {\"id\": 2, \"status\": \"done\"}, {\"id\": 3, \"status\": \"open\"}]\nfor t in tickets:\n    if t[\"status\"] == \"open\":\n        print(t[\"id\"])",
      hints: ["for t in tickets:", "if t[\"status\"] == \"open\"", "print(t[\"id\"])"],
    }),
  }),
  gig({
    id: "gig-histo",
    title: "Star chart",
    client: "Owen Park",
    company: "Drift Market",
    category: "report",
    lane: "craft",
    unlockAfter: 75,
    difficulty: "Medium / Hard",
    pay: 1380,
    xp: 240,
    skills: ["string * int", "loops"],
    summary: "Print *** then ** then *****.",
    brief: "Tiny histogram from counts [3, 2, 5]. Repeat \"*\" n times.",
    challenge: ch({
      id: "gig-histo",
      title: "Stars for counts",
      concept: "string repeat",
      prompt: "For each n in [3, 2, 5], print \"*\" * n.",
      briefing: "A string times a number repeats the string.",
      example: "for n in counts:\n    print(\"*\" * n)",
      starter: "counts = [3, 2, 5]\n",
      expected: "***\n**\n*****\n",
      solution: "counts = [3, 2, 5]\nfor n in counts:\n    print(\"*\" * n)",
      hints: ["for n in counts:", "print(\"*\" * n)", "Three lines"],
    }),
  }),
  gig({
    id: "gig-pipe-two",
    title: "Helper pipeline",
    client: "Rae Quinn",
    company: "Fieldkit Labs",
    category: "automation",
    lane: "craft",
    unlockAfter: 75,
    difficulty: "Hard",
    pay: 1600,
    xp: 280,
    skills: ["functions", "composition"],
    summary: "clean then tag a name.",
    brief: "clean strips and uppercases. tag adds ID:. Print ID:ADA for \"  ada  \".",
    challenge: ch({
      id: "gig-pipe-two",
      title: "One function calls another",
      concept: "composition",
      prompt: "Write clean(s) = s.strip().upper(). Write tag(s) = \"ID:\" + clean(s). Print tag(\"  ada  \").",
      briefing: "tag calls clean. The inner function finishes first.",
      example: "def clean(s):\n    return s.strip().upper()\ndef tag(s):\n    return \"ID:\" + clean(s)",
      starter: "def clean(s):\n    return s\n\ndef tag(s):\n    return s\n",
      expected: "ID:ADA\n",
      solution:
        "def clean(s):\n    return s.strip().upper()\n\ndef tag(s):\n    return \"ID:\" + clean(s)\nprint(tag(\"  ada  \"))",
      hints: ["clean: strip then upper", "tag: \"ID:\" + clean(s)", "print(tag(\"  ada  \"))"],
    }),
  }),
];

export function gigById(id: string): FreelanceJob | undefined {
  return GIGS.find((g) => g.id === id);
}

export function maxCompleted(completed: number[]): number {
  return completed.length ? Math.max(...completed) : 0;
}

export function isGigUnlocked(job: FreelanceJob, completed: number[]): boolean {
  return maxCompleted(completed) >= job.unlockAfter;
}

export function unlockedGigs(completed: number[]): FreelanceJob[] {
  return GIGS.filter((g) => isGigUnlocked(g, completed));
}

export function lockedGigs(completed: number[]): FreelanceJob[] {
  return GIGS.filter((g) => !isGigUnlocked(g, completed));
}

export function gigsNewlyUnlocked(prevMax: number, nextMax: number): FreelanceJob[] {
  return GIGS.filter((g) => g.unlockAfter > prevMax && g.unlockAfter <= nextMax);
}

export function laneById(id: GigLaneId): GigLane {
  return GIG_LANES.find((l) => l.id === id) ?? GIG_LANES[0];
}

export function gigsInLane(lane: GigLaneId): FreelanceJob[] {
  return GIGS.filter((g) => g.lane === lane);
}

export function categoryLabel(c: FreelanceCategory): string {
  switch (c) {
    case "bugfix":
      return "Bugfix";
    case "utility":
      return "Utility";
    case "game":
      return "Mini-game";
    case "data":
      return "Data";
    case "automation":
      return "Automation";
    case "api":
      return "API sim";
    case "report":
      return "Report";
  }
}

export function featuredGig(completed: number[], doneIds: Set<string>): FreelanceJob | null {
  const open = unlockedGigs(completed).filter((g) => !doneIds.has(g.id));
  if (!open.length) return null;
  return open[0];
}

export const SIM_DISCLAIMER =
  "Simulated clients, ratings, and pay. Practice only — not real employment.";
