import type { CareerId, ChapterId, Difficulty, LevelDef, Step } from "./types.ts";

function brief(title: string, body: string, example?: string): Step {
  return example ? { type: "brief", title, body, example } : { type: "brief", title, body };
}

function choice(
  concept: string,
  question: string,
  a: string,
  ae: string,
  b: string,
  be: string,
  c: string,
  ce: string,
  correct: "a" | "b" | "c",
): Step {
  return {
    type: "choice",
    concept,
    question,
    options: [
      { id: "a", label: a, correct: correct === "a", explain: ae },
      { id: "b", label: b, correct: correct === "b", explain: be },
      { id: "c", label: c, correct: correct === "c", explain: ce },
    ],
  };
}

function code(
  id: string,
  title: string,
  concept: string,
  prompt: string,
  briefing: string,
  example: string,
  starter: string,
  expected: string,
  solution: string,
  hints: string[],
): Step {
  return {
    type: "code",
    challenge: { id, title, concept, prompt, briefing, example, starter, expected, solution, hints },
  };
}

function lv(
  id: number,
  title: string,
  job: string,
  difficulty: Difficulty,
  description: string,
  objective: string,
  coins: number,
  xp: number,
  unlockRewardId: string,
  unlockReward: string,
  careerUnlock: CareerId,
  chapter: ChapterId,
  steps: Step[],
  extra?: { timeLimitSec?: number; championship?: boolean; finale?: boolean },
): LevelDef {
  return {
    id,
    title,
    job,
    difficulty,
    description,
    objective,
    rewardCoins: coins,
    rewardXp: xp,
    unlockRewardId,
    unlockReward,
    careerUnlock,
    chapter,
    ...extra,
    steps,
  };
}

export const LEVELS_PRO: LevelDef[] = [
  lv(
    51,
    "Zip Rail",
    "Virtuoso",
    "Medium",
    "zip walks two lists together: first with first, second with second.",
    "Pair names with scores and print each pair.",
    3000,
    1000,
    "zip-rail",
    "Zip Rail",
    "virtuoso",
    "patterns",
    [
      brief(
        "Two lists, one walk",
        "zip(names, scores) hands you a pair on each step. Unpack: for n, s in zip(names, scores):. It stops at the shorter list.",
        "for n, s in zip([\"Ada\", \"Lin\"], [90, 70]):\n    print(n)\n    print(s)",
      ),
      choice(
        "zip length",
        "zip([1, 2, 3], [\"a\", \"b\"]) makes how many pairs?",
        "3",
        "zip stops when the shortest list ends. The extra 3 is ignored.",
        "2",
        "Two pairs: (1, a) and (2, b). The leftover 3 is dropped.",
        "5",
        "zip does not concatenate. It pairs by position.",
        "b",
      ),
      code(
        "l51-zip",
        "Lockstep",
        "zip",
        "names is Ada, Lin. scores is 90, 70. For each pair, print the name then the score.",
        "Use zip and unpack two names in the for line.",
        "for n, s in zip(names, scores):",
        "names = [\"Ada\", \"Lin\"]\nscores = [90, 70]\n",
        "Ada\n90\nLin\n70\n",
        "names = [\"Ada\", \"Lin\"]\nscores = [90, 70]\nfor n, s in zip(names, scores):\n    print(n)\n    print(s)",
        ["for n, s in zip(names, scores):", "print(n) then print(s)", "Do not add extra text."],
      ),
    ],
  ),
  lv(
    52,
    "Truth Bulk",
    "Virtuoso",
    "Medium",
    "any(list) is True if at least one item is true. all(list) needs every item true.",
    "Print any and all for the given lists.",
    3100,
    1050,
    "truth-bulk",
    "Truth Bulk",
    "virtuoso",
    "patterns",
    [
      brief(
        "One question for the whole list",
        "0, \"\", [], None are false. any([0, 0, 1]) is True because 1 is true. all([1, 0, 3]) is False because 0 is false. all([]) is True — there is no liar.",
        "print(any([0, 1]))  # True\nprint(all([1, 2]))  # True",
      ),
      choice(
        "any vs all",
        "What does any([0, 0, 0]) print?",
        "True",
        "Every item is 0, which is false, so any is False.",
        "False",
        "No item is true, so any is False.",
        "0",
        "any always returns True or False, not a number.",
        "b",
      ),
      code(
        "l52-any",
        "Bulk truth",
        "any / all",
        "Print any([0, 0, 1]), then all([1, 2, 3]), then all([1, 0, 3]).",
        "Three prints. True, True, False.",
        "print(any([0, 0, 1]))",
        "",
        "True\nTrue\nFalse\n",
        "print(any([0, 0, 1]))\nprint(all([1, 2, 3]))\nprint(all([1, 0, 3]))",
        ["any([0, 0, 1])", "all([1, 2, 3])", "all([1, 0, 3]) is False because of 0"],
      ),
    ],
  ),
  lv(
    53,
    "Round Dial",
    "Virtuoso",
    "Medium",
    "round(n) nearest integer. float(\"2.5\") turns text into a decimal number.",
    "Round 3.7 and convert the string 2.5.",
    3200,
    1100,
    "round-dial",
    "Round Dial",
    "virtuoso",
    "patterns",
    [
      brief(
        "Nearby integer, numeric text",
        "round(3.7) is 4. round(3.2) is 3. float(\"2.5\") is the number 2.5 — not a string. int() would drop the decimal; float keeps it.",
        "print(round(3.7))\nprint(float(\"2.5\"))",
      ),
      choice(
        "float vs int",
        "What does int(\"3.0\") do in this course interpreter?",
        "Returns 3",
        "int() truncates a numeric string that Number() can read. \"3.0\" becomes 3.",
        "Crashes",
        "This teaching interpreter accepts numeric strings. Real CPython int(\"3.0\") does fail — here float is the safe conversion for decimals.",
        "Returns 3.0",
        "int() never keeps a decimal. float() would.",
        "a",
      ),
      code(
        "l53-round",
        "Nearby",
        "round / float",
        "Print round(3.7), then print float(\"2.5\").",
        "First line 4. Second line 2.5.",
        "print(round(3.7))",
        "",
        "4\n2.5\n",
        "print(round(3.7))\nprint(float(\"2.5\"))",
        ["round(3.7)", "float(\"2.5\")", "Two print calls."],
      ),
    ],
  ),
  lv(
    54,
    "Bool Gate",
    "Virtuoso",
    "Medium",
    "bool(x) names the truth of a value. Non-empty lists are True even if they hold 0.",
    "Print bool of empty string, \"ok\", empty list, and [0].",
    3300,
    1150,
    "bool-gate",
    "Bool Gate",
    "virtuoso",
    "patterns",
    [
      brief(
        "Name the truth",
        "bool(\"\") is False. bool(\"ok\") is True. bool([]) is False. bool([0]) is True — the list is not empty. The 0 inside does not make the list false.",
        "print(bool([0]))  # True",
      ),
      choice(
        "non-empty list",
        "Why is bool([0]) True?",
        "0 is true",
        "0 is false. The list is true because it has an item.",
        "The list has a length of 1",
        "A non-empty list is true, even if the item inside is 0 or False.",
        "Lists are always true",
        "Empty lists are false. bool([]) is False.",
        "b",
      ),
      code(
        "l54-bool",
        "Name it",
        "bool()",
        "Print bool(\"\"), bool(\"ok\"), bool([]), bool([0]) — each on its own line.",
        "False, True, False, True.",
        "print(bool(\"\"))",
        "",
        "False\nTrue\nFalse\nTrue\n",
        "print(bool(\"\"))\nprint(bool(\"ok\"))\nprint(bool([]))\nprint(bool([0]))",
        ["Four print(bool(...)) calls", "[0] is a non-empty list", "Empty string is False"],
      ),
    ],
  ),
  lv(
    55,
    "None Identity",
    "Artisan",
    "Medium",
    "is checks identity. Use x is None, not x == None, when you mean “no value”.",
    "Test a missing value with is and is not.",
    3400,
    1200,
    "none-is",
    "None Identity",
    "artisan",
    "patterns",
    [
      brief(
        "The value that means no value",
        "None is a singleton. x is None is True only when x really is None. 0 is not None. \"\" is not None. is not is the opposite.",
        "x = None\nprint(x is None)      # True\nprint(x is not None)  # False",
      ),
      choice(
        "is vs ==",
        "Which check is the Python style for “this is missing”?",
        "x == None",
        "It often works, but style (and this course) wants is, because None is one object.",
        "x is None",
        "Identity. There is only one None.",
        "x = None",
        "That assigns, it does not test.",
        "b",
      ),
      code(
        "l55-is",
        "Identity",
        "is None",
        "x is None. Print x is None, then x is not None, then (0 is None).",
        "True, False, False.",
        "print(x is None)",
        "x = None\n",
        "True\nFalse\nFalse\n",
        "x = None\nprint(x is None)\nprint(x is not None)\nprint(0 is None)",
        ["x is None", "x is not None", "0 is None is False"],
      ),
    ],
  ),
  lv(
    56,
    "Ternary Key",
    "Artisan",
    "Medium",
    "value_if_true if condition else value_if_false — a one-line choice that returns a value.",
    "Stamp even/odd with a ternary.",
    3500,
    1250,
    "ternary-key",
    "Ternary Key",
    "artisan",
    "patterns",
    [
      brief(
        "If that returns",
        "\"even\" if n % 2 == 0 else \"odd\" picks a string. It is an expression — you can print it or return it. The condition sits in the middle.",
        "print(\"yes\" if n > 0 else \"no\")",
      ),
      choice(
        "ternary order",
        "In a if cond else b, when is a used?",
        "When cond is false",
        "False takes the else branch — b.",
        "When cond is true",
        "The value before if is the True result.",
        "Always",
        "Only one side runs.",
        "b",
      ),
      code(
        "l56-tern",
        "One-line stamp",
        "ternary",
        "Print \"even\" if 8 is even else \"odd\". Then the same for 7.",
        "even then odd. Use n % 2 == 0 in the middle.",
        "print(\"even\" if n % 2 == 0 else \"odd\")",
        "",
        "even\nodd\n",
        "print(\"even\" if 8 % 2 == 0 else \"odd\")\nprint(\"even\" if 7 % 2 == 0 else \"odd\")",
        ["\"even\" if 8 % 2 == 0 else \"odd\"", "Second line uses 7", "Two prints"],
      ),
    ],
  ),
  lv(
    57,
    "Swap Hands",
    "Artisan",
    "Medium",
    "a, b = b, a swaps two boxes in one line. Python evaluates the right side first.",
    "Swap 3 and 9, then print both.",
    3600,
    1300,
    "swap-hands",
    "Swap Hands",
    "artisan",
    "patterns",
    [
      brief(
        "No third box",
        "In many languages you need t = a; a = b; b = t. Python lets you write a, b = b, a. The right side is packed, then unpacked into the left names.",
        "a = 3\nb = 9\na, b = b, a\nprint(a)  # 9",
      ),
      choice(
        "evaluation order",
        "After a, b = b, a, what happened to the original a?",
        "It is lost forever",
        "It moved into b. Nothing is lost.",
        "It is now in b",
        "Right side is (old b, old a). Then a gets old b, b gets old a.",
        "It stays in a",
        "That would not be a swap.",
        "b",
      ),
      code(
        "l57-swap",
        "Hands",
        "unpack assign",
        "a is 3, b is 9. Swap them with one assignment. Print a, then b.",
        "9 then 3.",
        "a, b = b, a",
        "a = 3\nb = 9\n",
        "9\n3\n",
        "a = 3\nb = 9\na, b = b, a\nprint(a)\nprint(b)",
        ["a, b = b, a", "print(a)", "print(b)"],
      ),
    ],
  ),
  lv(
    58,
    "Repeat Rack",
    "Artisan",
    "Medium",
    "A list times a number repeats the items. [0] * 4 is four zeros.",
    "Build a repeated list and a repeated word list.",
    3700,
    1350,
    "repeat-rack",
    "Repeat Rack",
    "artisan",
    "patterns",
    [
      brief(
        "Fill the rack",
        "[0] * 4 → [0, 0, 0, 0]. [\"go\"] * 3 → ['go', 'go', 'go']. This is a new list. Changing one slot later does not rewrite the multiplier.",
        "print([0] * 4)",
      ),
      choice(
        "repeat vs append",
        "What is [1, 2] * 2?",
        "[2, 4]",
        "That would be multiplying items. * on a list repeats the list.",
        "[1, 2, 1, 2]",
        "The whole list is laid down twice.",
        "[1, 2, 2]",
        "It does not append only the last item.",
        "b",
      ),
      code(
        "l58-rep",
        "Rack",
        "list * n",
        "Print [0] * 4, then print [\"go\"] * 3.",
        "[0, 0, 0, 0] then ['go', 'go', 'go'].",
        "print([0] * 4)",
        "",
        "[0, 0, 0, 0]\n['go', 'go', 'go']\n",
        "print([0] * 4)\nprint([\"go\"] * 3)",
        ["[0] * 4", "[\"go\"] * 3", "Two prints"],
      ),
    ],
  ),
  lv(
    59,
    "Reverse Walk",
    "Artisan",
    "Medium",
    "reversed(items) walks backwards. The original list stays in order.",
    "Print 3, 2, 1 from [1, 2, 3] without mutating it.",
    3800,
    1400,
    "reverse-walk",
    "Reverse Walk",
    "artisan",
    "patterns",
    [
      brief(
        "Backwards, copy",
        "list.reverse() flips the list in place and returns None. reversed(items) leaves items alone and lets you for-loop from the end. This course’s reversed() hands you a list.",
        "for n in reversed([1, 2, 3]):\n    print(n)",
      ),
      choice(
        "reverse vs reversed",
        "After xs = [1, 2]; xs.reverse(), what is xs?",
        "[1, 2]",
        "reverse() mutates. xs is now [2, 1].",
        "[2, 1]",
        "In-place flip.",
        "None",
        "reverse() returns None, but xs itself is the flipped list.",
        "b",
      ),
      code(
        "l59-rev",
        "Walk back",
        "reversed",
        "For each n in reversed([1, 2, 3]), print n.",
        "3 then 2 then 1.",
        "for n in reversed([1, 2, 3]):",
        "",
        "3\n2\n1\n",
        "for n in reversed([1, 2, 3]):\n    print(n)",
        ["for n in reversed([1, 2, 3]):", "print(n)", "Do not call .reverse()"],
      ),
    ],
  ),
  lv(
    60,
    "Fizz Seal",
    "Artisan",
    "Medium / Hard",
    "The classic remainder song. % 3 Fizz, % 5 Buzz, both FizzBuzz, else the number.",
    "Print FizzBuzz for 1 through 15.",
    4000,
    1500,
    "fizz-seal",
    "Fizz Seal",
    "artisan",
    "patterns",
    [
      brief(
        "Test the double first",
        "If you check % 3 before % 15, 15 would print Fizz and skip Buzz. Check n % 15 == 0 (or both) first, then 3, then 5, else the number. range(1, 16) is 1..15.",
        "if n % 15 == 0:\n    print(\"FizzBuzz\")",
      ),
      choice(
        "order",
        "Why check 15 before 3?",
        "15 is bigger",
        "Size is not the reason. 15 is divisible by 3, so the 3-branch would steal it.",
        "15 is also divisible by 3, so the Fizz branch would catch it first",
        "The more specific case must come first.",
        "15 is divisible by 5 only",
        "15 is divisible by both 3 and 5.",
        "b",
      ),
      code(
        "l60-fizz",
        "The song",
        "FizzBuzz",
        "For n from 1 to 15 inclusive: print FizzBuzz if divisible by 15, Fizz by 3, Buzz by 5, else n.",
        "Fifteen lines. 15 must be FizzBuzz, not Fizz.",
        "for n in range(1, 16):",
        "",
        "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n",
        "for n in range(1, 16):\n    if n % 15 == 0:\n        print(\"FizzBuzz\")\n    elif n % 3 == 0:\n        print(\"Fizz\")\n    elif n % 5 == 0:\n        print(\"Buzz\")\n    else:\n        print(n)",
        ["range(1, 16)", "if n % 15 == 0 first", "elif % 3, elif % 5, else n"],
      ),
    ],
  ),
  lv(
    61,
    "Clamp Band",
    "Artisan",
    "Medium",
    "A clamp keeps a number inside [lo, hi]. Below lo → lo. Above hi → hi.",
    "Write clamp and print three cases.",
    4100,
    1550,
    "clamp-band",
    "Clamp Band",
    "artisan",
    "patterns",
    [
      brief(
        "Stay in the band",
        "clamp(-2, 0, 10) is 0. clamp(4, 0, 10) is 4. clamp(99, 0, 10) is 10. Two ifs, or a nested min/max. Write the ifs so you see the rule.",
        "if n < lo:\n    return lo",
      ),
      choice(
        "inclusive",
        "clamp(0, 0, 10) should return?",
        "lo - 1",
        "0 is already on the edge, and edges are allowed.",
        "0",
        "The band includes both ends.",
        "10",
        "That would be the high end. 0 is the low end.",
        "b",
      ),
      code(
        "l61-clamp",
        "Band",
        "clamp",
        "Write clamp(n, lo, hi). Print clamp(-2, 0, 10), clamp(4, 0, 10), clamp(99, 0, 10).",
        "0, 4, 10.",
        "def clamp(n, lo, hi):",
        "def clamp(n, lo, hi):\n    return n\n",
        "0\n4\n10\n",
        "def clamp(n, lo, hi):\n    if n < lo:\n        return lo\n    if n > hi:\n        return hi\n    return n\nprint(clamp(-2, 0, 10))\nprint(clamp(4, 0, 10))\nprint(clamp(99, 0, 10))",
        ["if n < lo: return lo", "if n > hi: return hi", "Print three calls"],
      ),
    ],
  ),
  lv(
    62,
    "Mirror Test",
    "Artisan",
    "Medium",
    "A palindrome equals its reverse. s == s[::-1].",
    "Write pal(s) and test level vs python.",
    4200,
    1600,
    "mirror-test",
    "Mirror Test",
    "artisan",
    "patterns",
    [
      brief(
        "Same forwards and back",
        "\"level\" reversed is \"level\". \"python\" reversed is \"nohtyp\". Return the comparison — True or False — do not print inside the function.",
        "return s == s[::-1]",
      ),
      choice(
        "slice reverse",
        "What does \"ab\"[::-1] equal?",
        "\"ab\"",
        "Step -1 flips it to ba.",
        "\"ba\"",
        "[::-1] walks the string backwards.",
        "\"\"",
        "A missing start/end still covers the whole string.",
        "b",
      ),
      code(
        "l62-pal",
        "Mirror",
        "palindrome",
        "Write pal(s) that returns True when s equals its reverse. Print pal(\"level\") then pal(\"python\").",
        "True then False.",
        "def pal(s):\n    return s == s[::-1]",
        "def pal(s):\n    return False\n",
        "True\nFalse\n",
        "def pal(s):\n    return s == s[::-1]\nprint(pal(\"level\"))\nprint(pal(\"python\"))",
        ["s == s[::-1]", "print(pal(\"level\"))", "print(pal(\"python\"))"],
      ),
    ],
  ),
  lv(
    63,
    "Fact Forge",
    "Titan",
    "Medium / Hard",
    "Factorial n! is 1*2*...*n. An accumulator starts at 1 and multiplies.",
    "Write fact and print fact(5) and fact(1).",
    4300,
    1650,
    "fact-forge",
    "Fact Forge",
    "titan",
    "craft",
    [
      brief(
        "Multiply down the range",
        "Start p = 1. for i in range(1, n + 1): p *= i. fact(5) is 120. fact(1) is 1. fact(0) would also be 1 — the loop never runs.",
        "p = 1\nfor i in range(1, n + 1):\n    p *= i",
      ),
      choice(
        "start at 1",
        "Why start the product at 1, not 0?",
        "Style",
        "0 times anything stays 0. The answer would always be 0.",
        "0 * k is always 0, so the result would be stuck at 0",
        "1 is the identity for multiplication.",
        "range starts at 1",
        "That is a separate reason. The accumulator still needs 1.",
        "b",
      ),
      code(
        "l63-fact",
        "Forge",
        "factorial",
        "Write fact(n) that returns n!. Print fact(5) then fact(1).",
        "120 then 1.",
        "def fact(n):\n    p = 1\n    for i in range(1, n + 1):\n        p *= i\n    return p",
        "def fact(n):\n    return n\n",
        "120\n1\n",
        "def fact(n):\n    p = 1\n    for i in range(1, n + 1):\n        p *= i\n    return p\nprint(fact(5))\nprint(fact(1))",
        ["p = 1", "for i in range(1, n + 1): p *= i", "Print both calls"],
      ),
    ],
  ),
  lv(
    64,
    "Fib Spiral",
    "Titan",
    "Hard",
    "Fibonacci: 0, 1, 1, 2, 3, 5, 8, 13. Each term is the two before it, added. Swap walks it.",
    "Write fib(n) as the nth term (fib(0)=0). Print fib(6) and fib(7).",
    4400,
    1700,
    "fib-spiral",
    "Fib Spiral",
    "titan",
    "craft",
    [
      brief(
        "Two hands walking",
        "a, b = 0, 1. Repeat n times: a, b = b, a + b. After n steps, a is fib(n). fib(6) is 8. fib(7) is 13.",
        "a, b = 0, 1\nfor i in range(n):\n    a, b = b, a + b\nreturn a",
      ),
      choice(
        "fib 0",
        "What is fib(0)?",
        "1",
        "The sequence starts at 0.",
        "0",
        "Zeroth term is 0. First is 1.",
        "2",
        "That is later in the sequence.",
        "b",
      ),
      code(
        "l64-fib",
        "Spiral",
        "fibonacci",
        "Write fib(n) where fib(0) is 0 and fib(1) is 1. Print fib(6) then fib(7).",
        "8 then 13.",
        "a, b = b, a + b",
        "def fib(n):\n    return n\n",
        "8\n13\n",
        "def fib(n):\n    a, b = 0, 1\n    for i in range(n):\n        a, b = b, a + b\n    return a\nprint(fib(6))\nprint(fib(7))",
        ["a, b = 0, 1", "a, b = b, a + b  n times", "return a"],
      ),
    ],
  ),
  lv(
    65,
    "Digit Well",
    "Titan",
    "Medium / Hard",
    "% 10 peels the last digit. // 10 drops it. Loop until the number is 0.",
    "Sum the digits of 409.",
    4500,
    1750,
    "digit-well",
    "Digit Well",
    "titan",
    "craft",
    [
      brief(
        "Peel from the right",
        "409 % 10 is 9. 409 // 10 is 40. 40 % 10 is 0. 40 // 10 is 4. 4 % 10 is 4. Sum 9+0+4 = 13.",
        "while n > 0:\n    s += n % 10\n    n = n // 10",
      ),
      choice(
        "peel",
        "What is 27 % 10?",
        "2",
        "2 is 27 // 10, the leftover tens.",
        "7",
        "Remainder when dividing by 10 is the last digit.",
        "0",
        "27 is not a multiple of 10.",
        "b",
      ),
      code(
        "l65-digits",
        "Well",
        "digit sum",
        "Write digits(n) that returns the sum of decimal digits. Print digits(409).",
        "13.",
        "s += n % 10",
        "def digits(n):\n    return n\n",
        "13\n",
        "def digits(n):\n    s = 0\n    while n > 0:\n        s += n % 10\n        n = n // 10\n    return s\nprint(digits(409))",
        ["while n > 0:", "s += n % 10", "n = n // 10"],
      ),
    ],
  ),
  lv(
    66,
    "Vowel Net",
    "Titan",
    "Medium",
    "Count letters that sit in \"aeiou\". Membership does the test.",
    "Count vowels in jarvis.",
    4600,
    1800,
    "vowel-net",
    "Vowel Net",
    "titan",
    "craft",
    [
      brief(
        "A tiny membership net",
        "for ch in s: if ch in \"aeiou\": c += 1. \"jarvis\" has a and i — 2. This version is case-sensitive; lower first if you need both cases.",
        "if ch in \"aeiou\":\n    c += 1",
      ),
      choice(
        "membership",
        "Does \"y\" count as a vowel in this mission?",
        "Yes",
        "The net is aeiou only.",
        "No — the string is aeiou",
        "Keep the rule small and exact.",
        "Only at the end",
        "Position does not matter.",
        "b",
      ),
      code(
        "l66-vow",
        "Net",
        "vowel count",
        "Write vowels(s) that counts a, e, i, o, u. Print vowels(\"jarvis\").",
        "2.",
        "if ch in \"aeiou\":",
        "def vowels(s):\n    return 0\n",
        "2\n",
        "def vowels(s):\n    c = 0\n    for ch in s:\n        if ch in \"aeiou\":\n            c += 1\n    return c\nprint(vowels(\"jarvis\"))",
        ["for ch in s:", "if ch in \"aeiou\":", "c += 1"],
      ),
    ],
  ),
  lv(
    67,
    "Search Pin",
    "Titan",
    "Medium / Hard",
    "Linear search: walk until you find the target, return the index. Miss → -1.",
    "Find Lin and miss Mo in a three-name list.",
    4700,
    1850,
    "search-pin",
    "Search Pin",
    "titan",
    "craft",
    [
      brief(
        "Walk with a counter",
        "i = 0. for x in items: if x == target: return i. Then i += 1. After the loop, return -1. First match wins.",
        "for i, x in enumerate(items):\n    if x == target:\n        return i\nreturn -1",
      ),
      choice(
        "miss",
        "Why return -1 when missing?",
        "Indexes start at -1",
        "Indexes start at 0. -1 is a signal, not a position you would print as found.",
        "It cannot be a real index in a normal list",
        "Callers can test found < 0.",
        "Python requires it",
        "It is a convention, like str.find.",
        "b",
      ),
      code(
        "l67-find",
        "Pin",
        "linear search",
        "Write find(items, target) returning the first index or -1. Print find([\"Ada\", \"Lin\", \"Kai\"], \"Lin\") then find(..., \"Mo\").",
        "1 then -1.",
        "return -1",
        "def find(items, target):\n    return 0\n",
        "1\n-1\n",
        "def find(items, target):\n    i = 0\n    for x in items:\n        if x == target:\n            return i\n        i += 1\n    return -1\nprint(find([\"Ada\", \"Lin\", \"Kai\"], \"Lin\"))\nprint(find([\"Ada\", \"Lin\", \"Kai\"], \"Mo\"))",
        ["Walk with i", "return i when equal", "return -1 after the loop"],
      ),
    ],
  ),
  lv(
    68,
    "Unique Press",
    "Titan",
    "Medium / Hard",
    "Keep the first of each value. Drop later repeats. Order stays.",
    "Press [1, 2, 2, 3, 1, 4] into unique items.",
    4800,
    1900,
    "unique-press",
    "Unique Press",
    "titan",
    "craft",
    [
      brief(
        "Seen before?",
        "out starts empty. for x in items: if x not in out: out.append(x). First 1 stays. Second 1 is skipped. This is O(n²) and fine for mission-size lists.",
        "if x not in out:\n    out.append(x)",
      ),
      choice(
        "order",
        "Unique of [2, 1, 2] is?",
        "[1, 2]",
        "That would sort. We keep first-seen order: 2 then 1.",
        "[2, 1]",
        "First 2, then 1. The later 2 is dropped.",
        "[2, 1, 2]",
        "That is not unique.",
        "b",
      ),
      code(
        "l68-uniq",
        "Press",
        "dedup",
        "From items [1, 2, 2, 3, 1, 4], build a new list with first-seen uniques and print it.",
        "[1, 2, 3, 4]",
        "if x not in out:\n    out.append(x)",
        "items = [1, 2, 2, 3, 1, 4]\n",
        "[1, 2, 3, 4]\n",
        "items = [1, 2, 2, 3, 1, 4]\nout = []\nfor x in items:\n    if x not in out:\n        out.append(x)\nprint(out)",
        ["out = []", "if x not in out", "print(out)"],
      ),
    ],
  ),
  lv(
    69,
    "Flat Grid",
    "Titan",
    "Medium",
    "A list of lists becomes one list. Nested for. append each inner item.",
    "Flatten [[1, 2], [3, 4], [5]].",
    4900,
    1950,
    "flat-grid",
    "Flat Grid",
    "titan",
    "craft",
    [
      brief(
        "Rows then cells",
        "for row in grid: for x in row: out.append(x). Uneven rows are fine — the inner loop just runs fewer times.",
        "for row in grid:\n    for x in row:\n        out.append(x)",
      ),
      choice(
        "append row",
        "What if you append(row) instead of each x?",
        "Same result",
        "You would nest lists inside out.",
        "out would be a list of lists still",
        "Flatten means items, not rows.",
        "Error",
        "append accepts a list. It just would not flatten.",
        "b",
      ),
      code(
        "l69-flat",
        "Flatten",
        "nested lists",
        "Flatten grid = [[1, 2], [3, 4], [5]] into one list and print it.",
        "[1, 2, 3, 4, 5]",
        "for row in grid:\n    for x in row:",
        "grid = [[1, 2], [3, 4], [5]]\n",
        "[1, 2, 3, 4, 5]\n",
        "grid = [[1, 2], [3, 4], [5]]\nout = []\nfor row in grid:\n    for x in row:\n        out.append(x)\nprint(out)",
        ["out = []", "nested for", "out.append(x)"],
      ),
    ],
  ),
  lv(
    70,
    "Min Hand",
    "Titan",
    "Medium",
    "Find the smallest with a loop. No min(). Start from the first item.",
    "Smallest of [9, 2, 7, 2, 5].",
    5000,
    2000,
    "min-hand",
    "Min Hand",
    "titan",
    "craft",
    [
      brief(
        "Champion challenger",
        "m = nums[0]. for n in nums: if n < m: m = n. Ties keep the old champion. Empty lists are out of scope — you need a first item.",
        "m = nums[0]\nfor n in nums:\n    if n < m:\n        m = n",
      ),
      choice(
        "start",
        "Why not start m at 0?",
        "0 is always smallest",
        "If every number is positive, 0 would win even though it is not in the list.",
        "0 might not be in the list, and might be smaller than every real item",
        "Start from an actual item.",
        "Indexes start at 0",
        "Different 0.",
        "b",
      ),
      code(
        "l70-min",
        "Hand",
        "min loop",
        "Write smallest(nums) without calling min. Print smallest([9, 2, 7, 2, 5]).",
        "2.",
        "if n < m:\n    m = n",
        "def smallest(nums):\n    return nums[0]\n",
        "2\n",
        "def smallest(nums):\n    m = nums[0]\n    for n in nums:\n        if n < m:\n            m = n\n    return m\nprint(smallest([9, 2, 7, 2, 5]))",
        ["m = nums[0]", "if n < m: m = n", "Do not use min()"],
      ),
    ],
  ),
  lv(
    71,
    "Run Total",
    "Titan",
    "Medium",
    "Print the sum after every add. A running total, not just the final number.",
    "Running total of [5, 10, 3].",
    5100,
    2050,
    "run-total",
    "Run Total",
    "titan",
    "craft",
    [
      brief(
        "After every step",
        "total = 0. for n in nums: total += n; print(total). For [5, 10, 3] you should see 5, then 15, then 18 — three lines, not one.",
        "total += n\nprint(total)",
      ),
      choice(
        "print place",
        "If you print only after the loop, what do you see?",
        "The running total",
        "You would only see the last sum.",
        "Only the final sum",
        "Print belongs inside the loop.",
        "Nothing",
        "You would still see one number if you print after.",
        "b",
      ),
      code(
        "l71-run",
        "Running",
        "accumulator print",
        "Starting at 0, add each of [5, 10, 3] and print the total after each add.",
        "5, 15, 18.",
        "total += n\nprint(total)",
        "nums = [5, 10, 3]\n",
        "5\n15\n18\n",
        "nums = [5, 10, 3]\ntotal = 0\nfor n in nums:\n    total += n\n    print(total)",
        ["total = 0", "total += n", "print inside the loop"],
      ),
    ],
  ),
  lv(
    72,
    "Prime Gate",
    "Titan",
    "Hard",
    "A prime is greater than 1 and has no divisor from 2 through sqrt(n).",
    "Test 7, 9, and 2.",
    5200,
    2100,
    "prime-gate",
    "Prime Gate",
    "titan",
    "craft",
    [
      brief(
        "Trial division",
        "n < 2 → False. i from 2 while i * i <= n: if n % i == 0: return False; i += 1. Then True. 2 is prime. 9 fails at i = 3.",
        "while i * i <= n:\n    if n % i == 0:\n        return False\n    i += 1",
      ),
      choice(
        "two",
        "Is 2 prime?",
        "No, it is even",
        "2 is the even prime. The loop i*i <= 2 never finds a divisor.",
        "Yes",
        "Only divisible by 1 and 2.",
        "Only odd numbers are prime",
        "2 is the exception that proves the rule about other evens.",
        "b",
      ),
      code(
        "l72-prime",
        "Gate",
        "prime",
        "Write prime(n) returning True/False. Print prime(7), prime(9), prime(2).",
        "True, False, True.",
        "while i * i <= n:",
        "def prime(n):\n    return True\n",
        "True\nFalse\nTrue\n",
        "def prime(n):\n    if n < 2:\n        return False\n    i = 2\n    while i * i <= n:\n        if n % i == 0:\n            return False\n        i += 1\n    return True\nprint(prime(7))\nprint(prime(9))\nprint(prime(2))",
        ["n < 2 → False", "test i from 2 while i * i <= n", "Print three calls"],
      ),
    ],
  ),
  lv(
    73,
    "GCD Lock",
    "Titan",
    "Hard",
    "Euclid: while b is not 0, a, b = b, a % b. Then a is the greatest common divisor.",
    "gcd(48, 18) and gcd(7, 3).",
    5300,
    2150,
    "gcd-lock",
    "GCD Lock",
    "titan",
    "craft",
    [
      brief(
        "Remainders shrink",
        "48, 18 → 18, 12 → 12, 6 → 6, 0. Stop. Answer 6. gcd(7, 3) is 1 — they share no larger factor. Swap with a, b = b, a % b.",
        "while b != 0:\n    a, b = b, a % b\nreturn a",
      ),
      choice(
        "stop",
        "When the remainder is 0, why is a the GCD?",
        "a is always 1",
        "gcd can be larger than 1. 6 in the 48, 18 example.",
        "b now divides a exactly, and Euclid proved that remainder chain shares the GCD",
        "The last non-zero remainder is the GCD.",
        "You guessed",
        "It is a theorem, not a guess — but you only need the loop here.",
        "b",
      ),
      code(
        "l73-gcd",
        "Lock",
        "gcd",
        "Write gcd(a, b) with Euclid’s remainder loop. Print gcd(48, 18) then gcd(7, 3).",
        "6 then 1.",
        "a, b = b, a % b",
        "def gcd(a, b):\n    return a\n",
        "6\n1\n",
        "def gcd(a, b):\n    while b != 0:\n        a, b = b, a % b\n    return a\nprint(gcd(48, 18))\nprint(gcd(7, 3))",
        ["while b != 0:", "a, b = b, a % b", "return a"],
      ),
    ],
  ),
  lv(
    74,
    "Leap Dial",
    "Titan",
    "Medium / Hard",
    "Leap year: divisible by 400, or by 4 but not by 100. 2000 yes, 1900 no, 2024 yes.",
    "Write leap(y) for those three years.",
    5400,
    2200,
    "leap-dial",
    "Leap Dial",
    "titan",
    "craft",
    [
      brief(
        "Calendar remainders",
        "if y % 400 == 0: True. if y % 100 == 0: False. return y % 4 == 0. Order matters: 2000 is a 400-year, 1900 is a century that is not.",
        "if y % 400 == 0:\n    return True\nif y % 100 == 0:\n    return False",
      ),
      choice(
        "1900",
        "Why is 1900 not a leap year?",
        "It is odd",
        "1900 is even. The century rule drops it.",
        "It is divisible by 100 but not by 400",
        "Centuries need 400.",
        "2024 is the only leap year",
        "Many years leap. 2000 does.",
        "b",
      ),
      code(
        "l74-leap",
        "Dial",
        "leap year",
        "Write leap(y). Print leap(2000), leap(1900), leap(2024).",
        "True, False, True.",
        "if y % 400 == 0:\n    return True",
        "def leap(y):\n    return y % 4 == 0\n",
        "True\nFalse\nTrue\n",
        "def leap(y):\n    if y % 400 == 0:\n        return True\n    if y % 100 == 0:\n        return False\n    return y % 4 == 0\nprint(leap(2000))\nprint(leap(1900))\nprint(leap(2024))",
        ["400 first", "then 100 → False", "else % 4 == 0"],
      ),
    ],
  ),
  lv(
    75,
    "Sovereign Championship",
    "Sovereign",
    "Expert",
    "Craft championship. Stamp, flatten-unique, digit sum — under the clock.",
    "Clear every stage. Claim the Sovereign Seal.",
    14000,
    4500,
    "sovereign-seal",
    "Sovereign Seal",
    "sovereign",
    "craft",
    [
      brief(
        "Three tools, one clock",
        "Stage 1: remainder stamp. Stage 2: flatten then unique. Stage 3: digit sum. Same laws: colon, indent, return.",
        "def stamp(n):\n    if n % 3 == 0:\n        return \"Fizz\"\n    return str(n)",
      ),
      code(
        "l75-stamp",
        "Stage 1 — Stamp",
        "remainder stamp",
        "Write stamp(n): Fizz if n % 3 == 0 else the number as text. Print stamp(3), stamp(5), stamp(6).",
        "Fizz, 5, Fizz.",
        "return str(n)",
        "def stamp(n):\n    return n\n",
        "Fizz\n5\nFizz\n",
        "def stamp(n):\n    if n % 3 == 0:\n        return \"Fizz\"\n    return str(n)\nprint(stamp(3))\nprint(stamp(5))\nprint(stamp(6))",
        ["if n % 3 == 0: return \"Fizz\"", "return str(n)", "Print three calls"],
      ),
      code(
        "l75-flat",
        "Stage 2 — Flatten unique",
        "flatten + unique",
        "Flatten [[1, 1], [2, 1], [3]] then keep first-seen uniques. Print the result.",
        "[1, 2, 3]",
        "if x not in out:\n    out.append(x)",
        "grid = [[1, 1], [2, 1], [3]]\n",
        "[1, 2, 3]\n",
        "grid = [[1, 1], [2, 1], [3]]\nout = []\nfor row in grid:\n    for x in row:\n        if x not in out:\n            out.append(x)\nprint(out)",
        ["nested for", "if x not in out", "print(out)"],
      ),
      code(
        "l75-digits",
        "Stage 3 — Digit sum",
        "digit sum",
        "Write digits(n) summing decimal digits. Print digits(1234).",
        "10.",
        "s += n % 10",
        "def digits(n):\n    return n\n",
        "10\n",
        "def digits(n):\n    s = 0\n    while n > 0:\n        s += n % 10\n        n = n // 10\n    return s\nprint(digits(1234))",
        ["while n > 0", "% 10 and // 10", "print(digits(1234))"],
      ),
    ],
    { timeLimitSec: 180, championship: true },
  ),
  lv(
    76,
    "Collatz Path",
    "Sovereign",
    "Hard",
    "Even → n//2. Odd → 3n+1. Count steps until 1. The hailstone path.",
    "How many steps from 6 to 1?",
    5500,
    2250,
    "collatz-path",
    "Collatz Path",
    "sovereign",
    "craft",
    [
      brief(
        "Hailstones",
        "6 → 3 → 10 → 5 → 16 → 8 → 4 → 2 → 1. That is 8 steps. Count the arrows, not the starting 6. Stop when n == 1. Do not count a step at 1.",
        "while n != 1:\n    if n % 2 == 0:\n        n = n // 2\n    else:\n        n = 3 * n + 1\n    c += 1",
      ),
      choice(
        "count",
        "From 2 to 1, how many steps?",
        "2",
        "2 is even → 1. One step.",
        "1",
        "A single halving.",
        "0",
        "You start at 2, not 1.",
        "b",
      ),
      code(
        "l76-col",
        "Path",
        "Collatz",
        "Write steps(n) counting Collatz steps to 1. Print steps(6).",
        "8.",
        "n = n // 2",
        "def steps(n):\n    return n\n",
        "8\n",
        "def steps(n):\n    c = 0\n    while n != 1:\n        if n % 2 == 0:\n            n = n // 2\n        else:\n            n = 3 * n + 1\n        c += 1\n    return c\nprint(steps(6))",
        ["while n != 1:", "even: n // 2  odd: 3*n+1", "c += 1 each round"],
      ),
    ],
  ),
  lv(
    77,
    "Power Loop",
    "Sovereign",
    "Medium / Hard",
    "Raise a base without **. Multiply in a counted loop.",
    "2 to the 8th is 256.",
    5600,
    2300,
    "power-loop",
    "Power Loop",
    "sovereign",
    "craft",
    [
      brief(
        "Multiply e times",
        "p = 1. Repeat e times: p *= b. power(2, 8) is 256. power(anything, 0) is 1 because the loop does not run.",
        "p = 1\nfor i in range(e):\n    p *= b",
      ),
      choice(
        "zero exp",
        "power(5, 0) should be?",
        "0",
        "The empty product is 1.",
        "1",
        "No multiplications. Identity 1.",
        "5",
        "That would be exponent 1.",
        "b",
      ),
      code(
        "l77-pow",
        "Loop power",
        "power by loop",
        "Write power(b, e) without **. Print power(2, 8).",
        "256.",
        "p *= b",
        "def power(b, e):\n    return b\n",
        "256\n",
        "def power(b, e):\n    p = 1\n    for i in range(e):\n        p *= b\n    return p\nprint(power(2, 8))",
        ["p = 1", "for i in range(e): p *= b", "Do not use **"],
      ),
    ],
  ),
  lv(
    78,
    "Odd Bin",
    "Sovereign",
    "Medium",
    "Build a new list of odds. Do not mutate the original.",
    "Odds from [4, 7, 2, 9, 8].",
    5700,
    2350,
    "odd-bin",
    "Odd Bin",
    "sovereign",
    "craft",
    [
      brief(
        "Filter into a new box",
        "odds = []. for n in nums: if n % 2 != 0: odds.append(n). The original nums stays [4, 7, 2, 9, 8].",
        "if n % 2 != 0:\n    odds.append(n)",
      ),
      choice(
        "new list",
        "Why not nums.remove odds in place?",
        "remove while looping skips items",
        "Mutating a list you are walking is a classic bug. Build a new list.",
        "remove is illegal",
        "It exists — it is just the wrong tool here.",
        "Odds cannot be removed",
        "They can. Prefer a fresh list.",
        "a",
      ),
      code(
        "l78-odd",
        "Bin",
        "filter odds",
        "From nums = [4, 7, 2, 9, 8], print a new list of the odd numbers in order.",
        "[7, 9]",
        "if n % 2 != 0:",
        "nums = [4, 7, 2, 9, 8]\n",
        "[7, 9]\n",
        "nums = [4, 7, 2, 9, 8]\nodds = []\nfor n in nums:\n    if n % 2 != 0:\n        odds.append(n)\nprint(odds)",
        ["odds = []", "n % 2 != 0", "print(odds)"],
      ),
    ],
  ),
  lv(
    79,
    "Word Span",
    "Sovereign",
    "Easy / Medium",
    "len of every word. A loop over a list of strings.",
    "Print lengths of code, a, python.",
    5800,
    2400,
    "word-span",
    "Word Span",
    "sovereign",
    "craft",
    [
      brief(
        "Measure each token",
        "for w in words: print(len(w)). \"code\" is 4, \"a\" is 1, \"python\" is 6. Do not print the words themselves.",
        "print(len(w))",
      ),
      choice(
        "len string",
        "len(\"a\") is?",
        "0",
        "One character.",
        "1",
        "A single letter has length 1.",
        "97",
        "That would be ord, not len.",
        "b",
      ),
      code(
        "l79-len",
        "Span",
        "len words",
        "For each word in [\"code\", \"a\", \"python\"], print its length.",
        "4, 1, 6.",
        "print(len(w))",
        "words = [\"code\", \"a\", \"python\"]\n",
        "4\n1\n6\n",
        "words = [\"code\", \"a\", \"python\"]\nfor w in words:\n    print(len(w))",
        ["for w in words:", "print(len(w))", "Three lines"],
      ),
    ],
  ),
  lv(
    80,
    "Title Press",
    "Sovereign",
    "Medium",
    "Chain methods: strip then title. Spaces off, words capitalized.",
    "Clean \"  hello world  \".",
    5900,
    2450,
    "title-press",
    "Title Press",
    "sovereign",
    "craft",
    [
      brief(
        "Two methods, one expression",
        "raw.strip().title() first trims, then capitalizes each word. Order matters: title() would keep the spaces, strip after still works, but the taught press is strip then title.",
        "print(raw.strip().title())",
      ),
      choice(
        "order",
        "What does \"  hi\".title() start with?",
        "H immediately",
        "title does not strip. It would start with spaces, then Hi.",
        "spaces, then Hi",
        "Strip first if you want Hi at the left edge.",
        "error",
        "title accepts leading spaces.",
        "b",
      ),
      code(
        "l80-title",
        "Press",
        "strip + title",
        "raw is \"  hello world  \". Print raw.strip().title().",
        "Hello World",
        "print(raw.strip().title())",
        "raw = \"  hello world  \"\n",
        "Hello World\n",
        "raw = \"  hello world  \"\nprint(raw.strip().title())",
        ["strip() first", ".title()", "One print"],
      ),
    ],
  ),
  lv(
    81,
    "Ord Key",
    "Sentinel",
    "Medium",
    "ord(\"A\") is 65. chr(66) is B. Letters are numbers underneath.",
    "Print ord of A and chr of 66.",
    6000,
    2500,
    "ord-key",
    "Ord Key",
    "sentinel",
    "legend",
    [
      brief(
        "The number of a letter",
        "Unicode code points. For basic English, they match ASCII. ord needs a string of length 1. chr maps the other way. \"A\" + 1 is a TypeError — use ord/chr to shift.",
        "print(ord(\"A\"))\nprint(chr(66))",
      ),
      choice(
        "shift",
        "How do you get the letter after ch?",
        "ch + 1",
        "str + int is a TypeError. Convert with ord, add, chr.",
        "chr(ord(ch) + 1)",
        "Number, add, back to letter.",
        "ch.next()",
        "No such method here.",
        "b",
      ),
      code(
        "l81-ord",
        "Key",
        "ord / chr",
        "Print ord(\"A\"), then chr(66).",
        "65 then B.",
        "print(ord(\"A\"))",
        "",
        "65\nB\n",
        "print(ord(\"A\"))\nprint(chr(66))",
        ["ord(\"A\")", "chr(66)", "Two prints"],
      ),
    ],
  ),
  lv(
    82,
    "Caesar Shift",
    "Sentinel",
    "Hard",
    "Move every letter one place forward with chr(ord(ch) + 1). A tiny cipher.",
    "Shift abc to bcd.",
    6100,
    2550,
    "caesar-shift",
    "Caesar Shift",
    "sentinel",
    "legend",
    [
      brief(
        "One step on the alphabet",
        "Build a new string. for ch in s: out += chr(ord(ch) + 1). \"abc\" → \"bcd\". This version does not wrap Z → A. Keep the mission small.",
        "out += chr(ord(ch) + 1)",
      ),
      choice(
        "immutable",
        "Why not s[0] = \"b\"?",
        "Indexes start at 1",
        "Strings cannot be assigned at an index. They are immutable.",
        "Strings cannot be changed in place",
        "Build a new string with += or join.",
        "ord would fail",
        "ord is fine. Assignment is the problem.",
        "b",
      ),
      code(
        "l82-cae",
        "Shift",
        "caesar +1",
        "Write shift(s) that moves every character one code point forward. Print shift(\"abc\").",
        "bcd",
        "out += chr(ord(ch) + 1)",
        "def shift(s):\n    return s\n",
        "bcd\n",
        "def shift(s):\n    out = \"\"\n    for ch in s:\n        out += chr(ord(ch) + 1)\n    return out\nprint(shift(\"abc\"))",
        ["out = \"\"", "chr(ord(ch) + 1)", "print(shift(\"abc\"))"],
      ),
    ],
  ),
  lv(
    83,
    "Case Gate",
    "Sentinel",
    "Medium",
    "isupper, islower, isspace classify a character. Empty strings are False.",
    "Stamp U, S, L for \"A z\".",
    6200,
    2600,
    "case-gate",
    "Case Gate",
    "sentinel",
    "legend",
    [
      brief(
        "Three gates",
        "Walk \"A z\". A is upper → U. space is space → S. z is lower → L. elif chain so a letter is not also called space.",
        "if ch.isupper():\n    print(\"U\")\nelif ch.islower():\n    print(\"L\")",
      ),
      choice(
        "space",
        "Does \" \".isalpha() pass?",
        "Yes",
        "Space is not a letter. isspace is the test.",
        "No",
        "isalpha needs A–Z or a–z.",
        "Only in Python 2",
        "Same rule in Python 3.",
        "b",
      ),
      code(
        "l83-case",
        "Classify",
        "isupper/islower/isspace",
        "For each character in \"A z\": print U if upper, S if space, L if lower.",
        "U, S, L on three lines.",
        "if ch.isupper():",
        "text = \"A z\"\n",
        "U\nS\nL\n",
        "text = \"A z\"\nfor ch in text:\n    if ch.isupper():\n        print(\"U\")\n    elif ch.isspace():\n        print(\"S\")\n    elif ch.islower():\n        print(\"L\")",
        ["for ch in text:", "isupper / isspace / islower", "Print U, S, L"],
      ),
    ],
  ),
  lv(
    84,
    "Freq Table",
    "Sentinel",
    "Hard",
    "A dictionary of counts. If the key exists, add 1. Else plant 1.",
    "Count letters in aba.",
    6300,
    2650,
    "freq-table",
    "Freq Table",
    "sentinel",
    "legend",
    [
      brief(
        "Tally by key",
        "freq = {}. for ch in text: if ch in freq: freq[ch] = freq[ch] + 1 else: freq[ch] = 1. \"aba\" → a:2, b:1. Then print the two lookups.",
        "if ch in freq:\n    freq[ch] = freq[ch] + 1\nelse:\n    freq[ch] = 1",
      ),
      choice(
        "missing key",
        "What if you write freq[ch] = freq[ch] + 1 on a new letter?",
        "It starts at 1",
        "KeyError. The key is not there yet.",
        "KeyError",
        "Plant the first 1 in the else branch, or use setdefault.",
        "It stays 0",
        "There is no 0 until you put one.",
        "b",
      ),
      code(
        "l84-freq",
        "Tally",
        "frequency dict",
        "Count characters in \"aba\". Print freq[\"a\"] then freq[\"b\"].",
        "2 then 1.",
        "freq[ch] = freq[ch] + 1",
        "text = \"aba\"\n",
        "2\n1\n",
        "text = \"aba\"\nfreq = {}\nfor ch in text:\n    if ch in freq:\n        freq[ch] = freq[ch] + 1\n    else:\n        freq[ch] = 1\nprint(freq[\"a\"])\nprint(freq[\"b\"])",
        ["freq = {}", "if ch in freq", "print freq of a and b"],
      ),
    ],
  ),
  lv(
    85,
    "Anagram Seal",
    "Sentinel",
    "Medium / Hard",
    "Same letters, new order. sorted(a) == sorted(b).",
    "listen/silent vs cat/car.",
    6400,
    2700,
    "anagram-seal",
    "Anagram Seal",
    "sentinel",
    "legend",
    [
      brief(
        "Sort and compare",
        "sorted(\"listen\") and sorted(\"silent\") are the same list of letters. Length can differ — sorted then catches that too. This ignores meaning, only letters.",
        "return sorted(a) == sorted(b)",
      ),
      choice(
        "length",
        "Are \"aa\" and \"a\" anagrams?",
        "Yes, same letters",
        "Counts must match. sorted differs in length.",
        "No — counts differ",
        "Anagrams are rearrangements, not subsets.",
        "Only if sorted",
        "sorted would not be equal.",
        "b",
      ),
      code(
        "l85-ana",
        "Seal",
        "anagram",
        "Write ana(a, b) True when sorted letters match. Print ana(\"listen\", \"silent\") then ana(\"cat\", \"car\").",
        "True then False.",
        "return sorted(a) == sorted(b)",
        "def ana(a, b):\n    return a == b\n",
        "True\nFalse\n",
        "def ana(a, b):\n    return sorted(a) == sorted(b)\nprint(ana(\"listen\", \"silent\"))\nprint(ana(\"cat\", \"car\"))",
        ["sorted(a) == sorted(b)", "print both calls", "Do not compare a == b raw"],
      ),
    ],
  ),
  lv(
    86,
    "Merge Unique",
    "Sentinel",
    "Medium / Hard",
    "Concatenate two lists, then keep first-seen uniques.",
    "Merge [1, 2, 3] with [3, 4].",
    6500,
    2750,
    "merge-unique",
    "Merge Unique",
    "sentinel",
    "legend",
    [
      brief(
        "Plus, then press",
        "a + b concatenates. Then the unique press from earlier. [1, 2, 3] + [3, 4] → drop the second 3 → [1, 2, 3, 4].",
        "for x in a + b:\n    if x not in out:\n        out.append(x)",
      ),
      choice(
        "plus lists",
        "[1, 2] + [2] equals?",
        "[1, 2]",
        "Plus concatenates, it does not unique. [1, 2, 2].",
        "[1, 2, 2]",
        "Then you unique in a second step.",
        "[3]",
        "That would add items.",
        "b",
      ),
      code(
        "l86-merge",
        "Merge",
        "concat + unique",
        "Merge a = [1, 2, 3] and b = [3, 4] into a unique list in first-seen order. Print it.",
        "[1, 2, 3, 4]",
        "for x in a + b:",
        "a = [1, 2, 3]\nb = [3, 4]\n",
        "[1, 2, 3, 4]\n",
        "a = [1, 2, 3]\nb = [3, 4]\nout = []\nfor x in a + b:\n    if x not in out:\n        out.append(x)\nprint(out)",
        ["a + b", "if x not in out", "print(out)"],
      ),
    ],
  ),
  lv(
    87,
    "Stock Ledger",
    "Sentinel",
    "Medium",
    "Add to an existing key. Create a missing one. Inventory math.",
    "Add 3 pens and stock a new mug.",
    6600,
    2800,
    "stock-ledger",
    "Stock Ledger",
    "sentinel",
    "legend",
    [
      brief(
        "Read, add, write",
        "stock[\"pen\"] = stock[\"pen\"] + 3. A new item is just stock[\"mug\"] = 1. Reading a missing key is KeyError — create it instead.",
        "stock[\"pen\"] = stock[\"pen\"] + 3\nstock[\"mug\"] = 1",
      ),
      choice(
        "missing",
        "stock[\"mug\"] + 1 when mug is missing?",
        "Creates mug",
        "KeyError on the read.",
        "KeyError",
        "Assign a first value when the key is new.",
        "0",
        "No implicit zero.",
        "b",
      ),
      code(
        "l87-stock",
        "Ledger",
        "dict update values",
        "stock starts {\"pen\": 2}. Add 3 pens. Set mug to 1. Print pen then mug.",
        "5 then 1.",
        "stock[\"pen\"] = stock[\"pen\"] + 3",
        "stock = {\"pen\": 2}\n",
        "5\n1\n",
        "stock = {\"pen\": 2}\nstock[\"pen\"] = stock[\"pen\"] + 3\nstock[\"mug\"] = 1\nprint(stock[\"pen\"])\nprint(stock[\"mug\"])",
        ["add 3 to pen", "stock[\"mug\"] = 1", "Two prints"],
      ),
    ],
  ),
  lv(
    88,
    "Update Kit",
    "Sentinel",
    "Medium / Hard",
    "update merges another dict in place. setdefault plants a default if missing.",
    "Merge a role, then tally with setdefault.",
    6700,
    2850,
    "update-kit",
    "Update Kit",
    "sentinel",
    "legend",
    [
      brief(
        "Two dict tools",
        "user.update({\"role\": \"lead\"}) writes/overwrites keys. freq.setdefault(\"a\", 0) returns the current value, planting 0 if new. Then you can add 1.",
        "freq.setdefault(\"a\", 0)\nfreq[\"a\"] = freq[\"a\"] + 1",
      ),
      choice(
        "setdefault",
        "If a is already 4, setdefault(\"a\", 0) returns?",
        "0",
        "It only plants when missing. It returns 4.",
        "4",
        "Existing value wins.",
        "None",
        "You passed 0 as the default, but it is not used.",
        "b",
      ),
      code(
        "l88-upd",
        "Kit",
        "update / setdefault",
        "user is {\"name\": \"Ada\"}. update role to lead and print it. Then freq = {}, setdefault a to 0, add 1, print freq[\"a\"].",
        "lead then 1.",
        "user.update({\"role\": \"lead\"})",
        "user = {\"name\": \"Ada\"}\n",
        "lead\n1\n",
        "user = {\"name\": \"Ada\"}\nuser.update({\"role\": \"lead\"})\nprint(user[\"role\"])\nfreq = {}\nfreq.setdefault(\"a\", 0)\nfreq[\"a\"] = freq[\"a\"] + 1\nprint(freq[\"a\"])",
        ["user.update(...)", "setdefault(\"a\", 0)", "add 1 and print"],
      ),
    ],
  ),
  lv(
    89,
    "Mean Desk",
    "Mythic",
    "Medium",
    "Integer mean: sum with a loop, divide with //. No floating surprise.",
    "Mean of 80, 90, 70.",
    6800,
    2900,
    "mean-desk",
    "Mean Desk",
    "mythic",
    "legend",
    [
      brief(
        "Floor the average",
        "s = 0; for n in nums: s += n; return s // len(nums). 240 // 3 is 80. // drops the decimal on purpose for this desk.",
        "return s // len(nums)",
      ),
      choice(
        "slash",
        "Why // not / here?",
        "/ is illegal",
        "/ works and would print 80.0. The mission wants a whole number.",
        "The briefing asks for an integer mean",
        "80 not 80.0.",
        "// is faster",
        "Not the reason in this course.",
        "b",
      ),
      code(
        "l89-mean",
        "Desk",
        "integer mean",
        "Write mean(nums) as integer average with //. Print mean([80, 90, 70]).",
        "80.",
        "return s // len(nums)",
        "def mean(nums):\n    return 0\n",
        "80\n",
        "def mean(nums):\n    s = 0\n    for n in nums:\n        s += n\n    return s // len(nums)\nprint(mean([80, 90, 70]))",
        ["sum with a loop", "s // len(nums)", "print the call"],
      ),
    ],
  ),
  lv(
    90,
    "Nested Pass",
    "Mythic",
    "Medium / Hard",
    "Walk a dict of records. Print names whose nested ok is True.",
    "Ada and Kai pass. Lin does not.",
    6900,
    2950,
    "nested-pass",
    "Nested Pass",
    "mythic",
    "legend",
    [
      brief(
        "Record inside a record",
        "for name in desk: if desk[name][\"ok\"]: print(name). Dictionary order is insertion order: Ada, Lin, Kai — Lin is skipped.",
        "if desk[name][\"ok\"]:\n    print(name)",
      ),
      choice(
        "truth",
        "if desk[name][\"ok\"] tests what?",
        "The name string",
        "It tests the nested boolean.",
        "Whether that record’s ok is true",
        "True prints. False skips.",
        "Whether the key exists",
        "Missing ok would be KeyError. It exists here.",
        "b",
      ),
      code(
        "l90-ok",
        "Pass list",
        "nested dict filter",
        "desk maps names to {ok: bool}. Print each name whose ok is True, in dict order.",
        "Ada then Kai.",
        "if desk[name][\"ok\"]:",
        "desk = {\"Ada\": {\"ok\": True}, \"Lin\": {\"ok\": False}, \"Kai\": {\"ok\": True}}\n",
        "Ada\nKai\n",
        "desk = {\"Ada\": {\"ok\": True}, \"Lin\": {\"ok\": False}, \"Kai\": {\"ok\": True}}\nfor name in desk:\n    if desk[name][\"ok\"]:\n        print(name)",
        ["for name in desk:", "if desk[name][\"ok\"]:", "print(name)"],
      ),
    ],
  ),
  lv(
    91,
    "Pair Sheet",
    "Mythic",
    "Medium",
    "zip keys to values and print k=v lines. A tiny report sheet.",
    "name=Ada and job=lead.",
    7000,
    3000,
    "pair-sheet",
    "Pair Sheet",
    "mythic",
    "legend",
    [
      brief(
        "Two rails, one sheet",
        "for k, v in zip(keys, vals): print(k + \"=\" + v). Both values are strings here, so + is enough. str() if a number appears later.",
        "print(k + \"=\" + v)",
      ),
      choice(
        "plus",
        "k + \"=\" + 7 would?",
        "Print name=7",
        "TypeError — int is not str. Use str(7).",
        "TypeError unless you str() the number",
        "This mission’s values are already strings.",
        "Print 7",
        "The + would fail first.",
        "b",
      ),
      code(
        "l91-sheet",
        "Sheet",
        "zip report",
        "keys = name, job. vals = Ada, lead. Print each as key=value.",
        "name=Ada then job=lead.",
        "print(k + \"=\" + v)",
        "keys = [\"name\", \"job\"]\nvals = [\"Ada\", \"lead\"]\n",
        "name=Ada\njob=lead\n",
        "keys = [\"name\", \"job\"]\nvals = [\"Ada\", \"lead\"]\nfor k, v in zip(keys, vals):\n    print(k + \"=\" + v)",
        ["for k, v in zip(keys, vals):", "k + \"=\" + v", "Two lines"],
      ),
    ],
  ),
  lv(
    92,
    "Histo Bar",
    "Mythic",
    "Hard",
    "Stars for counts. n: plus \"*\" * count. A chart you can read.",
    "Histogram of [1, 2, 2, 3, 3, 3] for 1..3.",
    7100,
    3050,
    "histo-bar",
    "Histo Bar",
    "mythic",
    "legend",
    [
      brief(
        "Count then draw",
        "for n in range(1, 4): print(str(n) + \":\" + \"*\" * scores.count(n)). 1 once, 2 twice, 3 thrice. String * int repeats the bar.",
        "print(str(n) + \":\" + \"*\" * scores.count(n))",
      ),
      choice(
        "count",
        "[1, 2, 2].count(2) is?",
        "1",
        "Two is there twice.",
        "2",
        "count walks the whole list.",
        "3",
        "Length is 3, count of 2 is 2.",
        "b",
      ),
      code(
        "l92-hist",
        "Bars",
        "histogram",
        "scores = [1, 2, 2, 3, 3, 3]. For n in 1, 2, 3 print n: plus that many stars.",
        "1:* then 2:** then 3:***",
        "\"*\" * scores.count(n)",
        "scores = [1, 2, 2, 3, 3, 3]\n",
        "1:*\n2:**\n3:***\n",
        "scores = [1, 2, 2, 3, 3, 3]\nfor n in range(1, 4):\n    print(str(n) + \":\" + \"*\" * scores.count(n))",
        ["for n in range(1, 4):", "str(n) + \":\" + stars", "count(n)"],
      ),
    ],
  ),
  lv(
    93,
    "Rotate Ring",
    "Mythic",
    "Medium",
    "pop(0) takes the front. append puts it on the back. The ring turns once.",
    "Rotate [1, 2, 3, 4] left by one.",
    7200,
    3100,
    "rotate-ring",
    "Rotate Ring",
    "mythic",
    "legend",
    [
      brief(
        "Front to back",
        "first = items.pop(0) removes index 0 and returns it. items.append(first) hangs it on the end. [1, 2, 3, 4] becomes [2, 3, 4, 1].",
        "first = items.pop(0)\nitems.append(first)",
      ),
      choice(
        "pop 0",
        "pop() with no args takes?",
        "The first item",
        "Bare pop takes the last. pop(0) takes the first.",
        "The last item",
        "Default is the end. Pass 0 for the front.",
        "A random item",
        "Index is explicit.",
        "b",
      ),
      code(
        "l93-rot",
        "Ring",
        "rotate left",
        "items = [1, 2, 3, 4]. Move the first item to the end. Print items.",
        "[2, 3, 4, 1]",
        "items.append(items.pop(0))",
        "items = [1, 2, 3, 4]\n",
        "[2, 3, 4, 1]\n",
        "items = [1, 2, 3, 4]\nfirst = items.pop(0)\nitems.append(first)\nprint(items)",
        ["pop(0)", "append that value", "print(items)"],
      ),
    ],
  ),
  lv(
    94,
    "Window Sum",
    "Mythic",
    "Medium / Hard",
    "Add each neighbor pair as you walk. A window of two.",
    "Neighbor sums of [3, 1, 4, 1].",
    7300,
    3150,
    "window-sum",
    "Window Sum",
    "mythic",
    "legend",
    [
      brief(
        "i and i+1",
        "i from 0 while i < len(items) - 1: print(items[i] + items[i + 1]); i += 1. Four items → three windows: 3+1, 1+4, 4+1.",
        "while i < len(items) - 1:\n    print(items[i] + items[i + 1])\n    i += 1",
      ),
      choice(
        "last index",
        "Why stop at len - 1?",
        "Indexes start at 1",
        "items[i+1] would fall off the end if i is the last index.",
        "i+1 must still be a valid index",
        "Last pair starts at the second-to-last item.",
        "Windows are even",
        "Count of windows is n-1, not about even.",
        "b",
      ),
      code(
        "l94-win",
        "Windows",
        "pairwise sum",
        "items = [3, 1, 4, 1]. Print the sum of each neighbor pair, in order.",
        "4, 5, 5.",
        "print(items[i] + items[i + 1])",
        "items = [3, 1, 4, 1]\n",
        "4\n5\n5\n",
        "items = [3, 1, 4, 1]\ni = 0\nwhile i < len(items) - 1:\n    print(items[i] + items[i + 1])\n    i += 1",
        ["i = 0", "while i < len(items) - 1", "print pair sum"],
      ),
    ],
  ),
  lv(
    95,
    "Clock Mod",
    "Mythic",
    "Medium",
    "% 24 wraps hours. 22 + 5 is 3 o’clock, not 27.",
    "Wrap 22+5 and 0+24.",
    7400,
    3200,
    "clock-mod",
    "Clock Mod",
    "mythic",
    "legend",
    [
      brief(
        "A circle of 24",
        "return (h + add) % 24. 22+5 = 27, 27 % 24 is 3. 0+24 % 24 is 0 — midnight again. Negative hours are out of scope.",
        "return (h + add) % 24",
      ),
      choice(
        "24",
        "24 % 24 is?",
        "24",
        "A full circle is 0, not 24, on a 0–23 clock.",
        "0",
        "Exactly 24 hours lands on the same hour.",
        "1",
        "That would be 25 % 24.",
        "b",
      ),
      code(
        "l95-clock",
        "Wrap",
        "mod 24",
        "Write wrap(h, add) as (h + add) % 24. Print wrap(22, 5) then wrap(0, 24).",
        "3 then 0.",
        "return (h + add) % 24",
        "def wrap(h, add):\n    return h + add\n",
        "3\n0\n",
        "def wrap(h, add):\n    return (h + add) % 24\nprint(wrap(22, 5))\nprint(wrap(0, 24))",
        ["% 24", "print wrap(22, 5)", "print wrap(0, 24)"],
      ),
    ],
  ),
  lv(
    96,
    "Temp Forge",
    "Mythic",
    "Medium",
    "C to F with integer math: c * 9 // 5 + 32. 0 → 32, 100 → 212.",
    "Convert freezing and boiling.",
    7500,
    3250,
    "temp-forge",
    "Temp Forge",
    "mythic",
    "legend",
    [
      brief(
        "Integer Fahrenheit",
        "to_f(c) = c * 9 // 5 + 32. Multiply before you floor-divide so 100 * 9 // 5 is 180, plus 32 is 212. Parentheses optional here because * // bind left to right, then +.",
        "return c * 9 // 5 + 32",
      ),
      choice(
        "order",
        "Why not c * (9 // 5)?",
        "Same answer",
        "9 // 5 is 1, so you would add 32 to c. Freezing would still look ok; boiling would be 132.",
        "9 // 5 is 1, so boiling would be wrong",
        "Multiply first: 100 * 9 // 5.",
        "Python forbids it",
        "It runs. It is just the wrong formula.",
        "b",
      ),
      code(
        "l96-temp",
        "Forge",
        "C to F",
        "Write to_f(c) as integer Fahrenheit. Print to_f(0) then to_f(100).",
        "32 then 212.",
        "return c * 9 // 5 + 32",
        "def to_f(c):\n    return c\n",
        "32\n212\n",
        "def to_f(c):\n    return c * 9 // 5 + 32\nprint(to_f(0))\nprint(to_f(100))",
        ["c * 9 // 5 + 32", "print to_f(0)", "print to_f(100)"],
      ),
    ],
  ),
  lv(
    97,
    "Bit Tape",
    "Mythic",
    "Medium / Hard",
    "Odd → 1. Even → 0. Build a string of bits from a list of numbers.",
    "Tape for [1, 4, 5, 8].",
    7600,
    3300,
    "bit-tape",
    "Bit Tape",
    "mythic",
    "legend",
    [
      brief(
        "Parity as bits",
        "out = \"\". for n in nums: if n % 2 == 0: out += \"0\" else: out += \"1\". [1, 4, 5, 8] → 1010. This is not binary conversion of each n — only even/odd.",
        "if n % 2 == 0:\n    out += \"0\"\nelse:\n    out += \"1\"",
      ),
      choice(
        "parity",
        "Is 4 odd or even for this tape?",
        "Odd, bit 1",
        "4 % 2 is 0 → even → 0.",
        "Even, bit 0",
        "Remainder 0 means even.",
        "Both",
        "Pick one branch.",
        "b",
      ),
      code(
        "l97-bits",
        "Tape",
        "parity string",
        "From [1, 4, 5, 8] build a string: 1 if odd, 0 if even. Print it.",
        "1010",
        "out += \"1\"",
        "nums = [1, 4, 5, 8]\n",
        "1010\n",
        "nums = [1, 4, 5, 8]\nout = \"\"\nfor n in nums:\n    if n % 2 == 0:\n        out += \"0\"\n    else:\n        out += \"1\"\nprint(out)",
        ["out = \"\"", "even → 0, odd → 1", "print(out)"],
      ),
    ],
  ),
  lv(
    98,
    "Ticket Bay",
    "Mythic",
    "Medium / Hard",
    "A list of ticket records. Print ids whose open is True.",
    "Open tickets 1 and 3.",
    7700,
    3350,
    "ticket-bay",
    "Ticket Bay",
    "mythic",
    "legend",
    [
      brief(
        "Filter records",
        "for t in tickets: if t[\"open\"]: print(t[\"id\"]). Same pattern as nested pass, but the outer structure is a list, not a dict of names.",
        "if t[\"open\"]:\n    print(t[\"id\"])",
      ),
      choice(
        "key",
        "t[\"id\"] vs t.id?",
        "Same",
        "Python dicts use []. .id would be an attribute — TypeError on a dict.",
        "Use t[\"id\"] for a dictionary",
        "Brackets and a string key.",
        "Use t.id always",
        "That is another language’s records, or a class. Not this dict.",
        "b",
      ),
      code(
        "l98-tix",
        "Bay",
        "filter dict list",
        "tickets have id and open. Print the id of each open ticket, in list order.",
        "1 then 3.",
        "if t[\"open\"]:",
        "tickets = [{\"id\": 1, \"open\": True}, {\"id\": 2, \"open\": False}, {\"id\": 3, \"open\": True}]\n",
        "1\n3\n",
        "tickets = [{\"id\": 1, \"open\": True}, {\"id\": 2, \"open\": False}, {\"id\": 3, \"open\": True}]\nfor t in tickets:\n    if t[\"open\"]:\n        print(t[\"id\"])",
        ["for t in tickets:", "if t[\"open\"]:", "print(t[\"id\"])"],
      ),
    ],
  ),
  lv(
    99,
    "Pipe Link",
    "Mythic",
    "Medium / Hard",
    "One helper feeds another. clean then tag. A two-stage pipeline.",
    "Tag a stripped, lowered name.",
    7800,
    3400,
    "pipe-link",
    "Pipe Link",
    "mythic",
    "legend",
    [
      brief(
        "Return, don’t print inside",
        "clean(s) returns s.strip().lower(). tag(s) returns \"[\" + s + \"]\". Compose: tag(clean(\"  Ada  \")) → [ada]. Each function does one job.",
        "def clean(s):\n    return s.strip().lower()\ndef tag(s):\n    return \"[\" + s + \"]\"",
      ),
      choice(
        "compose",
        "tag(clean(x)) runs which first?",
        "tag",
        "Inner call runs first. clean, then tag.",
        "clean",
        "Inside-out. Same as math f(g(x)).",
        "Together",
        "They are two calls, nested.",
        "b",
      ),
      code(
        "l99-pipe",
        "Pipeline",
        "compose helpers",
        "Write clean(s) as strip+lower and tag(s) as [s]. Print tag(clean(\"  Ada  \")).",
        "[ada]",
        "print(tag(clean(\"  Ada  \")))",
        "def clean(s):\n    return s\ndef tag(s):\n    return s\n",
        "[ada]\n",
        "def clean(s):\n    return s.strip().lower()\ndef tag(s):\n    return \"[\" + s + \"]\"\nprint(tag(clean(\"  Ada  \")))",
        ["strip().lower()", "\"[\" + s + \"]\"", "print(tag(clean(...)))"],
      ),
    ],
  ),
  lv(
    100,
    "Immortal Championship",
    "Immortal",
    "Expert",
    "Final championship. Palindrome, zip filter, frequency report — under the clock.",
    "Clear every stage. Claim the Immortal Crown.",
    20000,
    6000,
    "immortal-crown",
    "Immortal Crown",
    "immortal",
    "legend",
    [
      brief(
        "The whole language",
        "Stage 1: a string equals its reverse. Stage 2: zip names to scores, print who passes. Stage 3: count a letter and write a labeled line. Colons, indents, quotes, print.",
        "def pal(s):\n    return s == s[::-1]",
      ),
      code(
        "l100-pal",
        "Stage 1 — Mirror",
        "palindrome",
        "Write pal(s) True when s equals s[::-1]. Print pal(\"radar\") then pal(\"jarvis\").",
        "True then False.",
        "return s == s[::-1]",
        "def pal(s):\n    return False\n",
        "True\nFalse\n",
        "def pal(s):\n    return s == s[::-1]\nprint(pal(\"radar\"))\nprint(pal(\"jarvis\"))",
        ["s == s[::-1]", "print pal(\"radar\")", "print pal(\"jarvis\")"],
      ),
      code(
        "l100-zip",
        "Stage 2 — Pass sheet",
        "zip + filter",
        "names Ada, Lin, Kai. scores 90, 60, 88. Print each name whose score is at least 70, using zip.",
        "Ada then Kai.",
        "for n, s in zip(names, scores):",
        "names = [\"Ada\", \"Lin\", \"Kai\"]\nscores = [90, 60, 88]\n",
        "Ada\nKai\n",
        "names = [\"Ada\", \"Lin\", \"Kai\"]\nscores = [90, 60, 88]\nfor n, s in zip(names, scores):\n    if s >= 70:\n        print(n)",
        ["zip(names, scores)", "if s >= 70", "print(n)"],
      ),
      code(
        "l100-freq",
        "Stage 3 — Letter report",
        "count + report",
        "Write report(text, ch) that returns ch + \"=\" + str(text.count(ch)). Print report(\"banana\", \"a\").",
        "a=3",
        "return ch + \"=\" + str(text.count(ch))",
        "def report(text, ch):\n    return \"\"\n",
        "a=3\n",
        "def report(text, ch):\n    return ch + \"=\" + str(text.count(ch))\nprint(report(\"banana\", \"a\"))",
        ["text.count(ch)", "str(...) for the number", "print(report(\"banana\", \"a\"))"],
      ),
    ],
    { timeLimitSec: 220, championship: true, finale: true },
  ),
];
