import type { LevelDef } from "./types.ts";

export const LEVELS_PLUS: LevelDef[] = [
  {
    id: 26,
    title: "Remainder Seal",
    job: "Legend",
    difficulty: "Medium",
    description: "The % operator is leftover after division. Even numbers leave 0.",
    objective: "Print remainders and spot an even number.",
    rewardCoins: 2800,
    rewardXp: 900,
    unlockRewardId: "remainder-seal",
    unlockReward: "Remainder Seal",
    careerUnlock: "master",
    chapter: "algorithms",
    steps: [
      {
        type: "brief",
        title: "Leftover, not the quotient",
        body: "17 % 5 is 2 because 5 fits into 17 three times and 2 is left. n % 2 == 0 means n is even. The % sign is not a percentage here — it is remainder.",
        example: "print(17 % 5)  # 2\nprint(8 % 2)   # 0",
      },
      {
        type: "choice",
        concept: "even test",
        question: "Which check is True when n is even?",
        options: [
          { id: "a", label: "n % 2 == 1", correct: false, explain: "A remainder of 1 means odd: 7 % 2 is 1." },
          { id: "b", label: "n % 2 == 0", correct: true, explain: "Even numbers divide by 2 with nothing left." },
          { id: "c", label: "n / 2 == 0", correct: false, explain: "Division gives a size, not a leftover. 8 / 2 is 4, not 0." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l26-mod",
          title: "Leftover",
          concept: "% remainder",
          prompt: "Print 17 % 5, then print 8 % 2, each on its own line.",
          briefing: "Do not quote the numbers. % is math.",
          example: "print(17 % 5)",
          starter: "",
          expected: "2\n0\n",
          solution: "print(17 % 5)\nprint(8 % 2)",
          hints: ["print(17 % 5)", "print(8 % 2)", "Two print calls."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l26-even",
          title: "Parity stamp",
          concept: "if + %",
          prompt: "n is 14. If n is even print EVEN, otherwise print ODD.",
          briefing: "if n % 2 == 0:",
          example: "if n % 2 == 0:\n    print(\"EVEN\")",
          starter: "n = 14\n",
          expected: "EVEN\n",
          solution: "n = 14\nif n % 2 == 0:\n    print(\"EVEN\")\nelse:\n    print(\"ODD\")",
          hints: ["if n % 2 == 0:", "print(\"EVEN\")", "else: print(\"ODD\")"],
        },
      },
    ],
  },
  {
    id: 27,
    title: "Power Cell",
    job: "Legend",
    difficulty: "Medium",
    description: "** raises a number. // divides and throws away the decimal.",
    objective: "Print a square and an integer division.",
    rewardCoins: 2900,
    rewardXp: 950,
    unlockRewardId: "power-cell",
    unlockReward: "Power Cell",
    careerUnlock: "master",
    chapter: "algorithms",
    steps: [
      {
        type: "brief",
        title: "Two division signs",
        body: "2 ** 5 is 32. 7 / 2 is 3.5. 7 // 2 is 3 — the floor. Use // when you want a whole number of groups.",
        example: "print(2 ** 5)\nprint(7 // 2)",
      },
      {
        type: "code",
        challenge: {
          id: "l27-pow",
          title: "Square",
          concept: "**",
          prompt: "Print 6 raised to the power of 2 using **.",
          briefing: "6 ** 2 is 36, not 12.",
          example: "print(6 ** 2)",
          starter: "",
          expected: "36\n",
          solution: "print(6 ** 2)",
          hints: ["Use ** not *", "print(6 ** 2)", "The answer is 36."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l27-floor",
          title: "Whole groups",
          concept: "//",
          prompt: "Print 17 // 5. That is how many full groups of 5 fit into 17.",
          briefing: "// drops the leftover. 17 // 5 is 3, not 3.4.",
          example: "print(17 // 5)",
          starter: "",
          expected: "3\n",
          solution: "print(17 // 5)",
          hints: ["Use // not /", "print(17 // 5)", "The leftover 2 is discarded."],
        },
      },
    ],
  },
  {
    id: 28,
    title: "Repeat Tape",
    job: "Legend",
    difficulty: "Easy / Medium",
    description: "A string times an integer repeats the text.",
    objective: "Print a repeated signal and a dashed rule.",
    rewardCoins: 3000,
    rewardXp: 1000,
    unlockRewardId: "repeat-tape",
    unlockReward: "Repeat Tape",
    careerUnlock: "master",
    chapter: "algorithms",
    steps: [
      {
        type: "brief",
        title: "Text × number",
        body: "\"go\" * 3 is gogogo. The number must be an integer. A space string times 4 is four spaces. This is how you draw a rule without typing it by hand.",
        example: "print(\"go\" * 3)\nprint(\"-\" * 5)",
      },
      {
        type: "code",
        challenge: {
          id: "l28-go",
          title: "Call three times",
          concept: "str * int",
          prompt: "Print go repeated exactly three times, no spaces: gogogo.",
          briefing: "\"go\" * 3",
          example: "print(\"go\" * 3)",
          starter: "",
          expected: "gogogo\n",
          solution: "print(\"go\" * 3)",
          hints: ["\"go\" * 3", "No extra spaces.", "Wrap in print."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l28-rule",
          title: "Rule line",
          concept: "str * int",
          prompt: "Print a line of exactly 8 dashes using *.",
          briefing: "\"-\" * 8",
          example: "print(\"-\" * 8)",
          starter: "",
          expected: "--------\n",
          solution: "print(\"-\" * 8)",
          hints: ["\"-\" * 8", "Eight dashes, no spaces.", "print that."],
        },
      },
    ],
  },
  {
    id: 29,
    title: "Member Pass",
    job: "Legend",
    difficulty: "Medium",
    description: "in asks whether something lives inside a string, list, or dict.",
    objective: "Test membership and print True or False.",
    rewardCoins: 3100,
    rewardXp: 1050,
    unlockRewardId: "member-pass",
    unlockReward: "Member Pass",
    careerUnlock: "legend",
    chapter: "algorithms",
    steps: [
      {
        type: "brief",
        title: "Present or absent",
        body: "\"th\" in \"Python\" is True. 9 in [1, 2, 3] is False. \"name\" in user checks keys, not values. not in is the opposite.",
        example: "print(\"th\" in \"Python\")\nprint(9 not in [1, 2, 3])",
      },
      {
        type: "choice",
        concept: "in on dict",
        question: "For user = {\"name\": \"Ada\"}, what does \"Ada\" in user check?",
        options: [
          { id: "a", label: "Whether Ada is a value", correct: false, explain: "in on a dict checks keys only. The key is name, the value is Ada." },
          { id: "b", label: "Whether Ada is a key", correct: true, explain: "\"Ada\" in user is False because the key is \"name\"." },
          { id: "c", label: "Whether the dict is named Ada", correct: false, explain: "The dict is named user. in looks inside it." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l29-str",
          title: "Substring",
          concept: "in str",
          prompt: "Print whether th is inside the string Python.",
          briefing: "print(\"th\" in \"Python\") shows True.",
          example: "print(\"th\" in \"Python\")",
          starter: "",
          expected: "True\n",
          solution: "print(\"th\" in \"Python\")",
          hints: ["\"th\" in \"Python\"", "Print the comparison.", "True has a capital T."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l29-list",
          title: "Missing seat",
          concept: "not in",
          prompt: "Print whether 9 is not in the list [1, 2, 3].",
          briefing: "9 not in [1, 2, 3] is True.",
          example: "print(9 not in [1, 2, 3])",
          starter: "",
          expected: "True\n",
          solution: "print(9 not in [1, 2, 3])",
          hints: ["Use not in", "print(9 not in [1, 2, 3])", "True — 9 is missing."],
        },
      },
    ],
  },
  {
    id: 30,
    title: "Chain Gate",
    job: "Oracle",
    difficulty: "Medium",
    description: "Python lets you write 1 < n < 10 the way math class does.",
    objective: "Print chained comparisons.",
    rewardCoins: 3200,
    rewardXp: 1100,
    unlockRewardId: "chain-gate",
    unlockReward: "Chain Gate",
    careerUnlock: "legend",
    chapter: "algorithms",
    steps: [
      {
        type: "brief",
        title: "Both sides at once",
        body: "1 < n < 10 is True only if n is greater than 1 and less than 10. You do not need and. Both comparisons must hold.",
        example: "n = 7\nprint(1 < n < 10)",
      },
      {
        type: "code",
        challenge: {
          id: "l30-in",
          title: "Inside the band",
          concept: "chained compare",
          prompt: "n is 7. Print the result of 1 < n < 10.",
          briefing: "7 is between 1 and 10, so True.",
          example: "print(1 < n < 10)",
          starter: "n = 7\n",
          expected: "True\n",
          solution: "n = 7\nprint(1 < n < 10)",
          hints: ["print(1 < n < 10)", "No and needed.", "True."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l30-out",
          title: "Outside",
          concept: "chained compare",
          prompt: "n is 10. Print 1 < n < 10. Think carefully: is 10 less than 10?",
          briefing: "The right side is strict. 10 < 10 is False, so the chain is False.",
          example: "print(1 < n < 10)",
          starter: "n = 10\n",
          expected: "False\n",
          solution: "n = 10\nprint(1 < n < 10)",
          hints: ["10 is not less than 10.", "print(1 < n < 10)", "False."],
        },
      },
    ],
  },
  {
    id: 31,
    title: "None Watch",
    job: "Oracle",
    difficulty: "Medium",
    description: "None is a real value that means “nothing here”.",
    objective: "Print None and branch when a box is empty.",
    rewardCoins: 3300,
    rewardXp: 1150,
    unlockRewardId: "none-watch",
    unlockReward: "None Watch",
    careerUnlock: "legend",
    chapter: "algorithms",
    steps: [
      {
        type: "brief",
        title: "Capital N",
        body: "None is a keyword, not a string. print(None) shows None. if x is None is the usual test, but == None also works here. Do not quote it.",
        example: "x = None\nprint(x)",
      },
      {
        type: "code",
        challenge: {
          id: "l31-print",
          title: "Empty box",
          concept: "None",
          prompt: "Assign x = None, then print x.",
          briefing: "No quotes around None.",
          example: "x = None\nprint(x)",
          starter: "",
          expected: "None\n",
          solution: "x = None\nprint(x)",
          hints: ["x = None", "No quotes.", "print(x)"],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l31-if",
          title: "Missing file",
          concept: "None branch",
          prompt: "note is None. If note equals None print MISSING, otherwise print note.",
          briefing: "if note == None:",
          example: "if note == None:\n    print(\"MISSING\")",
          starter: "note = None\n",
          expected: "MISSING\n",
          solution: "note = None\nif note == None:\n    print(\"MISSING\")\nelse:\n    print(note)",
          hints: ["if note == None:", "print(\"MISSING\")", "else: print(note)"],
        },
      },
    ],
  },
  {
    id: 32,
    title: "Truth Lens",
    job: "Oracle",
    difficulty: "Medium / Hard",
    description: "Empty lists and empty strings are False in an if.",
    objective: "Branch on emptiness.",
    rewardCoins: 3400,
    rewardXp: 1200,
    unlockRewardId: "truth-lens",
    unlockReward: "Truth Lens",
    careerUnlock: "legend",
    chapter: "algorithms",
    steps: [
      {
        type: "brief",
        title: "Empty is False",
        body: "if box: is False when box is []. if text: is False when text is \"\". Non-empty values are True. This saves you writing len(box) > 0.",
        example: "if box:\n    print(\"full\")\nelse:\n    print(\"empty\")",
      },
      {
        type: "choice",
        concept: "truthiness",
        question: "What does if \"\": print(\"yes\") do?",
        options: [
          { id: "a", label: "Prints yes", correct: false, explain: "An empty string is False, so the block is skipped." },
          { id: "b", label: "Prints nothing", correct: true, explain: "Empty string is False. The print never runs." },
          { id: "c", label: "Crashes", correct: false, explain: "Empty strings are legal. They are just False in a condition." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l32-list",
          title: "Empty crate",
          concept: "list truthiness",
          prompt: "box is []. If box is non-empty print full, otherwise print empty.",
          briefing: "if box: else.",
          example: "if box:\n    print(\"full\")\nelse:\n    print(\"empty\")",
          starter: "box = []\n",
          expected: "empty\n",
          solution: "box = []\nif box:\n    print(\"full\")\nelse:\n    print(\"empty\")",
          hints: ["if box:", "else: print(\"empty\")", "[] is False."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l32-str",
          title: "Named",
          concept: "str truthiness",
          prompt: "name is Ada. If name is non-empty print READY, otherwise print WAIT.",
          briefing: "A non-empty string is True.",
          example: "if name:\n    print(\"READY\")",
          starter: "name = \"Ada\"\n",
          expected: "READY\n",
          solution: "name = \"Ada\"\nif name:\n    print(\"READY\")\nelse:\n    print(\"WAIT\")",
          hints: ["if name:", "print(\"READY\")", "Ada is non-empty."],
        },
      },
    ],
  },
  {
    id: 33,
    title: "Swap File",
    job: "Sage",
    difficulty: "Medium",
    description: "replace rewrites text. find returns an index or -1.",
    objective: "Rewrite a callsign and locate a letter.",
    rewardCoins: 3500,
    rewardXp: 1250,
    unlockRewardId: "swap-file",
    unlockReward: "Swap File",
    careerUnlock: "oracle",
    chapter: "fluency",
    steps: [
      {
        type: "brief",
        title: "New string, old unchanged",
        body: "text.replace(\"a\", \"o\") returns a new string. find returns the first index, or -1 if missing. Remember the parentheses on methods.",
        example: "print(\"cat\".replace(\"a\", \"o\"))\nprint(\"Python\".find(\"t\"))",
      },
      {
        type: "code",
        challenge: {
          id: "l33-replace",
          title: "Rewrite",
          concept: "replace",
          prompt: "Print cat with a replaced by o, so the output is cot.",
          briefing: "\"cat\".replace(\"a\", \"o\")",
          example: "print(\"cat\".replace(\"a\", \"o\"))",
          starter: "",
          expected: "cot\n",
          solution: "print(\"cat\".replace(\"a\", \"o\"))",
          hints: ["replace(\"a\", \"o\")", "Call it on \"cat\".", "Print the result."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l33-find",
          title: "First t",
          concept: "find",
          prompt: "Print the index of the first t in Python using find.",
          briefing: "P=0, y=1, t=2. find returns 2.",
          example: "print(\"Python\".find(\"t\"))",
          starter: "",
          expected: "2\n",
          solution: "print(\"Python\".find(\"t\"))",
          hints: ["\"Python\".find(\"t\")", "Indexes start at 0.", "The first t is 2."],
        },
      },
    ],
  },
  {
    id: 34,
    title: "Prefix Badge",
    job: "Sage",
    difficulty: "Medium",
    description: "startswith and endswith check the edges of a string.",
    objective: "Print True/False for a prefix and a suffix.",
    rewardCoins: 3600,
    rewardXp: 1300,
    unlockRewardId: "prefix-badge",
    unlockReward: "Prefix Badge",
    careerUnlock: "oracle",
    chapter: "fluency",
    steps: [
      {
        type: "brief",
        title: "Edges only",
        body: "\"hello\".startswith(\"he\") is True. \"hello\".endswith(\"HE\") is False — capitals matter. These methods return booleans, so you can print them or use them in if.",
        example: "print(\"hello\".startswith(\"he\"))\nprint(\"file.py\".endswith(\".py\"))",
      },
      {
        type: "code",
        challenge: {
          id: "l34-start",
          title: "Opens with",
          concept: "startswith",
          prompt: "Print whether hello starts with he.",
          briefing: "startswith returns True or False.",
          example: "print(\"hello\".startswith(\"he\"))",
          starter: "",
          expected: "True\n",
          solution: "print(\"hello\".startswith(\"he\"))",
          hints: ["\"hello\".startswith(\"he\")", "Print it.", "True."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l34-end",
          title: "Python file",
          concept: "endswith",
          prompt: "name is mission.py. Print whether it ends with .py.",
          briefing: "The dot is part of the suffix string.",
          example: "print(name.endswith(\".py\"))",
          starter: "name = \"mission.py\"\n",
          expected: "True\n",
          solution: "name = \"mission.py\"\nprint(name.endswith(\".py\"))",
          hints: ["name.endswith(\".py\")", "Include the dot.", "Print the boolean."],
        },
      },
    ],
  },
  {
    id: 35,
    title: "Digit Gate",
    job: "Sage",
    difficulty: "Medium",
    description: "isdigit and isalpha classify a whole string.",
    objective: "Print whether tokens are digits or letters.",
    rewardCoins: 3700,
    rewardXp: 1350,
    unlockRewardId: "digit-gate",
    unlockReward: "Digit Gate",
    careerUnlock: "oracle",
    chapter: "fluency",
    steps: [
      {
        type: "brief",
        title: "The whole string",
        body: "\"42\".isdigit() is True. \"4a\".isdigit() is False — every character must be a digit. isalpha is the letter version. Empty strings are False.",
        example: "print(\"42\".isdigit())\nprint(\"Ada\".isalpha())",
      },
      {
        type: "code",
        challenge: {
          id: "l35-digit",
          title: "Numeric token",
          concept: "isdigit",
          prompt: "Print whether 42 (as a string) is all digits, then whether 4a is all digits.",
          briefing: "Two lines: True then False.",
          example: "print(\"42\".isdigit())\nprint(\"4a\".isdigit())",
          starter: "",
          expected: "True\nFalse\n",
          solution: "print(\"42\".isdigit())\nprint(\"4a\".isdigit())",
          hints: ["\"42\".isdigit()", "\"4a\".isdigit()", "Two prints."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l35-alpha",
          title: "Letters only",
          concept: "isalpha",
          prompt: "Print whether Ada is all letters.",
          briefing: "isalpha() — parentheses required.",
          example: "print(\"Ada\".isalpha())",
          starter: "",
          expected: "True\n",
          solution: "print(\"Ada\".isalpha())",
          hints: ["\"Ada\".isalpha()", "Do not forget ().", "True."],
        },
      },
    ],
  },
  {
    id: 36,
    title: "Pop Stack",
    job: "Director",
    difficulty: "Medium / Hard",
    description: "pop removes and returns. insert places an item at an index.",
    objective: "Pop the last seat, then insert at the front.",
    rewardCoins: 3800,
    rewardXp: 1400,
    unlockRewardId: "pop-stack",
    unlockReward: "Pop Stack",
    careerUnlock: "oracle",
    chapter: "fluency",
    steps: [
      {
        type: "brief",
        title: "Take and place",
        body: "team.pop() removes the last item and returns it — you can print that return. insert(0, x) puts x at the front. Both change the list in place.",
        example: "print(team.pop())\nteam.insert(0, \"Ada\")",
      },
      {
        type: "code",
        challenge: {
          id: "l36-pop",
          title: "Last out",
          concept: "pop",
          prompt: "team is Ada, Lin, Kai. Pop the last name and print what pop returns. Then print the list.",
          briefing: "Two prints: Kai then the remaining list.",
          example: "print(team.pop())\nprint(team)",
          starter: "team = [\"Ada\", \"Lin\", \"Kai\"]\n",
          expected: "Kai\n['Ada', 'Lin']\n",
          solution: "team = [\"Ada\", \"Lin\", \"Kai\"]\nprint(team.pop())\nprint(team)",
          hints: ["print(team.pop())", "Then print(team)", "Kai comes off the end."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l36-insert",
          title: "Front of line",
          concept: "insert",
          prompt: "queue is Lin, Kai. Insert Ada at index 0, then print the list.",
          briefing: "queue.insert(0, \"Ada\")",
          example: "queue.insert(0, \"Ada\")\nprint(queue)",
          starter: "queue = [\"Lin\", \"Kai\"]\n",
          expected: "['Ada', 'Lin', 'Kai']\n",
          solution: "queue = [\"Lin\", \"Kai\"]\nqueue.insert(0, \"Ada\")\nprint(queue)",
          hints: ["insert(0, \"Ada\")", "Index 0 is the front.", "print(queue) after."],
        },
      },
    ],
  },
  {
    id: 37,
    title: "Mutate Rack",
    job: "Director",
    difficulty: "Medium / Hard",
    description: "sort and reverse change the list. They return None.",
    objective: "Sort in place, then reverse in place.",
    rewardCoins: 3900,
    rewardXp: 1450,
    unlockRewardId: "mutate-rack",
    unlockReward: "Mutate Rack",
    careerUnlock: "sage",
    chapter: "fluency",
    steps: [
      {
        type: "brief",
        title: "In place vs sorted",
        body: "nums.sort() changes nums and returns None. sorted(nums) returns a new list. reverse() flips the current order. Print the list after you mutate it, not the method call.",
        example: "nums.sort()\nprint(nums)",
      },
      {
        type: "choice",
        concept: "sort return",
        question: "What does print(nums.sort()) show?",
        options: [
          { id: "a", label: "The sorted list", correct: false, explain: "sort returns None. Print nums afterwards." },
          { id: "b", label: "None", correct: true, explain: "Mutating methods return None. The list changed silently." },
          { id: "c", label: "An error", correct: false, explain: "It is legal — just not useful to print." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l37-sort",
          title: "Order in place",
          concept: "sort",
          prompt: "nums is [5, 1, 4]. Sort it in place, then print nums.",
          briefing: "nums.sort() then print(nums).",
          example: "nums.sort()\nprint(nums)",
          starter: "nums = [5, 1, 4]\n",
          expected: "[1, 4, 5]\n",
          solution: "nums = [5, 1, 4]\nnums.sort()\nprint(nums)",
          hints: ["nums.sort()", "Do not print the call.", "print(nums)"],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l37-rev",
          title: "Flip",
          concept: "reverse",
          prompt: "items is [1, 2, 3]. Reverse it in place, then print the list.",
          briefing: "items.reverse()",
          example: "items.reverse()\nprint(items)",
          starter: "items = [1, 2, 3]\n",
          expected: "[3, 2, 1]\n",
          solution: "items = [1, 2, 3]\nitems.reverse()\nprint(items)",
          hints: ["items.reverse()", "Then print(items)", "[3, 2, 1]"],
        },
      },
    ],
  },
  {
    id: 38,
    title: "Count Desk",
    job: "Director",
    difficulty: "Medium",
    description: "count tells you how many times a value appears.",
    objective: "Count in a list and in a string.",
    rewardCoins: 4000,
    rewardXp: 1500,
    unlockRewardId: "count-desk",
    unlockReward: "Count Desk",
    careerUnlock: "sage",
    chapter: "fluency",
    steps: [
      {
        type: "brief",
        title: "How many",
        body: "[1, 2, 1, 1].count(1) is 3. \"banana\".count(\"a\") is 3. Missing values count as 0, they do not crash.",
        example: "print(nums.count(1))\nprint(\"banana\".count(\"a\"))",
      },
      {
        type: "code",
        challenge: {
          id: "l38-list",
          title: "Ones",
          concept: "list.count",
          prompt: "nums is [1, 2, 1, 1]. Print how many times 1 appears.",
          briefing: "nums.count(1)",
          example: "print(nums.count(1))",
          starter: "nums = [1, 2, 1, 1]\n",
          expected: "3\n",
          solution: "nums = [1, 2, 1, 1]\nprint(nums.count(1))",
          hints: ["nums.count(1)", "Print that.", "The answer is 3."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l38-str",
          title: "Letter a",
          concept: "str.count",
          prompt: "Print how many times a appears in banana.",
          briefing: "\"banana\".count(\"a\")",
          example: "print(\"banana\".count(\"a\"))",
          starter: "",
          expected: "3\n",
          solution: "print(\"banana\".count(\"a\"))",
          hints: ["\"banana\".count(\"a\")", "Three a's.", "Print the number."],
        },
      },
    ],
  },
  {
    id: 39,
    title: "Enum Walk",
    job: "Sage",
    difficulty: "Hard",
    description: "enumerate gives you the index and the item together.",
    objective: "Print each index, then each item.",
    rewardCoins: 4200,
    rewardXp: 1600,
    unlockRewardId: "enum-walk",
    unlockReward: "Enum Walk",
    careerUnlock: "sage",
    chapter: "fluency",
    steps: [
      {
        type: "brief",
        title: "Two names on the for line",
        body: "for i, x in enumerate(items): unpacks each pair. i is 0, 1, 2… x is the value. You need both names, a comma, and enumerate around the list.",
        example: "for i, x in enumerate([\"a\", \"b\"]):\n    print(i)\n    print(x)",
      },
      {
        type: "code",
        challenge: {
          id: "l39-enum",
          title: "Numbered seats",
          concept: "enumerate",
          prompt: "Loop enumerate([\"a\", \"b\"]) as i, x. Print i then x, each on its own line.",
          briefing: "Four lines: 0, a, 1, b.",
          example: "for i, x in enumerate([\"a\", \"b\"]):\n    print(i)\n    print(x)",
          starter: "",
          expected: "0\na\n1\nb\n",
          solution: "for i, x in enumerate([\"a\", \"b\"]):\n    print(i)\n    print(x)",
          hints: ["for i, x in enumerate([\"a\", \"b\"]):", "print(i)", "print(x)"],
        },
      },
    ],
  },
  {
    id: 40,
    title: "Pair Unpack",
    job: "Director",
    difficulty: "Hard",
    description: "items() yields (key, value) pairs you can unpack.",
    objective: "Walk a dict printing each key then each value.",
    rewardCoins: 4300,
    rewardXp: 1650,
    unlockRewardId: "pair-unpack",
    unlockReward: "Pair Unpack",
    careerUnlock: "sage",
    chapter: "fluency",
    steps: [
      {
        type: "brief",
        title: "Two names, one pair",
        body: "for k, v in scores.items(): sets k to the key and v to the value. Insertion order is Ada then Kai.",
        example: "for k, v in scores.items():\n    print(k)\n    print(v)",
      },
      {
        type: "code",
        challenge: {
          id: "l40-items",
          title: "Open the pairs",
          concept: "dict.items",
          prompt: "scores maps Ada to 90 and Kai to 70. Unpack items as k, v. Print k then v, each on its own line.",
          briefing: "Four lines: Ada, 90, Kai, 70.",
          example: "for k, v in scores.items():\n    print(k)\n    print(v)",
          starter: "scores = {\"Ada\": 90, \"Kai\": 70}\n",
          expected: "Ada\n90\nKai\n70\n",
          solution: "scores = {\"Ada\": 90, \"Kai\": 70}\nfor k, v in scores.items():\n    print(k)\n    print(v)",
          hints: ["for k, v in scores.items():", "print(k)", "print(v)"],
        },
      },
    ],
  },
  {
    id: 41,
    title: "Grid Key",
    job: "Director",
    difficulty: "Hard",
    description: "A list of lists is a grid. Two indexes: row, then column.",
    objective: "Read a cell, then overwrite one.",
    rewardCoins: 4400,
    rewardXp: 1700,
    unlockRewardId: "grid-key",
    unlockReward: "Grid Key",
    careerUnlock: "director",
    chapter: "studio",
    steps: [
      {
        type: "brief",
        title: "Row then column",
        body: "grid[1][0] is row 1, column 0. Both indexes start at 0. You can assign grid[0][1] = 9 to replace a cell.",
        example: "grid = [[1, 2], [3, 4]]\nprint(grid[1][0])",
      },
      {
        type: "code",
        challenge: {
          id: "l41-read",
          title: "Lower left",
          concept: "nested list",
          prompt: "grid is [[1, 2], [3, 4]]. Print the value at row 1, column 0.",
          briefing: "That cell is 3.",
          example: "print(grid[1][0])",
          starter: "grid = [[1, 2], [3, 4]]\n",
          expected: "3\n",
          solution: "grid = [[1, 2], [3, 4]]\nprint(grid[1][0])",
          hints: ["grid[1][0]", "Row 1 is [3, 4].", "Column 0 is 3."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l41-write",
          title: "Overwrite a cell",
          concept: "nested assign",
          prompt: "Set grid[0][1] to 9, then print the whole grid.",
          briefing: "grid[0][1] = 9 mutates the inner list.",
          example: "grid[0][1] = 9\nprint(grid)",
          starter: "grid = [[1, 2], [3, 4]]\n",
          expected: "[[1, 9], [3, 4]]\n",
          solution: "grid = [[1, 2], [3, 4]]\ngrid[0][1] = 9\nprint(grid)",
          hints: ["grid[0][1] = 9", "print(grid)", "The 2 becomes 9."],
        },
      },
    ],
  },
  {
    id: 42,
    title: "Nested Vault",
    job: "Director",
    difficulty: "Hard",
    description: "A dictionary can hold another dictionary as a value.",
    objective: "Read a nested field, then update one.",
    rewardCoins: 4500,
    rewardXp: 1750,
    unlockRewardId: "nested-vault",
    unlockReward: "Nested Vault",
    careerUnlock: "director",
    chapter: "studio",
    steps: [
      {
        type: "brief",
        title: "Two keys in a row",
        body: "desk[\"Ada\"][\"role\"] walks into Ada's record, then reads role. You can assign desk[\"Ada\"][\"role\"] = \"lead\" to update.",
        example: "print(desk[\"Ada\"][\"role\"])",
      },
      {
        type: "code",
        challenge: {
          id: "l42-read",
          title: "Inner field",
          concept: "nested dict",
          prompt: "Print Ada's role from the nested desk record.",
          briefing: "desk[\"Ada\"][\"role\"]",
          example: "print(desk[\"Ada\"][\"role\"])",
          starter: "desk = {\"Ada\": {\"role\": \"lead\", \"score\": 90}, \"Lin\": {\"role\": \"dev\", \"score\": 70}}\n",
          expected: "lead\n",
          solution:
            "desk = {\"Ada\": {\"role\": \"lead\", \"score\": 90}, \"Lin\": {\"role\": \"dev\", \"score\": 70}}\nprint(desk[\"Ada\"][\"role\"])",
          hints: ["desk[\"Ada\"]", "then [\"role\"]", "print that."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l42-write",
          title: "Promote Ada",
          concept: "nested assign",
          prompt: "Set Ada's role to director, then print that role.",
          briefing: "desk[\"Ada\"][\"role\"] = \"director\"",
          example: "desk[\"Ada\"][\"role\"] = \"director\"\nprint(desk[\"Ada\"][\"role\"])",
          starter: "desk = {\"Ada\": {\"role\": \"lead\", \"score\": 90}}\n",
          expected: "director\n",
          solution:
            "desk = {\"Ada\": {\"role\": \"lead\", \"score\": 90}}\ndesk[\"Ada\"][\"role\"] = \"director\"\nprint(desk[\"Ada\"][\"role\"])",
          hints: ["desk[\"Ada\"][\"role\"] = \"director\"", "Then print it.", "Match lowercase director."],
        },
      },
    ],
  },
  {
    id: 43,
    title: "Step Rail",
    job: "Grandmaster",
    difficulty: "Medium / Hard",
    description: "range can take a step so it skips numbers.",
    objective: "Print even numbers using range with a step.",
    rewardCoins: 4600,
    rewardXp: 1800,
    unlockRewardId: "step-rail",
    unlockReward: "Step Rail",
    careerUnlock: "director",
    chapter: "studio",
    timeLimitSec: 70,
    steps: [
      {
        type: "brief",
        title: "Three arguments",
        body: "range(start, stop, step). range(0, 8, 2) is 0, 2, 4, 6 — stop is still excluded. Negative steps count down.",
        example: "for i in range(0, 8, 2):\n    print(i)",
      },
      {
        type: "code",
        challenge: {
          id: "l43-evens",
          title: "Skip by two",
          concept: "range step",
          prompt: "Print 0, 2, 4, 6 using range with a step of 2. Stop before 8.",
          briefing: "range(0, 8, 2)",
          example: "for i in range(0, 8, 2):\n    print(i)",
          starter: "",
          expected: "0\n2\n4\n6\n",
          solution: "for i in range(0, 8, 2):\n    print(i)",
          hints: ["range(0, 8, 2)", "Stop is 8, last printed is 6.", "for i in ...: print(i)"],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l43-down",
          title: "Count down",
          concept: "negative step",
          prompt: "Print 5, 4, 3, 2, 1 using range with a negative step. Stop before 0.",
          briefing: "range(5, 0, -1)",
          example: "for i in range(5, 0, -1):\n    print(i)",
          starter: "",
          expected: "5\n4\n3\n2\n1\n",
          solution: "for i in range(5, 0, -1):\n    print(i)",
          hints: ["range(5, 0, -1)", "0 is the stop, not printed.", "print(i) in the loop."],
        },
      },
    ],
  },
  {
    id: 44,
    title: "Mirror Glass",
    job: "Grandmaster",
    difficulty: "Medium / Hard",
    description: "[::-1] reverses a string or a list.",
    objective: "Mirror a word and a list.",
    rewardCoins: 4700,
    rewardXp: 1850,
    unlockRewardId: "mirror-glass",
    unlockReward: "Mirror Glass",
    careerUnlock: "director",
    chapter: "studio",
    steps: [
      {
        type: "brief",
        title: "Step of -1",
        body: "\"Python\"[::-1] is nohtyP. [1, 2, 3][::-1] is [3, 2, 1]. The empty start and end mean “the whole thing”, walking backwards.",
        example: "print(\"Python\"[::-1])\nprint([1, 2, 3][::-1])",
      },
      {
        type: "code",
        challenge: {
          id: "l44-str",
          title: "Mirror the name",
          concept: "reverse slice",
          prompt: "Print Python reversed with a slice.",
          briefing: "[::-1] on the string.",
          example: "print(\"Python\"[::-1])",
          starter: "",
          expected: "nohtyP\n",
          solution: "print(\"Python\"[::-1])",
          hints: ["\"Python\"[::-1]", "Capitals stay on the same letters.", "P ends up last."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l44-list",
          title: "Flip the list",
          concept: "reverse slice",
          prompt: "Print [1, 2, 3] reversed with a slice. Do not use reverse().",
          briefing: "[1, 2, 3][::-1] returns a new list.",
          example: "print([1, 2, 3][::-1])",
          starter: "",
          expected: "[3, 2, 1]\n",
          solution: "print([1, 2, 3][::-1])",
          hints: ["[::-1]", "Print the slice.", "[3, 2, 1]"],
        },
      },
    ],
  },
  {
    id: 45,
    title: "Accum Forge",
    job: "Grandmaster",
    difficulty: "Hard",
    description: "Start with empty text. Add a piece each time the loop runs.",
    objective: "Build a joined string without using join().",
    rewardCoins: 4800,
    rewardXp: 1900,
    unlockRewardId: "accum-forge",
    unlockReward: "Accum Forge",
    careerUnlock: "director",
    chapter: "studio",
    steps: [
      {
        type: "brief",
        title: "The running box",
        body: "out = \"\" then out = out + x builds a longer string. A space goes in as its own piece if you want gaps. Print once after the loop.",
        example: "out = \"\"\nfor w in words:\n    out = out + w\nprint(out)",
      },
      {
        type: "code",
        challenge: {
          id: "l45-glue",
          title: "Smash together",
          concept: "accumulator",
          prompt: "words is go, team. Start out as empty. Add each word onto out. Print out once after the loop. Result: goteam",
          briefing: "No spaces. Concatenate in the loop, print after.",
          example: "out = \"\"\nfor w in words:\n    out = out + w\nprint(out)",
          starter: "words = [\"go\", \"team\"]\n",
          expected: "goteam\n",
          solution: "words = [\"go\", \"team\"]\nout = \"\"\nfor w in words:\n    out = out + w\nprint(out)",
          hints: ["out = \"\"", "out = out + w", "print(out) after the loop"],
        },
      },
    ],
  },
  {
    id: 46,
    title: "Helper Link",
    job: "Grandmaster",
    difficulty: "Hard",
    description: "One function can call another. Small tools stack.",
    objective: "Write double, then twice, and print twice(5).",
    rewardCoins: 5000,
    rewardXp: 2000,
    unlockRewardId: "helper-link",
    unlockReward: "Helper Link",
    careerUnlock: "grandmaster",
    chapter: "studio",
    steps: [
      {
        type: "brief",
        title: "Call down the stack",
        body: "twice(n) can return double(n) + double(n), or simply 2 * double(n). Define double first so twice can see it.",
        example: "def double(n):\n    return n * 2\ndef twice(n):\n    return double(n) + double(n)",
      },
      {
        type: "code",
        challenge: {
          id: "l46-link",
          title: "Stacked tools",
          concept: "function calls function",
          prompt: "Write double(n) that returns n * 2. Write twice(n) that returns double(n) + double(n). Print twice(5).",
          briefing: "5 doubled is 10. 10 + 10 is 20.",
          example: "def double(n):\n    return n * 2",
          starter: "def double(n):\n    return n\n",
          expected: "20\n",
          solution:
            "def double(n):\n    return n * 2\ndef twice(n):\n    return double(n) + double(n)\nprint(twice(5))",
          hints: ["return n * 2", "twice returns double(n) + double(n)", "print(twice(5))"],
        },
      },
    ],
  },
  {
    id: 47,
    title: "Studio Report",
    job: "Grandmaster",
    difficulty: "Hard",
    description: "A function reads a roster and writes one labeled line.",
    objective: "Write line(name, score) and print two reports.",
    rewardCoins: 5200,
    rewardXp: 2100,
    unlockRewardId: "studio-report",
    unlockReward: "Studio Report",
    careerUnlock: "grandmaster",
    chapter: "studio",
    steps: [
      {
        type: "brief",
        title: "One shape, many calls",
        body: "line(name, score) returns name + \": \" + str(score). Convert the number. Call it twice to print two people.",
        example: "def line(name, score):\n    return name + \": \" + str(score)",
      },
      {
        type: "code",
        challenge: {
          id: "l47-line",
          title: "Two badges",
          concept: "format helper",
          prompt: "Write line(name, score) that returns name, then \": \", then the score as text. Print line(\"Ada\", 90) and line(\"Kai\", 70).",
          briefing: "Two lines of output. Space after the colon.",
          example: "print(line(\"Ada\", 90))",
          starter: "def line(name, score):\n    return name\n",
          expected: "Ada: 90\nKai: 70\n",
          solution:
            "def line(name, score):\n    return name + \": \" + str(score)\nprint(line(\"Ada\", 90))\nprint(line(\"Kai\", 70))",
          hints: ["str(score)", "\": \" has a colon and a space", "Print both calls."],
        },
      },
    ],
  },
  {
    id: 48,
    title: "Even Filter",
    job: "Grandmaster",
    difficulty: "Hard",
    description: "Walk a list. Print only the even numbers.",
    objective: "Filter with % before the clock hits zero.",
    rewardCoins: 5400,
    rewardXp: 2200,
    unlockRewardId: "even-filter",
    unlockReward: "Even Filter",
    careerUnlock: "grandmaster",
    chapter: "studio",
    timeLimitSec: 80,
    steps: [
      {
        type: "brief",
        title: "Keep the evens",
        body: "for n in nums: if n % 2 == 0: print(n). Indent twice. Odds are skipped, not deleted.",
        example: "for n in nums:\n    if n % 2 == 0:\n        print(n)",
      },
      {
        type: "code",
        challenge: {
          id: "l48-even",
          title: "Evens only",
          concept: "filter loop",
          prompt: "nums is [1, 4, 7, 8, 3, 10]. Print only the even numbers, each on its own line, in order.",
          briefing: "4, 8, 10.",
          example: "for n in nums:\n    if n % 2 == 0:\n        print(n)",
          starter: "nums = [1, 4, 7, 8, 3, 10]\n",
          expected: "4\n8\n10\n",
          solution: "nums = [1, 4, 7, 8, 3, 10]\nfor n in nums:\n    if n % 2 == 0:\n        print(n)",
          hints: ["for n in nums:", "if n % 2 == 0:", "print(n)"],
        },
      },
    ],
  },
  {
    id: 49,
    title: "Default Key",
    job: "Grandmaster",
    difficulty: "Hard",
    description: "get(key, fallback) returns the fallback instead of crashing.",
    objective: "Look up a missing city with a default.",
    rewardCoins: 5600,
    rewardXp: 2300,
    unlockRewardId: "default-key",
    unlockReward: "Default Key",
    careerUnlock: "grandmaster",
    chapter: "studio",
    steps: [
      {
        type: "brief",
        title: "The second argument",
        body: "user.get(\"city\", \"unknown\") returns unknown when city is missing. user[\"city\"] would raise KeyError. Use get when the key might not exist.",
        example: "print(user.get(\"city\", \"unknown\"))",
      },
      {
        type: "code",
        challenge: {
          id: "l49-get",
          title: "Fallback city",
          concept: "get default",
          prompt: "user has a name but no city. Print user.get(\"city\", \"unknown\"), then print user.get(\"name\", \"unknown\").",
          briefing: "Missing city → unknown. Present name → Ada.",
          example: "print(user.get(\"city\", \"unknown\"))",
          starter: "user = {\"name\": \"Ada\"}\n",
          expected: "unknown\nAda\n",
          solution: "user = {\"name\": \"Ada\"}\nprint(user.get(\"city\", \"unknown\"))\nprint(user.get(\"name\", \"unknown\"))",
          hints: ["get(\"city\", \"unknown\")", "get(\"name\", \"unknown\")", "Two prints."],
        },
      },
    ],
  },
  {
    id: 50,
    title: "Grandmaster Championship",
    job: "Grandmaster",
    difficulty: "Expert",
    description: "Grandmaster checkpoint. Helpers, filters, nested records — under the clock. The course continues after this.",
    objective: "Clear every stage. Claim the Grandmaster Crown. Then keep climbing.",
    rewardCoins: 12000,
    rewardXp: 4000,
    unlockRewardId: "grandmaster-crown",
    unlockReward: "Grandmaster Crown",
    careerUnlock: "grandmaster",
    chapter: "studio",
    timeLimitSec: 200,
    championship: true,
    steps: [
      {
        type: "brief",
        title: "The whole career",
        body: "Stage 1: a helper that classifies. Stage 2: walk nested scores. Stage 3: write a labeled report from a list. Same laws: colons, indents, quotes, print.",
        example: "def stamp(n):\n    if n % 2 == 0:\n        return \"EVEN\"\n    return \"ODD\"",
      },
      {
        type: "code",
        challenge: {
          id: "l50-stamp",
          title: "Stage 1 — Stamp",
          concept: "function + %",
          prompt: "Write stamp(n) that returns EVEN if n is even, else ODD. Print stamp(8) then stamp(7).",
          briefing: "Two lines: EVEN then ODD.",
          example: "print(stamp(8))\nprint(stamp(7))",
          starter: "def stamp(n):\n    return n\n",
          expected: "EVEN\nODD\n",
          solution:
            "def stamp(n):\n    if n % 2 == 0:\n        return \"EVEN\"\n    return \"ODD\"\nprint(stamp(8))\nprint(stamp(7))",
          hints: ["if n % 2 == 0: return \"EVEN\"", "return \"ODD\"", "Print both calls."],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l50-nested",
          title: "Stage 2 — Nested scores",
          concept: "nested dict + if",
          prompt: "desk maps names to records with a score. Print each name whose score is at least 80, in dictionary order.",
          briefing: "Ada 90 and Kai 88 pass. Lin 70 does not. Read desk[name][\"score\"].",
          example: "for name in desk:\n    if desk[name][\"score\"] >= 80:\n        print(name)",
          starter: "desk = {\"Ada\": {\"score\": 90}, \"Lin\": {\"score\": 70}, \"Kai\": {\"score\": 88}}\n",
          expected: "Ada\nKai\n",
          solution:
            "desk = {\"Ada\": {\"score\": 90}, \"Lin\": {\"score\": 70}, \"Kai\": {\"score\": 88}}\nfor name in desk:\n    if desk[name][\"score\"] >= 80:\n        print(name)",
          hints: ["for name in desk:", "if desk[name][\"score\"] >= 80:", "print(name)"],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l50-report",
          title: "Stage 3 — Final report",
          concept: "helpers + builtins",
          prompt: "Write report(nums) that returns max= then the max, then a space, then even= then how many even numbers. Print report([1, 4, 8, 3]).",
          briefing: "max is 8. Evens are 4 and 8, so even=2. Shape: max=8 even=2",
          example: "return \"max=\" + str(max(nums)) + \" even=\" + str(c)",
          starter: "def report(nums):\n    return \"\"\n",
          expected: "max=8 even=2\n",
          solution:
            "def report(nums):\n    c = 0\n    for n in nums:\n        if n % 2 == 0:\n            c += 1\n    return \"max=\" + str(max(nums)) + \" even=\" + str(c)\nprint(report([1, 4, 8, 3]))",
          hints: [
            "Count evens with % 2 == 0",
            "str(max(nums)) and str(c)",
            "print(report([1, 4, 8, 3]))",
          ],
        },
      },
    ],
  },
];
