import type { LevelDef } from "./types.ts";
import { LEVELS_PLUS } from "./levels-plus.ts";
import { LEVELS_PRO } from "./levels-pro.ts";

const CORE: LevelDef[] = [
  {
    id: 1,
    title: "Rookie Orientation",
    job: "Trainee",
    difficulty: "Easy",
    description: "Learn how a mission works, then write your first Python line.",
    objective: "Wait for the signal, then print a greeting.",
    rewardCoins: 500,
    rewardXp: 100,
    unlockRewardId: "trainee-badge",
    unlockReward: "Trainee Badge",
    careerUnlock: "trainee",
    chapter: "foundations",
    steps: [
      {
        type: "brief",
        title: "How missions work",
        body: "Each mission has a goal, a Python briefing, and a reward. Follow the steps. If your code is wrong, Jarvis explains the mistake and the fix — not just “error”.",
      },
      {
        type: "reaction",
        title: "Step 1 — Wait for the signal",
        body: "Stay ready. When GO appears, tap the action button. Too early fails the check.",
      },
      {
        type: "brief",
        title: "Step 2 — Python talks with print()",
        body: "print() is a function. A function is a tool you call with parentheses. The text inside quotes is a string — characters Python should treat as words, not as a name.",
        example: "print(\"Hello\")\n# The screen shows: Hello",
      },
      {
        type: "code",
        challenge: {
          id: "l1-hello",
          title: "Step 3 — Your first program",
          concept: "print() and strings",
          prompt: "Print exactly this greeting, including the comma and capital letters:",
          briefing:
            "Quotes wrap the message so Python does not look for a variable named Hello. print() then shows the message. The quotes themselves do not appear on the screen.",
          example: "print(\"Hello, Jarvis\")",
          starter: "# Type your line below.\n",
          expected: "Hello, Jarvis\n",
          solution: "print(\"Hello, Jarvis\")",
          hints: [
            "Use print( ) with parentheses.",
            "Put Hello, Jarvis inside quotes.",
            "Match capitals: Hello, Jarvis",
          ],
        },
      },
    ],
  },
  {
    id: 2,
    title: "First Assignment",
    job: "Junior Associate",
    difficulty: "Easy / Medium",
    description: "Choose the valid Python, then store values in variables.",
    objective: "Pass the decision cards and print a calculated result.",
    rewardCoins: 900,
    rewardXp: 150,
    unlockRewardId: "junior-desk",
    unlockReward: "Junior Desk",
    careerUnlock: "junior",
    chapter: "foundations",
    steps: [
      {
        type: "brief",
        title: "Variables store values",
        body: "A variable is a labeled box. name = \"Ada\" puts the string Ada in the box called name. After that, print(name) shows Ada — no quotes — because you printed the box, not the word name.",
        example: "name = \"Ada\"\nprint(name)\n# Ada",
      },
      {
        type: "choice",
        concept: "Assignment vs text",
        question: "Which line correctly stores the text Ada in a variable?",
        options: [
          {
            id: "a",
            label: "name = Ada",
            correct: false,
            explain: "Ada without quotes is treated as another variable. Python will look for a box named Ada and fail.",
          },
          {
            id: "b",
            label: "name = \"Ada\"",
            correct: true,
            explain: "Quotes make Ada a string. The box name now holds that text.",
          },
          {
            id: "c",
            label: "name == \"Ada\"",
            correct: false,
            explain: "== asks a yes/no question. It does not store anything. = stores. == compares.",
          },
        ],
      },
      {
        type: "choice",
        concept: "What print shows",
        question: "What does print(3 + 2) show?",
        options: [
          {
            id: "a",
            label: "3 + 2",
            correct: false,
            explain: "Without quotes, 3 + 2 is math. Python adds first, then prints the result.",
          },
          {
            id: "b",
            label: "5",
            correct: true,
            explain: "Numbers without quotes are numbers. + adds them. print shows 5.",
          },
          {
            id: "c",
            label: "\"32\"",
            correct: false,
            explain: "Sticking 3 and 2 together happens with strings: print(\"3\" + \"2\") would show 32.",
          },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l2-vars",
          title: "Store and print",
          concept: "variables",
          prompt: "Create a variable called city with the text London, then print the variable (not the word in quotes).",
          briefing: "Assign with =. Print the name with no quotes around the name.",
          example: "city = \"London\"\nprint(city)",
          starter: "city = \"\"\n",
          expected: "London\n",
          solution: "city = \"London\"\nprint(city)",
          hints: [
            "Put London inside quotes on the right of =.",
            "Then print(city) — city has no quotes.",
            "If you print(\"city\") you will see the word city, not London.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l2-sum",
          title: "Payroll math",
          concept: "numbers",
          prompt: "base is 40. bonus is 15. Print the sum of base and bonus as a number.",
          briefing: "Numbers have no quotes. + adds them. print(base + bonus) calculates, then shows the result.",
          example: "print(40 + 15)",
          starter: "base = 40\nbonus = 15\n",
          expected: "55\n",
          solution: "base = 40\nbonus = 15\nprint(base + bonus)",
          hints: [
            "Do not quote the numbers.",
            "print(base + bonus)",
            "The screen should show 55 with no extra text.",
          ],
        },
      },
    ],
  },
  {
    id: 3,
    title: "Speed Mission",
    job: "Specialist",
    difficulty: "Medium",
    description: "Write correct conditions before the clock hits zero.",
    objective: "Finish every task before time runs out.",
    rewardCoins: 1500,
    rewardXp: 250,
    unlockRewardId: "specialist-outfit",
    unlockReward: "Specialist Outfit",
    careerUnlock: "specialist",
    chapter: "foundations",
    timeLimitSec: 75,
    steps: [
      {
        type: "brief",
        title: "if / else decides",
        body: "An if line asks a yes/no question. If the answer is True, Python runs the indented block. else runs when the answer is False. The if line must end with a colon, and the next line must be indented.",
        example: "if score >= 70:\n    print(\"PASS\")\nelse:\n    print(\"RETRY\")",
      },
      {
        type: "code",
        challenge: {
          id: "l3-if",
          title: "Gate check",
          concept: "if / else",
          prompt: "score is 82. If score is at least 70, print PASS. Otherwise print RETRY.",
          briefing: ">= means greater than or equal. PASS and RETRY are strings — wrap them in quotes. Indent the print lines.",
          example: "if score >= 70:\n    print(\"PASS\")",
          starter: "score = 82\n",
          expected: "PASS\n",
          solution: "score = 82\nif score >= 70:\n    print(\"PASS\")\nelse:\n    print(\"RETRY\")",
          hints: [
            "End the if line with a colon.",
            "Indent print with 4 spaces.",
            "print(\"PASS\") with quotes.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l3-compare",
          title: "True or False",
          concept: "comparisons",
          prompt: "Print the result of checking whether 9 is less than 4. It should print False.",
          briefing: "Comparisons produce True or False. print(9 < 4) shows False because 9 is not less than 4. Do not quote True/False — they are boolean values, not text.",
          example: "print(9 < 4)",
          starter: "",
          expected: "False\n",
          solution: "print(9 < 4)",
          hints: [
            "Use the < operator.",
            "print(9 < 4)",
            "False has a capital F — Python will print that if you compare correctly.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l3-branch",
          title: "Access level",
          concept: "if / else",
          prompt: "role is guest. If role equals admin, print OPEN. Otherwise print LOCKED.",
          briefing: "== compares two values. Strings must match exactly. guest is not admin, so the else branch should run.",
          example: "if role == \"admin\":\n    print(\"OPEN\")\nelse:\n    print(\"LOCKED\")",
          starter: "role = \"guest\"\n",
          expected: "LOCKED\n",
          solution: "role = \"guest\"\nif role == \"admin\":\n    print(\"OPEN\")\nelse:\n    print(\"LOCKED\")",
          hints: [
            "Compare with == not =.",
            "else: then indented print(\"LOCKED\")",
            "guest is not admin, so LOCKED is correct.",
          ],
        },
      },
    ],
  },
  {
    id: 4,
    title: "Executive Trial",
    job: "Manager",
    difficulty: "Hard",
    description: "Complete three list-and-loop objectives in order.",
    objective: "Build a list, walk it, then report its size.",
    rewardCoins: 2500,
    rewardXp: 400,
    unlockRewardId: "executive-office",
    unlockReward: "Executive Office",
    careerUnlock: "manager",
    chapter: "foundations",
    steps: [
      {
        type: "brief",
        title: "Lists and for-loops",
        body: "A list holds several values in order, inside square brackets. for item in list: runs the indented block once per value. len(list) counts how many items. Indexes start at 0 — the first item is items[0].",
        example: "items = [\"plan\", \"code\", \"test\"]\nfor item in items:\n    print(item)",
      },
      {
        type: "code",
        challenge: {
          id: "l4-list",
          title: "Objective 1 — The roster",
          concept: "lists",
          prompt: "Create a list called team with three strings: Ada, Lin, Kai. Print the list.",
          briefing: "Strings in a list still need quotes. print(team) shows the whole list with brackets and quotes — that is normal.",
          example: "team = [\"Ada\", \"Lin\", \"Kai\"]\nprint(team)",
          starter: "team = []\n",
          expected: "['Ada', 'Lin', 'Kai']\n",
          solution: "team = [\"Ada\", \"Lin\", \"Kai\"]\nprint(team)",
          hints: [
            "Three quoted names inside [ ].",
            "Separate them with commas.",
            "print(team) after you build it.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l4-loop",
          title: "Objective 2 — Walk the list",
          concept: "for loops",
          prompt: "Loop through tasks and print each item on its own line.",
          briefing: "for t in tasks: then indent print(t). The loop variable t becomes each item in turn. Do not print the whole list.",
          example: "for t in tasks:\n    print(t)",
          starter: "tasks = [\"plan\", \"code\", \"test\"]\n",
          expected: "plan\ncode\ntest\n",
          solution: "tasks = [\"plan\", \"code\", \"test\"]\nfor t in tasks:\n    print(t)",
          hints: [
            "for t in tasks:",
            "Indent print(t) with 4 spaces.",
            "You should see three lines, one word each.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l4-len",
          title: "Objective 3 — Headcount",
          concept: "len()",
          prompt: "Print how many items are in rooms using len().",
          briefing: "len(rooms) returns a number. print(len(rooms)) shows that number. Do not write 3 by hand — use len so the answer stays correct if the list changes.",
          example: "print(len(rooms))",
          starter: "rooms = [\"ops\", \"lab\", \"brief\", \"vault\"]\n",
          expected: "4\n",
          solution: "rooms = [\"ops\", \"lab\", \"brief\", \"vault\"]\nprint(len(rooms))",
          hints: [
            "len(rooms) counts items.",
            "print(len(rooms))",
            "The answer is 4.",
          ],
        },
      },
    ],
  },
  {
    id: 5,
    title: "Elite Championship",
    job: "Elite Professional",
    difficulty: "Hard",
    description: "Combine functions, loops, and conditions. Championship scoring is live.",
    objective: "Clear every stage before time expires.",
    rewardCoins: 5000,
    rewardXp: 750,
    unlockRewardId: "m8-apex",
    unlockReward: "M8 Apex",
    careerUnlock: "elite",
    chapter: "foundations",
    timeLimitSec: 120,
    championship: true,
    steps: [
      {
        type: "brief",
        title: "Functions package skill",
        body: "def name(args): creates a reusable tool. return sends a value back to the caller. print(greet(\"Elite\")) first runs greet, then prints whatever greet returned.",
        example: "def greet(name):\n    return \"Ready, \" + name\nprint(greet(\"Elite\"))",
      },
      {
        type: "code",
        challenge: {
          id: "l5-fn",
          title: "Stage 1 — Briefing call",
          concept: "functions + return",
          prompt: "Write greet(name) so it returns Ready, plus a space, plus name. Then print greet(\"Elite\").",
          briefing: "return does not print. print is separate. Join strings with +.",
          example: "def greet(name):\n    return \"Ready, \" + name",
          starter: "def greet(name):\n    return name\n",
          expected: "Ready, Elite\n",
          solution: "def greet(name):\n    return \"Ready, \" + name\nprint(greet(\"Elite\"))",
          hints: [
            "return \"Ready, \" + name",
            "Remember the comma and space after Ready.",
            "Call print(greet(\"Elite\")) under the function.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l5-filter",
          title: "Stage 2 — Clearance filter",
          concept: "loop + if",
          prompt: "scores holds exam results. Print only the scores that are at least 70, each on its own line.",
          briefing: "Loop every score. Inside the loop, if score >= 70, print it. Indent twice: once for the for, once for the if.",
          example: "for s in scores:\n    if s >= 70:\n        print(s)",
          starter: "scores = [55, 90, 70, 41, 88]\n",
          expected: "90\n70\n88\n",
          solution: "scores = [55, 90, 70, 41, 88]\nfor s in scores:\n    if s >= 70:\n        print(s)",
          hints: [
            "for s in scores:",
            "if s >= 70:",
            "print(s) indented under the if.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l5-total",
          title: "Stage 3 — Final tally",
          concept: "functions + loops",
          prompt: "Write total(nums) that adds every number in the list and returns the sum. Print total([10, 20, 30]).",
          briefing: "Start a box at 0. Loop, add each number, return the box. You may also use sum(nums).",
          example: "def total(nums):\n    s = 0\n    for n in nums:\n        s += n\n    return s",
          starter: "def total(nums):\n    return 0\n",
          expected: "60\n",
          solution: "def total(nums):\n    s = 0\n    for n in nums:\n        s += n\n    return s\nprint(total([10, 20, 30]))",
          hints: [
            "s = 0 then for n in nums: s += n",
            "return s",
            "print(total([10, 20, 30]))",
          ],
        },
      },
    ],
  },
  {
    id: 6,
    title: "String Lab",
    job: "Senior Engineer",
    difficulty: "Easy / Medium",
    description: "Join text together. Turn numbers into text with str().",
    objective: "Concatenate names, then build a labeled desk number.",
    rewardCoins: 1100,
    rewardXp: 300,
    unlockRewardId: "string-keys",
    unlockReward: "String Keys",
    careerUnlock: "elite",
    chapter: "strings",
    steps: [
      {
        type: "brief",
        title: "Strings glue with +",
        body: "+ on two strings pastes them. It does not add a space unless you put one in. Numbers cannot join text until you wrap them in str().",
        example: "print(\"Ada\" + \" \" + \"Lovelace\")\nprint(\"Desk \" + str(7))",
      },
      {
        type: "choice",
        concept: "str() vs quotes",
        question: "How do you turn the number 7 into the text \"7\"?",
        options: [
          {
            id: "a",
            label: "int(7)",
            correct: false,
            explain: "int() turns values into numbers. 7 is already a number.",
          },
          {
            id: "b",
            label: "str(7)",
            correct: true,
            explain: "str() makes a string from a number so it can join other text.",
          },
          {
            id: "c",
            label: "print(7)",
            correct: false,
            explain: "print shows 7 on the screen, but the value is still a number — you cannot add it to a string.",
          },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l6-concat",
          title: "Nameplate",
          concept: "string +",
          prompt: "first is Ada. last is Lovelace. Print the full name with one space in the middle.",
          briefing: "Join with +. Put a space string between the two names.",
          example: "print(first + \" \" + last)",
          starter: "first = \"Ada\"\nlast = \"Lovelace\"\n",
          expected: "Ada Lovelace\n",
          solution: "first = \"Ada\"\nlast = \"Lovelace\"\nprint(first + \" \" + last)",
          hints: [
            "Use + between the pieces.",
            "The space is its own string: \" \"",
            "print(first + \" \" + last)",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l6-str",
          title: "Desk label",
          concept: "str()",
          prompt: "n is 7. Print Desk 7 using the variable n — do not type the digit 7 inside the string.",
          briefing: "Python refuses \"Desk \" + n because one side is text and the other is a number. Convert with str(n).",
          example: "print(\"Desk \" + str(n))",
          starter: "n = 7\n",
          expected: "Desk 7\n",
          solution: "n = 7\nprint(\"Desk \" + str(n))",
          hints: [
            "str(n) turns 7 into \"7\".",
            "\"Desk \" has a trailing space.",
            "print(\"Desk \" + str(n))",
          ],
        },
      },
    ],
  },
  {
    id: 7,
    title: "Case File",
    job: "Senior Engineer",
    difficulty: "Easy / Medium",
    description: "Change letter case and trim leftover spaces.",
    objective: "Use upper, lower, and strip.",
    rewardCoins: 1200,
    rewardXp: 350,
    unlockRewardId: "case-file",
    unlockReward: "Case File",
    careerUnlock: "senior",
    chapter: "strings",
    steps: [
      {
        type: "brief",
        title: "Methods sit after a dot",
        body: "text.upper() is a method — a function that belongs to a value. The empty () still matter. Forgetting them is a common miss. strip() removes spaces from both ends, not from the middle.",
        example: "print(\"jarvis\".upper())\nprint(\"  Ada  \".strip())",
      },
      {
        type: "choice",
        concept: "methods need ()",
        question: "What does print(\"Hi\".lower()) show?",
        options: [
          {
            id: "a",
            label: "Hi",
            correct: false,
            explain: "lower() changes every letter. H becomes h.",
          },
          {
            id: "b",
            label: "hi",
            correct: true,
            explain: "lower() returns a new string with all lowercase letters.",
          },
          {
            id: "c",
            label: "HI",
            correct: false,
            explain: "That would be upper(), the opposite method.",
          },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l7-upper",
          title: "Loud callsign",
          concept: "upper()",
          prompt: "Print jarvis in all capitals using a string method.",
          briefing: "Call upper on the string. Parentheses are required.",
          example: "print(\"jarvis\".upper())",
          starter: "",
          expected: "JARVIS\n",
          solution: "print(\"jarvis\".upper())",
          hints: [
            "\"jarvis\".upper()",
            "Do not forget ().",
            "Wrap the call in print.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l7-strip",
          title: "Clean badge",
          concept: "strip()",
          prompt: "name has extra spaces. Print the cleaned name with no leading or trailing spaces.",
          briefing: "strip() returns a new string. It does not change name unless you assign it.",
          example: "print(name.strip())",
          starter: "name = \"  Ada  \"\n",
          expected: "Ada\n",
          solution: "name = \"  Ada  \"\nprint(name.strip())",
          hints: [
            "name.strip()",
            "Print the result of strip, not name itself.",
            "The output is Ada with no spaces.",
          ],
        },
      },
    ],
  },
  {
    id: 8,
    title: "Character Lens",
    job: "Staff Engineer",
    difficulty: "Medium",
    description: "Read one character at a time. Indexes start at zero.",
    objective: "Print the first letter, the last letter, and a string length.",
    rewardCoins: 1300,
    rewardXp: 400,
    unlockRewardId: "char-lens",
    unlockReward: "Character Lens",
    careerUnlock: "senior",
    chapter: "strings",
    steps: [
      {
        type: "brief",
        title: "Indexes start at 0",
        body: "word[0] is the first character. word[-1] is the last. len(word) counts characters, including spaces.",
        example: "word = \"Python\"\nprint(word[0])  # P\nprint(word[-1]) # n",
      },
      {
        type: "choice",
        concept: "zero-based index",
        question: "In the string \"code\", which index is the letter d?",
        options: [
          { id: "a", label: "1", correct: false, explain: "Index 1 is o. Counting starts at 0: c=0, o=1, d=2, e=3." },
          { id: "b", label: "2", correct: true, explain: "c=0, o=1, d=2. The third letter lives at index 2." },
          { id: "c", label: "3", correct: false, explain: "Index 3 is e, the last letter." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l8-first-last",
          title: "Bookends",
          concept: "string index",
          prompt: "word is Python. Print the first character, then the last character, each on its own line.",
          briefing: "Use [0] and [-1]. Each print makes a new line.",
          example: "print(word[0])\nprint(word[-1])",
          starter: "word = \"Python\"\n",
          expected: "P\nn\n",
          solution: "word = \"Python\"\nprint(word[0])\nprint(word[-1])",
          hints: [
            "First letter: word[0]",
            "Last letter: word[-1]",
            "Two print calls.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l8-len",
          title: "Letter count",
          concept: "len(str)",
          prompt: "Print how many characters are in the string career using len().",
          briefing: "len works on strings the same way it works on lists.",
          example: "print(len(\"career\"))",
          starter: "",
          expected: "6\n",
          solution: "print(len(\"career\"))",
          hints: [
            "len(\"career\")",
            "Wrap it in print.",
            "The answer is 6.",
          ],
        },
      },
    ],
  },
  {
    id: 9,
    title: "Logic Core",
    job: "Staff Engineer",
    difficulty: "Medium",
    description: "Combine True and False with and, or, and not.",
    objective: "Print boolean results from comparisons and logic.",
    rewardCoins: 1400,
    rewardXp: 450,
    unlockRewardId: "logic-core",
    unlockReward: "Logic Core",
    careerUnlock: "staff",
    chapter: "logic",
    steps: [
      {
        type: "brief",
        title: "and / or / not",
        body: "and is True only if both sides are True. or is True if at least one side is True. not flips True to False. Comparisons like >= produce booleans you can combine.",
        example: "print(True and False)  # False\nprint(age >= 18 and age < 65)",
      },
      {
        type: "choice",
        concept: "not",
        question: "What does print(not True) show?",
        options: [
          { id: "a", label: "True", correct: false, explain: "not flips the value. The opposite of True is False." },
          { id: "b", label: "False", correct: true, explain: "not True is False. not False is True." },
          { id: "c", label: "not True", correct: false, explain: "Python evaluates the expression, then prints the boolean result." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l9-and",
          title: "Both gates",
          concept: "and",
          prompt: "Print the result of True and False.",
          briefing: "Do not quote True or False. They are keywords.",
          example: "print(True and False)",
          starter: "",
          expected: "False\n",
          solution: "print(True and False)",
          hints: [
            "True and False — no quotes.",
            "and needs both sides True to be True.",
            "The output is False.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l9-range",
          title: "Working age",
          concept: "combined compare",
          prompt: "age is 20. Print whether age is at least 18 and also less than 65.",
          briefing: "Chain with and. Python will print True or False.",
          example: "print(age >= 18 and age < 65)",
          starter: "age = 20\n",
          expected: "True\n",
          solution: "age = 20\nprint(age >= 18 and age < 65)",
          hints: [
            "age >= 18",
            "and age < 65",
            "Print the whole comparison.",
          ],
        },
      },
    ],
  },
  {
    id: 10,
    title: "Branch Map",
    job: "Lead Engineer",
    difficulty: "Medium / Hard",
    description: "elif picks the first matching branch. The clock is live.",
    objective: "Grade a score and classify a temperature before time runs out.",
    rewardCoins: 1600,
    rewardXp: 500,
    unlockRewardId: "branch-map",
    unlockReward: "Branch Map",
    careerUnlock: "staff",
    chapter: "logic",
    timeLimitSec: 90,
    steps: [
      {
        type: "brief",
        title: "elif is the next door",
        body: "Python checks if, then each elif, then else. The first True branch runs. Later branches are skipped even if they would also be True. Order matters.",
        example: "if score >= 90:\n    print(\"A\")\nelif score >= 70:\n    print(\"B\")\nelse:\n    print(\"C\")",
      },
      {
        type: "code",
        challenge: {
          id: "l10-grade",
          title: "Letter grade",
          concept: "elif",
          prompt: "score is 91. If it is at least 90 print A. Else if it is at least 70 print B. Otherwise print C.",
          briefing: "91 matches the first branch. Put colons on every header. Indent each print.",
          example: "if score >= 90:\n    print(\"A\")",
          starter: "score = 91\n",
          expected: "A\n",
          solution:
            "score = 91\nif score >= 90:\n    print(\"A\")\nelif score >= 70:\n    print(\"B\")\nelse:\n    print(\"C\")",
          hints: [
            "if score >= 90:",
            "elif score >= 70:",
            "else: print(\"C\")",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l10-temp",
          title: "Climate check",
          concept: "elif",
          prompt: "temp is 12. If temp is under 10 print COLD. Else if temp is under 25 print OK. Otherwise print HOT.",
          briefing: "12 is not < 10, but it is < 25, so OK.",
          example: "if temp < 10:\n    print(\"COLD\")",
          starter: "temp = 12\n",
          expected: "OK\n",
          solution:
            "temp = 12\nif temp < 10:\n    print(\"COLD\")\nelif temp < 25:\n    print(\"OK\")\nelse:\n    print(\"HOT\")",
          hints: [
            "if temp < 10:",
            "elif temp < 25:",
            "12 is OK, not COLD.",
          ],
        },
      },
    ],
  },
  {
    id: 11,
    title: "While Engine",
    job: "Lead Engineer",
    difficulty: "Medium",
    description: "A while loop repeats until its condition becomes False.",
    objective: "Count up, then count down. Always change the loop variable.",
    rewardCoins: 1700,
    rewardXp: 550,
    unlockRewardId: "while-engine",
    unlockReward: "While Engine",
    careerUnlock: "lead",
    chapter: "loops",
    steps: [
      {
        type: "brief",
        title: "while needs an exit",
        body: "while condition: repeats the indented block as long as the condition is True. If you forget to change the variable, the loop never ends — Jarvis will stop it and tell you.",
        example: "i = 1\nwhile i <= 3:\n    print(i)\n    i += 1",
      },
      {
        type: "choice",
        concept: "infinite loops",
        question: "Why must you change i inside while i <= 3?",
        options: [
          {
            id: "a",
            label: "So the condition eventually becomes False",
            correct: true,
            explain: "If i stays 1 forever, i <= 3 stays True and the loop never stops.",
          },
          {
            id: "b",
            label: "Python requires += on every line",
            correct: false,
            explain: "+= is just one way to change a number. The requirement is that the condition can become False.",
          },
          {
            id: "c",
            label: "print() only works after +=",
            correct: false,
            explain: "print works any time. The increment is about ending the loop, not about printing.",
          },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l11-up",
          title: "Count up",
          concept: "while",
          prompt: "Start i at 1. While i is at most 3, print i, then add 1.",
          briefing: "The increment belongs inside the loop, indented.",
          example: "while i <= 3:\n    print(i)\n    i += 1",
          starter: "i = 1\n",
          expected: "1\n2\n3\n",
          solution: "i = 1\nwhile i <= 3:\n    print(i)\n    i += 1",
          hints: [
            "while i <= 3:",
            "print(i) then i += 1",
            "Both lines indented.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l11-down",
          title: "Countdown",
          concept: "while",
          prompt: "n starts at 5. While n is greater than 0, print n, then subtract 1.",
          briefing: "n -= 1 is the same as n = n - 1. Stop when n is 0 so 0 is not printed.",
          example: "while n > 0:\n    print(n)\n    n -= 1",
          starter: "n = 5\n",
          expected: "5\n4\n3\n2\n1\n",
          solution: "n = 5\nwhile n > 0:\n    print(n)\n    n -= 1",
          hints: [
            "while n > 0:",
            "print(n)",
            "n -= 1",
          ],
        },
      },
    ],
  },
  {
    id: 12,
    title: "Range Rail",
    job: "Principal Engineer",
    difficulty: "Medium",
    description: "range() builds the numbers a for-loop walks.",
    objective: "Print range(4) and range(2, 6).",
    rewardCoins: 1800,
    rewardXp: 600,
    unlockRewardId: "range-rail",
    unlockReward: "Range Rail",
    careerUnlock: "lead",
    chapter: "loops",
    steps: [
      {
        type: "brief",
        title: "range stops before the end",
        body: "range(4) is 0, 1, 2, 3 — it does not include 4. range(2, 6) starts at 2 and stops before 6. You almost always use range inside a for loop.",
        example: "for i in range(4):\n    print(i)",
      },
      {
        type: "choice",
        concept: "range stop",
        question: "Which numbers does range(3) produce?",
        options: [
          { id: "a", label: "1, 2, 3", correct: false, explain: "range starts at 0 unless you say otherwise. It never includes the stop value." },
          { id: "b", label: "0, 1, 2", correct: true, explain: "Start 0, stop before 3." },
          { id: "c", label: "0, 1, 2, 3", correct: false, explain: "That would be range(4). The 3 is the stop, not a value." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l12-range",
          title: "Zero to three",
          concept: "range",
          prompt: "Loop with range(4) and print each number on its own line.",
          briefing: "for i in range(4): then print(i).",
          example: "for i in range(4):\n    print(i)",
          starter: "",
          expected: "0\n1\n2\n3\n",
          solution: "for i in range(4):\n    print(i)",
          hints: [
            "for i in range(4):",
            "Indent print(i).",
            "Four lines: 0 through 3.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l12-span",
          title: "Two to five",
          concept: "range(start, stop)",
          prompt: "Print every integer from 2 up to but not including 6.",
          briefing: "range(2, 6) does that in one call.",
          example: "for i in range(2, 6):\n    print(i)",
          starter: "",
          expected: "2\n3\n4\n5\n",
          solution: "for i in range(2, 6):\n    print(i)",
          hints: [
            "range(2, 6)",
            "Stop is 6, last printed is 5.",
            "for i in range(2, 6): print(i)",
          ],
        },
      },
    ],
  },
  {
    id: 13,
    title: "Nest Grid",
    job: "Principal Engineer",
    difficulty: "Hard",
    description: "A loop inside a loop. The inner one finishes every time the outer ticks.",
    objective: "Print a multiplication grid before the timer ends.",
    rewardCoins: 2000,
    rewardXp: 650,
    unlockRewardId: "nest-grid",
    unlockReward: "Nest Grid",
    careerUnlock: "principal",
    chapter: "loops",
    timeLimitSec: 80,
    steps: [
      {
        type: "brief",
        title: "Inner loop runs fully",
        body: "For each value of x, y walks its whole list. Four prints from two lists of two. Indent the inner for one extra level.",
        example: "for x in [1, 2]:\n    for y in [3, 4]:\n        print(x * y)",
      },
      {
        type: "code",
        challenge: {
          id: "l13-grid",
          title: "Product grid",
          concept: "nested for",
          prompt: "x walks [1, 2]. For each x, y walks [3, 4]. Print x * y each time.",
          briefing: "Four lines: 3, 4, then 6, 8.",
          example: "for x in [1, 2]:\n    for y in [3, 4]:\n        print(x * y)",
          starter: "",
          expected: "3\n4\n6\n8\n",
          solution: "for x in [1, 2]:\n    for y in [3, 4]:\n        print(x * y)",
          hints: [
            "for x in [1, 2]:",
            "    for y in [3, 4]:",
            "        print(x * y)",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l13-filter",
          title: "High water",
          concept: "for + if",
          prompt: "nums is [3, 10, 7, 2]. Print only the numbers greater than 5, each on its own line.",
          briefing: "Loop, then if n > 5: print(n).",
          example: "for n in nums:\n    if n > 5:\n        print(n)",
          starter: "nums = [3, 10, 7, 2]\n",
          expected: "10\n7\n",
          solution: "nums = [3, 10, 7, 2]\nfor n in nums:\n    if n > 5:\n        print(n)",
          hints: [
            "for n in nums:",
            "if n > 5:",
            "print(n) under the if.",
          ],
        },
      },
    ],
  },
  {
    id: 14,
    title: "Index Desk",
    job: "Principal Engineer",
    difficulty: "Medium",
    description: "Read and replace a list item by position.",
    objective: "Print index 1, then overwrite index 0.",
    rewardCoins: 2100,
    rewardXp: 700,
    unlockRewardId: "index-badge",
    unlockReward: "Index Badge",
    careerUnlock: "principal",
    chapter: "structures",
    steps: [
      {
        type: "brief",
        title: "Replace, don't append",
        body: "nums[1] reads the second item. nums[0] = 99 replaces the first. You can only assign to an index that already exists — use append to grow the list.",
        example: "nums = [10, 20, 30]\nprint(nums[1])\nnums[0] = 99",
      },
      {
        type: "code",
        challenge: {
          id: "l14-read",
          title: "Second seat",
          concept: "list index",
          prompt: "nums is [10, 20, 30]. Print the item at index 1.",
          briefing: "Index 1 is the second value because counting starts at 0.",
          example: "print(nums[1])",
          starter: "nums = [10, 20, 30]\n",
          expected: "20\n",
          solution: "nums = [10, 20, 30]\nprint(nums[1])",
          hints: [
            "nums[1]",
            "That is 20, not 10.",
            "print(nums[1])",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l14-write",
          title: "Overwrite",
          concept: "item assignment",
          prompt: "Set the first item of nums to 99, then print the whole list.",
          briefing: "nums[0] = 99 mutates the list in place.",
          example: "nums[0] = 99\nprint(nums)",
          starter: "nums = [10, 20, 30]\n",
          expected: "[99, 20, 30]\n",
          solution: "nums = [10, 20, 30]\nnums[0] = 99\nprint(nums)",
          hints: [
            "nums[0] = 99",
            "print(nums) after the assignment.",
            "Brackets in the output are normal.",
          ],
        },
      },
    ],
  },
  {
    id: 15,
    title: "Append Bay",
    job: "Architect",
    difficulty: "Medium",
    description: "Grow a list with append. The method itself returns None.",
    objective: "Add a teammate, then count the box.",
    rewardCoins: 2200,
    rewardXp: 800,
    unlockRewardId: "append-bay",
    unlockReward: "Append Bay",
    careerUnlock: "principal",
    chapter: "structures",
    steps: [
      {
        type: "brief",
        title: "append mutates",
        body: "team.append(\"Lin\") adds Lin to the end. The call returns None — so print(team.append(\"Lin\")) would show None. Print the list after you append.",
        example: "team = [\"Ada\"]\nteam.append(\"Lin\")\nprint(team)",
      },
      {
        type: "choice",
        concept: "append return",
        question: "What does print(team.append(\"Lin\")) show?",
        options: [
          { id: "a", label: "Lin", correct: false, explain: "append does not return the new item. It returns None." },
          { id: "b", label: "None", correct: true, explain: "Most mutating list methods return None. Print the list afterwards if you want to see it." },
          { id: "c", label: "['Ada', 'Lin']", correct: false, explain: "That is what print(team) shows after append, not what append itself returns." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l15-append",
          title: "Hire Lin",
          concept: "append",
          prompt: "team starts as [\"Ada\"]. Append Lin, then print the list.",
          briefing: "Two steps: append, then print(team).",
          example: "team.append(\"Lin\")\nprint(team)",
          starter: "team = [\"Ada\"]\n",
          expected: "['Ada', 'Lin']\n",
          solution: "team = [\"Ada\"]\nteam.append(\"Lin\")\nprint(team)",
          hints: [
            "team.append(\"Lin\")",
            "Then print(team)",
            "Do not print the append call itself.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l15-grow",
          title: "Load the box",
          concept: "append + len",
          prompt: "box starts empty. Append 1, then append 2, then print how many items are in box.",
          briefing: "Two appends, then print(len(box)).",
          example: "box.append(1)\nbox.append(2)\nprint(len(box))",
          starter: "box = []\n",
          expected: "2\n",
          solution: "box = []\nbox.append(1)\nbox.append(2)\nprint(len(box))",
          hints: [
            "box.append(1)",
            "box.append(2)",
            "print(len(box))",
          ],
        },
      },
    ],
  },
  {
    id: 16,
    title: "Slice Glass",
    job: "Architect",
    difficulty: "Medium / Hard",
    description: "A slice is a window: start included, end excluded.",
    objective: "Slice a list and a string.",
    rewardCoins: 2300,
    rewardXp: 850,
    unlockRewardId: "slice-glass",
    unlockReward: "Slice Glass",
    careerUnlock: "architect",
    chapter: "structures",
    steps: [
      {
        type: "brief",
        title: "start:end",
        body: "items[1:3] takes indexes 1 and 2 — it stops before 3. Leaving the start empty means 0. Leaving the end empty means “to the last item”. Slicing a string returns a smaller string.",
        example: "letters = [\"a\", \"b\", \"c\", \"d\"]\nprint(letters[1:3])  # ['b', 'c']\nprint(\"Python\"[0:3])  # Pyt",
      },
      {
        type: "choice",
        concept: "half-open slice",
        question: "What does \"code\"[:2] produce?",
        options: [
          { id: "a", label: "cod", correct: false, explain: "[:2] is indexes 0 and 1, so co — it stops before 2." },
          { id: "b", label: "co", correct: true, explain: "Empty start means 0. End 2 is excluded. c=0, o=1." },
          { id: "c", label: "code", correct: false, explain: "That would be the whole string, slice [:] or [0:4]." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l16-list",
          title: "Middle pair",
          concept: "list slice",
          prompt: "letters is a, b, c, d. Print the slice from index 1 up to (not including) 3.",
          briefing: "letters[1:3] → b and c.",
          example: "print(letters[1:3])",
          starter: "letters = [\"a\", \"b\", \"c\", \"d\"]\n",
          expected: "['b', 'c']\n",
          solution: "letters = [\"a\", \"b\", \"c\", \"d\"]\nprint(letters[1:3])",
          hints: [
            "letters[1:3]",
            "End 3 is not included.",
            "print the slice.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l16-str",
          title: "Prefix",
          concept: "string slice",
          prompt: "Print the first three characters of Python using a slice.",
          briefing: "[0:3] on a string returns a string, not a list.",
          example: "print(\"Python\"[0:3])",
          starter: "",
          expected: "Pyt\n",
          solution: "print(\"Python\"[0:3])",
          hints: [
            "\"Python\"[0:3]",
            "P=0, y=1, t=2.",
            "Output is Pyt with no quotes.",
          ],
        },
      },
    ],
  },
  {
    id: 17,
    title: "Break Seal",
    job: "Architect",
    difficulty: "Hard",
    description: "break leaves the loop. continue skips one round.",
    objective: "Stop at 9. Skip even numbers.",
    rewardCoins: 2400,
    rewardXp: 900,
    unlockRewardId: "break-seal",
    unlockReward: "Break Seal",
    careerUnlock: "architect",
    chapter: "structures",
    steps: [
      {
        type: "brief",
        title: "Two exits",
        body: "break jumps out of the nearest loop immediately. continue jumps to the next item and skips the rest of this round. % is remainder — n % 2 == 0 means n is even.",
        example: "for n in nums:\n    if n == 9:\n        break\n    print(n)",
      },
      {
        type: "code",
        challenge: {
          id: "l17-break",
          title: "Stop at nine",
          concept: "break",
          prompt: "Loop [1, 2, 9, 4]. Print each number, but break when you see 9 so 9 and 4 are not printed.",
          briefing: "Check for 9 first, then print. Order matters.",
          example: "if n == 9:\n    break\nprint(n)",
          starter: "",
          expected: "1\n2\n",
          solution: "for n in [1, 2, 9, 4]:\n    if n == 9:\n        break\n    print(n)",
          hints: [
            "for n in [1, 2, 9, 4]:",
            "if n == 9: break",
            "print(n) after the if, same indent as the if.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l17-continue",
          title: "Odds only",
          concept: "continue",
          prompt: "Loop 1, 2, 3, 4. Skip even numbers with continue. Print the odd ones.",
          briefing: "if n % 2 == 0: continue. Then print(n).",
          example: "if n % 2 == 0:\n    continue\nprint(n)",
          starter: "",
          expected: "1\n3\n",
          solution: "for n in [1, 2, 3, 4]:\n    if n % 2 == 0:\n        continue\n    print(n)",
          hints: [
            "for n in [1, 2, 3, 4]:",
            "if n % 2 == 0: continue",
            "print(n)",
          ],
        },
      },
    ],
  },
  {
    id: 18,
    title: "Record Vault",
    job: "Distinguished Engineer",
    difficulty: "Medium / Hard",
    description: "A dictionary maps a key to a value. Look up with [key].",
    objective: "Read a name, then promote a role.",
    rewardCoins: 2600,
    rewardXp: 1000,
    unlockRewardId: "record-vault",
    unlockReward: "Record Vault",
    careerUnlock: "architect",
    chapter: "structures",
    steps: [
      {
        type: "brief",
        title: "Keys, not indexes",
        body: "A dict uses curly braces and colons: {\"name\": \"Ada\"}. Read with user[\"name\"]. Assign user[\"role\"] = \"architect\" to add or replace a key. Keys are usually strings.",
        example: "user = {\"name\": \"Ada\", \"role\": \"lead\"}\nprint(user[\"name\"])",
      },
      {
        type: "choice",
        concept: "dict syntax",
        question: "Which line creates a dictionary?",
        options: [
          { id: "a", label: "user = [\"name\", \"Ada\"]", correct: false, explain: "Square brackets make a list, not a mapping." },
          { id: "b", label: "user = {\"name\": \"Ada\"}", correct: true, explain: "Curly braces, quoted key, colon, value." },
          { id: "c", label: "user = (\"name\": \"Ada\")", correct: false, explain: "Parentheses group expressions. They do not make a dict." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l18-read",
          title: "Look up",
          concept: "dict index",
          prompt: "user has name Ada and role lead. Print the name.",
          briefing: "user[\"name\"] — the key is a string, so it needs quotes.",
          example: "print(user[\"name\"])",
          starter: "user = {\"name\": \"Ada\", \"role\": \"lead\"}\n",
          expected: "Ada\n",
          solution: "user = {\"name\": \"Ada\", \"role\": \"lead\"}\nprint(user[\"name\"])",
          hints: [
            "user[\"name\"]",
            "Quotes around the key.",
            "print that lookup.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l18-write",
          title: "Promote",
          concept: "dict assign",
          prompt: "Change user role to architect, then print the role.",
          briefing: "user[\"role\"] = \"architect\" writes the key.",
          example: "user[\"role\"] = \"architect\"\nprint(user[\"role\"])",
          starter: "user = {\"name\": \"Ada\", \"role\": \"lead\"}\n",
          expected: "architect\n",
          solution: "user = {\"name\": \"Ada\", \"role\": \"lead\"}\nuser[\"role\"] = \"architect\"\nprint(user[\"role\"])",
          hints: [
            "user[\"role\"] = \"architect\"",
            "Then print(user[\"role\"])",
            "Match the lowercase spelling.",
          ],
        },
      },
    ],
  },
  {
    id: 19,
    title: "Key Walk",
    job: "Distinguished Engineer",
    difficulty: "Hard",
    description: "for k in dict walks keys. .get returns None instead of crashing.",
    objective: "Count keys, walk them, and safely look up a missing field.",
    rewardCoins: 2800,
    rewardXp: 1100,
    unlockRewardId: "key-walk",
    unlockReward: "Key Walk",
    careerUnlock: "distinguished",
    chapter: "structures",
    steps: [
      {
        type: "brief",
        title: "Missing keys",
        body: "user[\"art\"] raises KeyError if art is not there. user.get(\"art\") returns None instead. for k in scores walks the keys in insertion order. len(scores) counts keys.",
        example: "print(scores.get(\"art\"))\nfor k in scores:\n    print(k)",
      },
      {
        type: "code",
        challenge: {
          id: "l19-len-get",
          title: "Safe lookup",
          concept: "len + get",
          prompt: "Print how many keys scores has, then print scores.get(\"art\") — that key is missing.",
          briefing: "Missing get returns None, which print shows as None.",
          example: "print(len(scores))\nprint(scores.get(\"art\"))",
          starter: "scores = {\"math\": 90, \"code\": 80}\n",
          expected: "2\nNone\n",
          solution: "scores = {\"math\": 90, \"code\": 80}\nprint(len(scores))\nprint(scores.get(\"art\"))",
          hints: [
            "print(len(scores))",
            "print(scores.get(\"art\"))",
            "None has a capital N.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l19-keys",
          title: "Walk keys",
          concept: "for in dict",
          prompt: "Loop through scores and print each key on its own line.",
          briefing: "for k in scores: prints math then code — insertion order.",
          example: "for k in scores:\n    print(k)",
          starter: "scores = {\"math\": 90, \"code\": 80}\n",
          expected: "math\ncode\n",
          solution: "scores = {\"math\": 90, \"code\": 80}\nfor k in scores:\n    print(k)",
          hints: [
            "for k in scores:",
            "print(k)",
            "Do not print the values in this task.",
          ],
        },
      },
    ],
  },
  {
    id: 20,
    title: "Roster Intel",
    job: "Fellow",
    difficulty: "Hard",
    description: "Filter a dictionary of people by their scores.",
    objective: "Print names whose score is at least 80.",
    rewardCoins: 3000,
    rewardXp: 1200,
    unlockRewardId: "roster-intel",
    unlockReward: "Roster Intel",
    careerUnlock: "distinguished",
    chapter: "structures",
    steps: [
      {
        type: "brief",
        title: "Key then value",
        body: "for name in team: gives keys. team[name] is the score. Combine with if to keep a shortlist. This is how live rosters are queried.",
        example: "for name in team:\n    if team[name] >= 80:\n        print(name)",
      },
      {
        type: "choice",
        concept: "in on dict",
        question: "What does \"Lin\" in team check?",
        options: [
          { id: "a", label: "Whether any score equals the text Lin", correct: false, explain: "in on a dict checks keys, not values." },
          { id: "b", label: "Whether Lin is a key in the dictionary", correct: true, explain: "\"Lin\" in team is True if that name exists as a key." },
          { id: "c", label: "Whether the dict is named Lin", correct: false, explain: "The dict is named team. in looks inside it." },
        ],
      },
      {
        type: "code",
        challenge: {
          id: "l20-filter",
          title: "Clearance list",
          concept: "dict + if",
          prompt: "team maps names to scores. Print every name whose score is at least 80, each on its own line, in dictionary order.",
          briefing: "Ada 90 and Kai 88 pass. Lin 70 does not.",
          example: "for name in team:\n    if team[name] >= 80:\n        print(name)",
          starter: "team = {\"Ada\": 90, \"Lin\": 70, \"Kai\": 88}\n",
          expected: "Ada\nKai\n",
          solution:
            "team = {\"Ada\": 90, \"Lin\": 70, \"Kai\": 88}\nfor name in team:\n    if team[name] >= 80:\n        print(name)",
          hints: [
            "for name in team:",
            "if team[name] >= 80:",
            "print(name)",
          ],
        },
      },
    ],
  },
  {
    id: 21,
    title: "Dual Params",
    job: "Fellow",
    difficulty: "Medium / Hard",
    description: "A function can take more than one input.",
    objective: "Build a tag and compute an area.",
    rewardCoins: 3200,
    rewardXp: 1300,
    unlockRewardId: "dual-params",
    unlockReward: "Dual Params",
    careerUnlock: "distinguished",
    chapter: "mastery",
    steps: [
      {
        type: "brief",
        title: "Order of arguments",
        body: "def tag(role, name): has two parameters. tag(\"Lead\", \"Ada\") sends Lead into role and Ada into name — order matches. return sends a value back; print is still separate.",
        example: "def tag(role, name):\n    return role + \": \" + name\nprint(tag(\"Lead\", \"Ada\"))",
      },
      {
        type: "code",
        challenge: {
          id: "l21-tag",
          title: "Name tag",
          concept: "two parameters",
          prompt: "Write tag(role, name) so it returns role, then \": \", then name. Print tag(\"Lead\", \"Ada\").",
          briefing: "Join three strings. Remember the colon and space.",
          example: "return role + \": \" + name",
          starter: "def tag(role, name):\n    return name\n",
          expected: "Lead: Ada\n",
          solution: "def tag(role, name):\n    return role + \": \" + name\nprint(tag(\"Lead\", \"Ada\"))",
          hints: [
            "return role + \": \" + name",
            "Colon then space inside the string.",
            "print(tag(\"Lead\", \"Ada\"))",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l21-area",
          title: "Floor plan",
          concept: "two parameters",
          prompt: "Write area(w, h) that returns w times h. Print area(4, 5).",
          briefing: "Numbers multiply with *. Return the product, then print the call.",
          example: "def area(w, h):\n    return w * h",
          starter: "def area(w, h):\n    return 0\n",
          expected: "20\n",
          solution: "def area(w, h):\n    return w * h\nprint(area(4, 5))",
          hints: [
            "return w * h",
            "print(area(4, 5))",
            "The answer is 20.",
          ],
        },
      },
    ],
  },
  {
    id: 22,
    title: "Return Path",
    job: "Fellow",
    difficulty: "Hard",
    description: "A function can return from more than one branch.",
    objective: "Grade two scores with one function.",
    rewardCoins: 3400,
    rewardXp: 1400,
    unlockRewardId: "return-path",
    unlockReward: "Return Path",
    careerUnlock: "fellow",
    chapter: "mastery",
    steps: [
      {
        type: "brief",
        title: "return exits immediately",
        body: "When a function hits return, it stops. You can return from the if branch and from the else branch. Call the function twice to test both paths.",
        example: "def grade(n):\n    if n >= 70:\n        return \"PASS\"\n    return \"RETRY\"",
      },
      {
        type: "code",
        challenge: {
          id: "l22-grade",
          title: "Two calls",
          concept: "return branches",
          prompt: "Write grade(n) that returns PASS if n is at least 70, otherwise RETRY. Print grade(70) and grade(40), each on its own line.",
          briefing: "Two print calls after the function. 70 is PASS. 40 is RETRY.",
          example: "print(grade(70))\nprint(grade(40))",
          starter: "def grade(n):\n    return \"RETRY\"\n",
          expected: "PASS\nRETRY\n",
          solution:
            "def grade(n):\n    if n >= 70:\n        return \"PASS\"\n    return \"RETRY\"\nprint(grade(70))\nprint(grade(40))",
          hints: [
            "if n >= 70: return \"PASS\"",
            "return \"RETRY\" after the if",
            "Print both calls.",
          ],
        },
      },
    ],
  },
  {
    id: 23,
    title: "Join Forge",
    job: "Python Master",
    difficulty: "Hard",
    description: "split turns text into a list. join turns a list into text.",
    objective: "Join with dashes. Split on commas.",
    rewardCoins: 3600,
    rewardXp: 1600,
    unlockRewardId: "join-forge",
    unlockReward: "Join Forge",
    careerUnlock: "fellow",
    chapter: "mastery",
    steps: [
      {
        type: "brief",
        title: "The separator is on the left",
        body: "\"-\".join(parts) puts a dash between each string in the list. text.split(\",\") cuts on commas and returns a list. join fails if a list item is a number — convert with str first in real work.",
        example: "print(\"-\".join([\"plan\", \"code\", \"ship\"]))\nprint(\"a,b,c\".split(\",\"))",
      },
      {
        type: "code",
        challenge: {
          id: "l23-join",
          title: "Pipeline",
          concept: "join",
          prompt: "parts is plan, code, ship. Print them joined with dashes, no extra spaces.",
          briefing: "The string before the dot is the glue.",
          example: "print(\"-\".join(parts))",
          starter: "parts = [\"plan\", \"code\", \"ship\"]\n",
          expected: "plan-code-ship\n",
          solution: "parts = [\"plan\", \"code\", \"ship\"]\nprint(\"-\".join(parts))",
          hints: [
            "\"-\".join(parts)",
            "Print that call.",
            "No spaces around the dashes.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l23-split",
          title: "Cut the csv",
          concept: "split",
          prompt: "text is a,b,c. Split on the comma and print the list.",
          briefing: "split returns a list of strings. print shows brackets and quotes.",
          example: "print(text.split(\",\"))",
          starter: "text = \"a,b,c\"\n",
          expected: "['a', 'b', 'c']\n",
          solution: "text = \"a,b,c\"\nprint(text.split(\",\"))",
          hints: [
            "text.split(\",\")",
            "The separator is a comma string.",
            "print the result.",
          ],
        },
      },
    ],
  },
  {
    id: 24,
    title: "Sort Engine",
    job: "Python Master",
    difficulty: "Hard",
    description: "sorted returns a new list. min, max, and your own mean.",
    objective: "Order a list, then write a mean function using //.",
    rewardCoins: 4000,
    rewardXp: 1800,
    unlockRewardId: "sort-engine",
    unlockReward: "Sort Engine",
    careerUnlock: "fellow",
    chapter: "mastery",
    steps: [
      {
        type: "brief",
        title: "sorted vs sort",
        body: "sorted(nums) returns a new ordered list and leaves nums alone. nums.sort() changes nums and returns None. // is integer division — 60 // 3 is 20, not 20.0.",
        example: "print(sorted([5, 1, 4]))\nprint(sum(xs) // len(xs))",
      },
      {
        type: "code",
        challenge: {
          id: "l24-sorted",
          title: "In order",
          concept: "sorted + min/max",
          prompt: "nums is [5, 1, 4]. Print the sorted list, then the max, then the min, each on its own line.",
          briefing: "sorted, max, and min are built-in functions — not methods on this task.",
          example: "print(sorted(nums))\nprint(max(nums))\nprint(min(nums))",
          starter: "nums = [5, 1, 4]\n",
          expected: "[1, 4, 5]\n5\n1\n",
          solution: "nums = [5, 1, 4]\nprint(sorted(nums))\nprint(max(nums))\nprint(min(nums))",
          hints: [
            "print(sorted(nums))",
            "print(max(nums))",
            "print(min(nums))",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l24-mean",
          title: "Integer mean",
          concept: "functions + //",
          prompt: "Write mean(xs) that returns the integer average: sum divided by length using //. Print mean([10, 20, 30]).",
          briefing: "sum(xs) // len(xs). Integer division drops the decimal.",
          example: "def mean(xs):\n    return sum(xs) // len(xs)",
          starter: "def mean(xs):\n    return 0\n",
          expected: "20\n",
          solution: "def mean(xs):\n    return sum(xs) // len(xs)\nprint(mean([10, 20, 30]))",
          hints: [
            "return sum(xs) // len(xs)",
            "Use // not /",
            "print(mean([10, 20, 30]))",
          ],
        },
      },
    ],
  },
  {
    id: 25,
    title: "Python Mastery",
    job: "Python Master",
    difficulty: "Expert",
    description: "Mid-course championship. Functions, dictionaries, and a written report — under the clock.",
    objective: "Clear every stage. Claim the Master's Apex. Then the advanced tracks open.",
    rewardCoins: 8000,
    rewardXp: 2500,
    unlockRewardId: "master-apex",
    unlockReward: "Master's Apex",
    careerUnlock: "master",
    chapter: "mastery",
    timeLimitSec: 180,
    championship: true,
    steps: [
      {
        type: "brief",
        title: "Everything you learned",
        body: "Stage 1 packages a decision in a function. Stage 2 filters a live roster. Stage 3 writes a text report from numbers. Same rules as always: colons, indents, quotes, and print.",
        example: "def label(score):\n    if score >= 70:\n        return \"PASS\"\n    return \"RETRY\"",
      },
      {
        type: "code",
        challenge: {
          id: "l25-label",
          title: "Stage 1 — Stamp",
          concept: "functions + if",
          prompt: "Write label(score) that returns PASS if score is at least 70, else RETRY. Print label(88) then label(40).",
          briefing: "Two returns. Two calls. Two lines of output.",
          example: "print(label(88))\nprint(label(40))",
          starter: "def label(score):\n    return score\n",
          expected: "PASS\nRETRY\n",
          solution:
            "def label(score):\n    if score >= 70:\n        return \"PASS\"\n    return \"RETRY\"\nprint(label(88))\nprint(label(40))",
          hints: [
            "if score >= 70: return \"PASS\"",
            "return \"RETRY\"",
            "Print both calls.",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l25-roster",
          title: "Stage 2 — Shortlist",
          concept: "dict filter",
          prompt: "scores maps names to exam results. Print names with a score of at least 70, each on its own line, in dictionary order.",
          briefing: "Ada 90 and Kai 70 pass. Lin 55 does not.",
          example: "for name in scores:\n    if scores[name] >= 70:\n        print(name)",
          starter: "scores = {\"Ada\": 90, \"Lin\": 55, \"Kai\": 70}\n",
          expected: "Ada\nKai\n",
          solution:
            "scores = {\"Ada\": 90, \"Lin\": 55, \"Kai\": 70}\nfor name in scores:\n    if scores[name] >= 70:\n        print(name)",
          hints: [
            "for name in scores:",
            "if scores[name] >= 70:",
            "print(name)",
          ],
        },
      },
      {
        type: "code",
        challenge: {
          id: "l25-report",
          title: "Stage 3 — Report",
          concept: "str + builtins",
          prompt: "Write report(nums) that returns the text sum= then the sum, then a space, then n= then the length. Print report([10, 20, 30]).",
          briefing: "Join strings with +. Convert numbers with str(). Example shape: sum=60 n=3",
          example: "return \"sum=\" + str(sum(nums)) + \" n=\" + str(len(nums))",
          starter: "def report(nums):\n    return \"\"\n",
          expected: "sum=60 n=3\n",
          solution:
            "def report(nums):\n    return \"sum=\" + str(sum(nums)) + \" n=\" + str(len(nums))\nprint(report([10, 20, 30]))",
          hints: [
            "str(sum(nums)) and str(len(nums))",
            "Space before n=",
            "print(report([10, 20, 30]))",
          ],
        },
      },
    ],
  },
];

export const LEVELS: LevelDef[] = [...CORE, ...LEVELS_PLUS, ...LEVELS_PRO];
